provider: scm
major-version: 1
makeTemplate: bridged
team: ecosystem
providerDefaultBranch: main
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
