// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class AggregateInterfaceLayer3LldpHighAvailability {
    /**
     * @return Passive pre negotiation
     * 
     */
    private @Nullable Boolean passivePreNegotiation;

    private AggregateInterfaceLayer3LldpHighAvailability() {}
    /**
     * @return Passive pre negotiation
     * 
     */
    public Optional<Boolean> passivePreNegotiation() {
        return Optional.ofNullable(this.passivePreNegotiation);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AggregateInterfaceLayer3LldpHighAvailability defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean passivePreNegotiation;
        public Builder() {}
        public Builder(AggregateInterfaceLayer3LldpHighAvailability defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.passivePreNegotiation = defaults.passivePreNegotiation;
        }

        @CustomType.Setter
        public Builder passivePreNegotiation(@Nullable Boolean passivePreNegotiation) {

            this.passivePreNegotiation = passivePreNegotiation;
            return this;
        }
        public AggregateInterfaceLayer3LldpHighAvailability build() {
            final var _resultValue = new AggregateInterfaceLayer3LldpHighAvailability();
            _resultValue.passivePreNegotiation = passivePreNegotiation;
            return _resultValue;
        }
    }
}
