// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import java.util.Objects;

@CustomType
public final class BgpAddressFamilyProfileIpv4MulticastSendCommunityAll {
    private BgpAddressFamilyProfileIpv4MulticastSendCommunityAll() {}

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(BgpAddressFamilyProfileIpv4MulticastSendCommunityAll defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        public Builder() {}
        public Builder(BgpAddressFamilyProfileIpv4MulticastSendCommunityAll defaults) {
    	      Objects.requireNonNull(defaults);
        }

        public BgpAddressFamilyProfileIpv4MulticastSendCommunityAll build() {
            final var _resultValue = new BgpAddressFamilyProfileIpv4MulticastSendCommunityAll();
            return _resultValue;
        }
    }
}
