// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.scm.outputs.BgpAddressFamilyProfileIpv4UnicastNextHopSelf;
import com.pulumi.scm.outputs.BgpAddressFamilyProfileIpv4UnicastNextHopSelfForce;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class BgpAddressFamilyProfileIpv4UnicastNextHop {
    /**
     * @return Self
     * &gt; ℹ️ **Note:** You must specify exactly one of `self` and `selfForce`.
     * 
     */
    private @Nullable BgpAddressFamilyProfileIpv4UnicastNextHopSelf self;
    /**
     * @return Self force
     * &gt; ℹ️ **Note:** You must specify exactly one of `self` and `selfForce`.
     * 
     */
    private @Nullable BgpAddressFamilyProfileIpv4UnicastNextHopSelfForce selfForce;

    private BgpAddressFamilyProfileIpv4UnicastNextHop() {}
    /**
     * @return Self
     * &gt; ℹ️ **Note:** You must specify exactly one of `self` and `selfForce`.
     * 
     */
    public Optional<BgpAddressFamilyProfileIpv4UnicastNextHopSelf> self() {
        return Optional.ofNullable(this.self);
    }
    /**
     * @return Self force
     * &gt; ℹ️ **Note:** You must specify exactly one of `self` and `selfForce`.
     * 
     */
    public Optional<BgpAddressFamilyProfileIpv4UnicastNextHopSelfForce> selfForce() {
        return Optional.ofNullable(this.selfForce);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(BgpAddressFamilyProfileIpv4UnicastNextHop defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable BgpAddressFamilyProfileIpv4UnicastNextHopSelf self;
        private @Nullable BgpAddressFamilyProfileIpv4UnicastNextHopSelfForce selfForce;
        public Builder() {}
        public Builder(BgpAddressFamilyProfileIpv4UnicastNextHop defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.self = defaults.self;
    	      this.selfForce = defaults.selfForce;
        }

        @CustomType.Setter
        public Builder self(@Nullable BgpAddressFamilyProfileIpv4UnicastNextHopSelf self) {

            this.self = self;
            return this;
        }
        @CustomType.Setter
        public Builder selfForce(@Nullable BgpAddressFamilyProfileIpv4UnicastNextHopSelfForce selfForce) {

            this.selfForce = selfForce;
            return this;
        }
        public BgpAddressFamilyProfileIpv4UnicastNextHop build() {
            final var _resultValue = new BgpAddressFamilyProfileIpv4UnicastNextHop();
            _resultValue.self = self;
            _resultValue.selfForce = selfForce;
            return _resultValue;
        }
    }
}
