// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DnsSecurityProfileBotnetDomainsDnsSecurityCategory {
    /**
     * @return The Action param. String must be one of these: `&#34;default&#34;`, `&#34;allow&#34;`, `&#34;block&#34;`, `&#34;sinkhole&#34;`. Default: `&#34;default&#34;`.
     * 
     */
    private @Nullable String action;
    /**
     * @return The LogLevel param. String must be one of these: `&#34;default&#34;`, `&#34;none&#34;`, `&#34;low&#34;`, `&#34;informational&#34;`, `&#34;medium&#34;`, `&#34;high&#34;`, `&#34;critical&#34;`. Default: `&#34;default&#34;`.
     * 
     */
    private @Nullable String logLevel;
    /**
     * @return The Name param.
     * 
     */
    private @Nullable String name;
    /**
     * @return The PacketCapture param. String must be one of these: `&#34;disable&#34;`, `&#34;single-packet&#34;`, `&#34;extended-capture&#34;`.
     * 
     */
    private @Nullable String packetCapture;

    private DnsSecurityProfileBotnetDomainsDnsSecurityCategory() {}
    /**
     * @return The Action param. String must be one of these: `&#34;default&#34;`, `&#34;allow&#34;`, `&#34;block&#34;`, `&#34;sinkhole&#34;`. Default: `&#34;default&#34;`.
     * 
     */
    public Optional<String> action() {
        return Optional.ofNullable(this.action);
    }
    /**
     * @return The LogLevel param. String must be one of these: `&#34;default&#34;`, `&#34;none&#34;`, `&#34;low&#34;`, `&#34;informational&#34;`, `&#34;medium&#34;`, `&#34;high&#34;`, `&#34;critical&#34;`. Default: `&#34;default&#34;`.
     * 
     */
    public Optional<String> logLevel() {
        return Optional.ofNullable(this.logLevel);
    }
    /**
     * @return The Name param.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return The PacketCapture param. String must be one of these: `&#34;disable&#34;`, `&#34;single-packet&#34;`, `&#34;extended-capture&#34;`.
     * 
     */
    public Optional<String> packetCapture() {
        return Optional.ofNullable(this.packetCapture);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DnsSecurityProfileBotnetDomainsDnsSecurityCategory defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String action;
        private @Nullable String logLevel;
        private @Nullable String name;
        private @Nullable String packetCapture;
        public Builder() {}
        public Builder(DnsSecurityProfileBotnetDomainsDnsSecurityCategory defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.action = defaults.action;
    	      this.logLevel = defaults.logLevel;
    	      this.name = defaults.name;
    	      this.packetCapture = defaults.packetCapture;
        }

        @CustomType.Setter
        public Builder action(@Nullable String action) {

            this.action = action;
            return this;
        }
        @CustomType.Setter
        public Builder logLevel(@Nullable String logLevel) {

            this.logLevel = logLevel;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder packetCapture(@Nullable String packetCapture) {

            this.packetCapture = packetCapture;
            return this;
        }
        public DnsSecurityProfileBotnetDomainsDnsSecurityCategory build() {
            final var _resultValue = new DnsSecurityProfileBotnetDomainsDnsSecurityCategory();
            _resultValue.action = action;
            _resultValue.logLevel = logLevel;
            _resultValue.name = name;
            _resultValue.packetCapture = packetCapture;
            return _resultValue;
        }
    }
}
