// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorEqualTo;
import com.pulumi.scm.outputs.GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan;
import com.pulumi.scm.outputs.GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorLessThan;
import com.pulumi.scm.outputs.GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorPatternMatch;
import java.util.Objects;

@CustomType
public final class GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperator {
    /**
     * @return Equal to
     * 
     */
    private GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorEqualTo equalTo;
    /**
     * @return Greater than
     * 
     */
    private GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan greaterThan;
    /**
     * @return Less than
     * 
     */
    private GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorLessThan lessThan;
    /**
     * @return Pattern match
     * 
     */
    private GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorPatternMatch patternMatch;

    private GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperator() {}
    /**
     * @return Equal to
     * 
     */
    public GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorEqualTo equalTo() {
        return this.equalTo;
    }
    /**
     * @return Greater than
     * 
     */
    public GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan greaterThan() {
        return this.greaterThan;
    }
    /**
     * @return Less than
     * 
     */
    public GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorLessThan lessThan() {
        return this.lessThan;
    }
    /**
     * @return Pattern match
     * 
     */
    public GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorPatternMatch patternMatch() {
        return this.patternMatch;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperator defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorEqualTo equalTo;
        private GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan greaterThan;
        private GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorLessThan lessThan;
        private GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorPatternMatch patternMatch;
        public Builder() {}
        public Builder(GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperator defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.equalTo = defaults.equalTo;
    	      this.greaterThan = defaults.greaterThan;
    	      this.lessThan = defaults.lessThan;
    	      this.patternMatch = defaults.patternMatch;
        }

        @CustomType.Setter
        public Builder equalTo(GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorEqualTo equalTo) {
            if (equalTo == null) {
              throw new MissingRequiredPropertyException("GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperator", "equalTo");
            }
            this.equalTo = equalTo;
            return this;
        }
        @CustomType.Setter
        public Builder greaterThan(GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan greaterThan) {
            if (greaterThan == null) {
              throw new MissingRequiredPropertyException("GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperator", "greaterThan");
            }
            this.greaterThan = greaterThan;
            return this;
        }
        @CustomType.Setter
        public Builder lessThan(GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorLessThan lessThan) {
            if (lessThan == null) {
              throw new MissingRequiredPropertyException("GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperator", "lessThan");
            }
            this.lessThan = lessThan;
            return this;
        }
        @CustomType.Setter
        public Builder patternMatch(GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorPatternMatch patternMatch) {
            if (patternMatch == null) {
              throw new MissingRequiredPropertyException("GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperator", "patternMatch");
            }
            this.patternMatch = patternMatch;
            return this;
        }
        public GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperator build() {
            final var _resultValue = new GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperator();
            _resultValue.equalTo = equalTo;
            _resultValue.greaterThan = greaterThan;
            _resultValue.lessThan = lessThan;
            _resultValue.patternMatch = patternMatch;
            return _resultValue;
        }
    }
}
