// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThanQualifier;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan {
    /**
     * @return Context
     * 
     */
    private String context;
    /**
     * @return Qualifier
     * 
     */
    private List<GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThanQualifier> qualifiers;
    /**
     * @return Value
     * 
     */
    private Integer value;

    private GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan() {}
    /**
     * @return Context
     * 
     */
    public String context() {
        return this.context;
    }
    /**
     * @return Qualifier
     * 
     */
    public List<GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThanQualifier> qualifiers() {
        return this.qualifiers;
    }
    /**
     * @return Value
     * 
     */
    public Integer value() {
        return this.value;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String context;
        private List<GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThanQualifier> qualifiers;
        private Integer value;
        public Builder() {}
        public Builder(GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.context = defaults.context;
    	      this.qualifiers = defaults.qualifiers;
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder context(String context) {
            if (context == null) {
              throw new MissingRequiredPropertyException("GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan", "context");
            }
            this.context = context;
            return this;
        }
        @CustomType.Setter
        public Builder qualifiers(List<GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThanQualifier> qualifiers) {
            if (qualifiers == null) {
              throw new MissingRequiredPropertyException("GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan", "qualifiers");
            }
            this.qualifiers = qualifiers;
            return this;
        }
        public Builder qualifiers(GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThanQualifier... qualifiers) {
            return qualifiers(List.of(qualifiers));
        }
        @CustomType.Setter
        public Builder value(Integer value) {
            if (value == null) {
              throw new MissingRequiredPropertyException("GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan", "value");
            }
            this.value = value;
            return this;
        }
        public GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan build() {
            final var _resultValue = new GetAntiSpywareSignatureSignatureStandardAndConditionOrConditionOperatorGreaterThan();
            _resultValue.context = context;
            _resultValue.qualifiers = qualifiers;
            _resultValue.value = value;
            return _resultValue;
        }
    }
}
