// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelf;
import com.pulumi.scm.outputs.GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelfForce;
import java.util.Objects;

@CustomType
public final class GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHop {
    /**
     * @return Self
     * 
     */
    private GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelf self;
    /**
     * @return Self force
     * 
     */
    private GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelfForce selfForce;

    private GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHop() {}
    /**
     * @return Self
     * 
     */
    public GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelf self() {
        return this.self;
    }
    /**
     * @return Self force
     * 
     */
    public GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelfForce selfForce() {
        return this.selfForce;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHop defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelf self;
        private GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelfForce selfForce;
        public Builder() {}
        public Builder(GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHop defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.self = defaults.self;
    	      this.selfForce = defaults.selfForce;
        }

        @CustomType.Setter
        public Builder self(GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelf self) {
            if (self == null) {
              throw new MissingRequiredPropertyException("GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHop", "self");
            }
            this.self = self;
            return this;
        }
        @CustomType.Setter
        public Builder selfForce(GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelfForce selfForce) {
            if (selfForce == null) {
              throw new MissingRequiredPropertyException("GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHop", "selfForce");
            }
            this.selfForce = selfForce;
            return this;
        }
        public GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHop build() {
            final var _resultValue = new GetBgpAddressFamilyProfileIpv4Ipv4MulticastNextHop();
            _resultValue.self = self;
            _resultValue.selfForce = selfForce;
            return _resultValue;
        }
    }
}
