// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetBgpFilteringProfileIpv4Ipv4UnicastInboundNetworkFilters {
    /**
     * @return Distribute list
     * 
     */
    private String distributeList;
    /**
     * @return Prefix list
     * 
     */
    private String prefixList;

    private GetBgpFilteringProfileIpv4Ipv4UnicastInboundNetworkFilters() {}
    /**
     * @return Distribute list
     * 
     */
    public String distributeList() {
        return this.distributeList;
    }
    /**
     * @return Prefix list
     * 
     */
    public String prefixList() {
        return this.prefixList;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetBgpFilteringProfileIpv4Ipv4UnicastInboundNetworkFilters defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String distributeList;
        private String prefixList;
        public Builder() {}
        public Builder(GetBgpFilteringProfileIpv4Ipv4UnicastInboundNetworkFilters defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.distributeList = defaults.distributeList;
    	      this.prefixList = defaults.prefixList;
        }

        @CustomType.Setter
        public Builder distributeList(String distributeList) {
            if (distributeList == null) {
              throw new MissingRequiredPropertyException("GetBgpFilteringProfileIpv4Ipv4UnicastInboundNetworkFilters", "distributeList");
            }
            this.distributeList = distributeList;
            return this;
        }
        @CustomType.Setter
        public Builder prefixList(String prefixList) {
            if (prefixList == null) {
              throw new MissingRequiredPropertyException("GetBgpFilteringProfileIpv4Ipv4UnicastInboundNetworkFilters", "prefixList");
            }
            this.prefixList = prefixList;
            return this;
        }
        public GetBgpFilteringProfileIpv4Ipv4UnicastInboundNetworkFilters build() {
            final var _resultValue = new GetBgpFilteringProfileIpv4Ipv4UnicastInboundNetworkFilters();
            _resultValue.distributeList = distributeList;
            _resultValue.prefixList = prefixList;
            return _resultValue;
        }
    }
}
