// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetDataObjectPatternTypePredefinedPattern {
    /**
     * @return File type
     * 
     */
    private List<String> fileTypes;
    /**
     * @return Name
     * 
     */
    private String name;

    private GetDataObjectPatternTypePredefinedPattern() {}
    /**
     * @return File type
     * 
     */
    public List<String> fileTypes() {
        return this.fileTypes;
    }
    /**
     * @return Name
     * 
     */
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDataObjectPatternTypePredefinedPattern defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> fileTypes;
        private String name;
        public Builder() {}
        public Builder(GetDataObjectPatternTypePredefinedPattern defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.fileTypes = defaults.fileTypes;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder fileTypes(List<String> fileTypes) {
            if (fileTypes == null) {
              throw new MissingRequiredPropertyException("GetDataObjectPatternTypePredefinedPattern", "fileTypes");
            }
            this.fileTypes = fileTypes;
            return this;
        }
        public Builder fileTypes(String... fileTypes) {
            return fileTypes(List.of(fileTypes));
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetDataObjectPatternTypePredefinedPattern", "name");
            }
            this.name = name;
            return this;
        }
        public GetDataObjectPatternTypePredefinedPattern build() {
            final var _resultValue = new GetDataObjectPatternTypePredefinedPattern();
            _resultValue.fileTypes = fileTypes;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
