// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetForwardingProfileRegionalAndCustomProxyProxy2 {
    /**
     * @return Fqdn of the secondary (backup) proxy server used for failover scenarios
     * 
     */
    private String fqdn;
    /**
     * @return Geographic or network location identifier for the secondary proxy server
     * 
     */
    private String location;
    /**
     * @return port number for secondary proxy
     * 
     */
    private Integer port;

    private GetForwardingProfileRegionalAndCustomProxyProxy2() {}
    /**
     * @return Fqdn of the secondary (backup) proxy server used for failover scenarios
     * 
     */
    public String fqdn() {
        return this.fqdn;
    }
    /**
     * @return Geographic or network location identifier for the secondary proxy server
     * 
     */
    public String location() {
        return this.location;
    }
    /**
     * @return port number for secondary proxy
     * 
     */
    public Integer port() {
        return this.port;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetForwardingProfileRegionalAndCustomProxyProxy2 defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String fqdn;
        private String location;
        private Integer port;
        public Builder() {}
        public Builder(GetForwardingProfileRegionalAndCustomProxyProxy2 defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.fqdn = defaults.fqdn;
    	      this.location = defaults.location;
    	      this.port = defaults.port;
        }

        @CustomType.Setter
        public Builder fqdn(String fqdn) {
            if (fqdn == null) {
              throw new MissingRequiredPropertyException("GetForwardingProfileRegionalAndCustomProxyProxy2", "fqdn");
            }
            this.fqdn = fqdn;
            return this;
        }
        @CustomType.Setter
        public Builder location(String location) {
            if (location == null) {
              throw new MissingRequiredPropertyException("GetForwardingProfileRegionalAndCustomProxyProxy2", "location");
            }
            this.location = location;
            return this;
        }
        @CustomType.Setter
        public Builder port(Integer port) {
            if (port == null) {
              throw new MissingRequiredPropertyException("GetForwardingProfileRegionalAndCustomProxyProxy2", "port");
            }
            this.port = port;
            return this;
        }
        public GetForwardingProfileRegionalAndCustomProxyProxy2 build() {
            final var _resultValue = new GetForwardingProfileRegionalAndCustomProxyProxy2();
            _resultValue.fqdn = fqdn;
            _resultValue.location = location;
            _resultValue.port = port;
            return _resultValue;
        }
    }
}
