// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetForwardingProfileTypePacFileBlockRule;
import com.pulumi.scm.outputs.GetForwardingProfileTypePacFileForwardingRule;
import java.lang.Boolean;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetForwardingProfileTypePacFile {
    /**
     * @return Basic block rule configuration for PAC file and GlobalProtect proxy profiles
     * 
     */
    private GetForwardingProfileTypePacFileBlockRule blockRule;
    /**
     * @return List of PAC file-based forwarding rules
     * 
     */
    private List<GetForwardingProfileTypePacFileForwardingRule> forwardingRules;
    /**
     * @return User upload PAC file for PAC file based forwarding configuration
     * 
     */
    private Boolean pacUpload;

    private GetForwardingProfileTypePacFile() {}
    /**
     * @return Basic block rule configuration for PAC file and GlobalProtect proxy profiles
     * 
     */
    public GetForwardingProfileTypePacFileBlockRule blockRule() {
        return this.blockRule;
    }
    /**
     * @return List of PAC file-based forwarding rules
     * 
     */
    public List<GetForwardingProfileTypePacFileForwardingRule> forwardingRules() {
        return this.forwardingRules;
    }
    /**
     * @return User upload PAC file for PAC file based forwarding configuration
     * 
     */
    public Boolean pacUpload() {
        return this.pacUpload;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetForwardingProfileTypePacFile defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetForwardingProfileTypePacFileBlockRule blockRule;
        private List<GetForwardingProfileTypePacFileForwardingRule> forwardingRules;
        private Boolean pacUpload;
        public Builder() {}
        public Builder(GetForwardingProfileTypePacFile defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.blockRule = defaults.blockRule;
    	      this.forwardingRules = defaults.forwardingRules;
    	      this.pacUpload = defaults.pacUpload;
        }

        @CustomType.Setter
        public Builder blockRule(GetForwardingProfileTypePacFileBlockRule blockRule) {
            if (blockRule == null) {
              throw new MissingRequiredPropertyException("GetForwardingProfileTypePacFile", "blockRule");
            }
            this.blockRule = blockRule;
            return this;
        }
        @CustomType.Setter
        public Builder forwardingRules(List<GetForwardingProfileTypePacFileForwardingRule> forwardingRules) {
            if (forwardingRules == null) {
              throw new MissingRequiredPropertyException("GetForwardingProfileTypePacFile", "forwardingRules");
            }
            this.forwardingRules = forwardingRules;
            return this;
        }
        public Builder forwardingRules(GetForwardingProfileTypePacFileForwardingRule... forwardingRules) {
            return forwardingRules(List.of(forwardingRules));
        }
        @CustomType.Setter
        public Builder pacUpload(Boolean pacUpload) {
            if (pacUpload == null) {
              throw new MissingRequiredPropertyException("GetForwardingProfileTypePacFile", "pacUpload");
            }
            this.pacUpload = pacUpload;
            return this;
        }
        public GetForwardingProfileTypePacFile build() {
            final var _resultValue = new GetForwardingProfileTypePacFile();
            _resultValue.blockRule = blockRule;
            _resultValue.forwardingRules = forwardingRules;
            _resultValue.pacUpload = pacUpload;
            return _resultValue;
        }
    }
}
