// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetIkeGatewayProtocolIkev2Dpd;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetIkeGatewayProtocolIkev2 {
    /**
     * @return The Dpd param.
     * 
     */
    private GetIkeGatewayProtocolIkev2Dpd dpd;
    /**
     * @return The IkeCryptoProfile param.
     * 
     */
    private String ikeCryptoProfile;

    private GetIkeGatewayProtocolIkev2() {}
    /**
     * @return The Dpd param.
     * 
     */
    public GetIkeGatewayProtocolIkev2Dpd dpd() {
        return this.dpd;
    }
    /**
     * @return The IkeCryptoProfile param.
     * 
     */
    public String ikeCryptoProfile() {
        return this.ikeCryptoProfile;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetIkeGatewayProtocolIkev2 defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetIkeGatewayProtocolIkev2Dpd dpd;
        private String ikeCryptoProfile;
        public Builder() {}
        public Builder(GetIkeGatewayProtocolIkev2 defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dpd = defaults.dpd;
    	      this.ikeCryptoProfile = defaults.ikeCryptoProfile;
        }

        @CustomType.Setter
        public Builder dpd(GetIkeGatewayProtocolIkev2Dpd dpd) {
            if (dpd == null) {
              throw new MissingRequiredPropertyException("GetIkeGatewayProtocolIkev2", "dpd");
            }
            this.dpd = dpd;
            return this;
        }
        @CustomType.Setter
        public Builder ikeCryptoProfile(String ikeCryptoProfile) {
            if (ikeCryptoProfile == null) {
              throw new MissingRequiredPropertyException("GetIkeGatewayProtocolIkev2", "ikeCryptoProfile");
            }
            this.ikeCryptoProfile = ikeCryptoProfile;
            return this;
        }
        public GetIkeGatewayProtocolIkev2 build() {
            final var _resultValue = new GetIkeGatewayProtocolIkev2();
            _resultValue.dpd = dpd;
            _resultValue.ikeCryptoProfile = ikeCryptoProfile;
            return _resultValue;
        }
    }
}
