// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetLogicalRouterVrfMulticastMsdpPeerLocalAddress;
import com.pulumi.scm.outputs.GetLogicalRouterVrfMulticastMsdpPeerPeerAddress;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetLogicalRouterVrfMulticastMsdpPeer {
    /**
     * @return Authentication
     * 
     */
    private String authentication;
    /**
     * @return Enable
     * 
     */
    private Boolean enable;
    /**
     * @return Inbound sa filter
     * 
     */
    private String inboundSaFilter;
    /**
     * @return Local address
     * 
     */
    private GetLogicalRouterVrfMulticastMsdpPeerLocalAddress localAddress;
    /**
     * @return Max sa
     * 
     */
    private Integer maxSa;
    /**
     * @return Name
     * 
     */
    private String name;
    /**
     * @return Outbound sa filter
     * 
     */
    private String outboundSaFilter;
    /**
     * @return Peer address
     * 
     */
    private GetLogicalRouterVrfMulticastMsdpPeerPeerAddress peerAddress;
    /**
     * @return Peer as
     * 
     */
    private String peerAs;

    private GetLogicalRouterVrfMulticastMsdpPeer() {}
    /**
     * @return Authentication
     * 
     */
    public String authentication() {
        return this.authentication;
    }
    /**
     * @return Enable
     * 
     */
    public Boolean enable() {
        return this.enable;
    }
    /**
     * @return Inbound sa filter
     * 
     */
    public String inboundSaFilter() {
        return this.inboundSaFilter;
    }
    /**
     * @return Local address
     * 
     */
    public GetLogicalRouterVrfMulticastMsdpPeerLocalAddress localAddress() {
        return this.localAddress;
    }
    /**
     * @return Max sa
     * 
     */
    public Integer maxSa() {
        return this.maxSa;
    }
    /**
     * @return Name
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Outbound sa filter
     * 
     */
    public String outboundSaFilter() {
        return this.outboundSaFilter;
    }
    /**
     * @return Peer address
     * 
     */
    public GetLogicalRouterVrfMulticastMsdpPeerPeerAddress peerAddress() {
        return this.peerAddress;
    }
    /**
     * @return Peer as
     * 
     */
    public String peerAs() {
        return this.peerAs;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetLogicalRouterVrfMulticastMsdpPeer defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String authentication;
        private Boolean enable;
        private String inboundSaFilter;
        private GetLogicalRouterVrfMulticastMsdpPeerLocalAddress localAddress;
        private Integer maxSa;
        private String name;
        private String outboundSaFilter;
        private GetLogicalRouterVrfMulticastMsdpPeerPeerAddress peerAddress;
        private String peerAs;
        public Builder() {}
        public Builder(GetLogicalRouterVrfMulticastMsdpPeer defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.authentication = defaults.authentication;
    	      this.enable = defaults.enable;
    	      this.inboundSaFilter = defaults.inboundSaFilter;
    	      this.localAddress = defaults.localAddress;
    	      this.maxSa = defaults.maxSa;
    	      this.name = defaults.name;
    	      this.outboundSaFilter = defaults.outboundSaFilter;
    	      this.peerAddress = defaults.peerAddress;
    	      this.peerAs = defaults.peerAs;
        }

        @CustomType.Setter
        public Builder authentication(String authentication) {
            if (authentication == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfMulticastMsdpPeer", "authentication");
            }
            this.authentication = authentication;
            return this;
        }
        @CustomType.Setter
        public Builder enable(Boolean enable) {
            if (enable == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfMulticastMsdpPeer", "enable");
            }
            this.enable = enable;
            return this;
        }
        @CustomType.Setter
        public Builder inboundSaFilter(String inboundSaFilter) {
            if (inboundSaFilter == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfMulticastMsdpPeer", "inboundSaFilter");
            }
            this.inboundSaFilter = inboundSaFilter;
            return this;
        }
        @CustomType.Setter
        public Builder localAddress(GetLogicalRouterVrfMulticastMsdpPeerLocalAddress localAddress) {
            if (localAddress == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfMulticastMsdpPeer", "localAddress");
            }
            this.localAddress = localAddress;
            return this;
        }
        @CustomType.Setter
        public Builder maxSa(Integer maxSa) {
            if (maxSa == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfMulticastMsdpPeer", "maxSa");
            }
            this.maxSa = maxSa;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfMulticastMsdpPeer", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder outboundSaFilter(String outboundSaFilter) {
            if (outboundSaFilter == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfMulticastMsdpPeer", "outboundSaFilter");
            }
            this.outboundSaFilter = outboundSaFilter;
            return this;
        }
        @CustomType.Setter
        public Builder peerAddress(GetLogicalRouterVrfMulticastMsdpPeerPeerAddress peerAddress) {
            if (peerAddress == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfMulticastMsdpPeer", "peerAddress");
            }
            this.peerAddress = peerAddress;
            return this;
        }
        @CustomType.Setter
        public Builder peerAs(String peerAs) {
            if (peerAs == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfMulticastMsdpPeer", "peerAs");
            }
            this.peerAs = peerAs;
            return this;
        }
        public GetLogicalRouterVrfMulticastMsdpPeer build() {
            final var _resultValue = new GetLogicalRouterVrfMulticastMsdpPeer();
            _resultValue.authentication = authentication;
            _resultValue.enable = enable;
            _resultValue.inboundSaFilter = inboundSaFilter;
            _resultValue.localAddress = localAddress;
            _resultValue.maxSa = maxSa;
            _resultValue.name = name;
            _resultValue.outboundSaFilter = outboundSaFilter;
            _resultValue.peerAddress = peerAddress;
            _resultValue.peerAs = peerAs;
            return _resultValue;
        }
    }
}
