// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyAdvertiseFilter;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyNonExistFilter;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicy {
    /**
     * @return Advertise filters
     * 
     */
    private List<GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyAdvertiseFilter> advertiseFilters;
    /**
     * @return Enable
     * 
     */
    private Boolean enable;
    /**
     * @return Name
     * 
     */
    private String name;
    /**
     * @return Non exist filters
     * 
     */
    private List<GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyNonExistFilter> nonExistFilters;
    /**
     * @return Used by
     * 
     */
    private List<String> usedBies;

    private GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicy() {}
    /**
     * @return Advertise filters
     * 
     */
    public List<GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyAdvertiseFilter> advertiseFilters() {
        return this.advertiseFilters;
    }
    /**
     * @return Enable
     * 
     */
    public Boolean enable() {
        return this.enable;
    }
    /**
     * @return Name
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Non exist filters
     * 
     */
    public List<GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyNonExistFilter> nonExistFilters() {
        return this.nonExistFilters;
    }
    /**
     * @return Used by
     * 
     */
    public List<String> usedBies() {
        return this.usedBies;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicy defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyAdvertiseFilter> advertiseFilters;
        private Boolean enable;
        private String name;
        private List<GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyNonExistFilter> nonExistFilters;
        private List<String> usedBies;
        public Builder() {}
        public Builder(GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicy defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.advertiseFilters = defaults.advertiseFilters;
    	      this.enable = defaults.enable;
    	      this.name = defaults.name;
    	      this.nonExistFilters = defaults.nonExistFilters;
    	      this.usedBies = defaults.usedBies;
        }

        @CustomType.Setter
        public Builder advertiseFilters(List<GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyAdvertiseFilter> advertiseFilters) {
            if (advertiseFilters == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicy", "advertiseFilters");
            }
            this.advertiseFilters = advertiseFilters;
            return this;
        }
        public Builder advertiseFilters(GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyAdvertiseFilter... advertiseFilters) {
            return advertiseFilters(List.of(advertiseFilters));
        }
        @CustomType.Setter
        public Builder enable(Boolean enable) {
            if (enable == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicy", "enable");
            }
            this.enable = enable;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicy", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder nonExistFilters(List<GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyNonExistFilter> nonExistFilters) {
            if (nonExistFilters == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicy", "nonExistFilters");
            }
            this.nonExistFilters = nonExistFilters;
            return this;
        }
        public Builder nonExistFilters(GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicyNonExistFilter... nonExistFilters) {
            return nonExistFilters(List.of(nonExistFilters));
        }
        @CustomType.Setter
        public Builder usedBies(List<String> usedBies) {
            if (usedBies == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicy", "usedBies");
            }
            this.usedBies = usedBies;
            return this;
        }
        public Builder usedBies(String... usedBies) {
            return usedBies(List.of(usedBies));
        }
        public GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicy build() {
            final var _resultValue = new GetLogicalRouterVrfBgpPolicyConditionalAdvertisementPolicy();
            _resultValue.advertiseFilters = advertiseFilters;
            _resultValue.enable = enable;
            _resultValue.name = name;
            _resultValue.nonExistFilters = nonExistFilters;
            _resultValue.usedBies = usedBies;
            return _resultValue;
        }
    }
}
