// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetLogicalRouterListDataVrfMulticastInterfaceGroupGroupPermissionSourceSpecificMulticast {
    /**
     * @return Group address
     * 
     */
    private String groupAddress;
    /**
     * @return Included
     * 
     */
    private Boolean included;
    /**
     * @return Name
     * 
     */
    private String name;
    /**
     * @return Source address
     * 
     */
    private String sourceAddress;

    private GetLogicalRouterListDataVrfMulticastInterfaceGroupGroupPermissionSourceSpecificMulticast() {}
    /**
     * @return Group address
     * 
     */
    public String groupAddress() {
        return this.groupAddress;
    }
    /**
     * @return Included
     * 
     */
    public Boolean included() {
        return this.included;
    }
    /**
     * @return Name
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Source address
     * 
     */
    public String sourceAddress() {
        return this.sourceAddress;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetLogicalRouterListDataVrfMulticastInterfaceGroupGroupPermissionSourceSpecificMulticast defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String groupAddress;
        private Boolean included;
        private String name;
        private String sourceAddress;
        public Builder() {}
        public Builder(GetLogicalRouterListDataVrfMulticastInterfaceGroupGroupPermissionSourceSpecificMulticast defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.groupAddress = defaults.groupAddress;
    	      this.included = defaults.included;
    	      this.name = defaults.name;
    	      this.sourceAddress = defaults.sourceAddress;
        }

        @CustomType.Setter
        public Builder groupAddress(String groupAddress) {
            if (groupAddress == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterListDataVrfMulticastInterfaceGroupGroupPermissionSourceSpecificMulticast", "groupAddress");
            }
            this.groupAddress = groupAddress;
            return this;
        }
        @CustomType.Setter
        public Builder included(Boolean included) {
            if (included == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterListDataVrfMulticastInterfaceGroupGroupPermissionSourceSpecificMulticast", "included");
            }
            this.included = included;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterListDataVrfMulticastInterfaceGroupGroupPermissionSourceSpecificMulticast", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder sourceAddress(String sourceAddress) {
            if (sourceAddress == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterListDataVrfMulticastInterfaceGroupGroupPermissionSourceSpecificMulticast", "sourceAddress");
            }
            this.sourceAddress = sourceAddress;
            return this;
        }
        public GetLogicalRouterListDataVrfMulticastInterfaceGroupGroupPermissionSourceSpecificMulticast build() {
            final var _resultValue = new GetLogicalRouterListDataVrfMulticastInterfaceGroupGroupPermissionSourceSpecificMulticast();
            _resultValue.groupAddress = groupAddress;
            _resultValue.included = included;
            _resultValue.name = name;
            _resultValue.sourceAddress = sourceAddress;
            return _resultValue;
        }
    }
}
