// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetLogicalRouterListDataVrfRibFilterIpv4Static {
    /**
     * @return Route map
     * 
     */
    private String routeMap;

    private GetLogicalRouterListDataVrfRibFilterIpv4Static() {}
    /**
     * @return Route map
     * 
     */
    public String routeMap() {
        return this.routeMap;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetLogicalRouterListDataVrfRibFilterIpv4Static defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String routeMap;
        public Builder() {}
        public Builder(GetLogicalRouterListDataVrfRibFilterIpv4Static defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.routeMap = defaults.routeMap;
        }

        @CustomType.Setter
        public Builder routeMap(String routeMap) {
            if (routeMap == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterListDataVrfRibFilterIpv4Static", "routeMap");
            }
            this.routeMap = routeMap;
            return this;
        }
        public GetLogicalRouterListDataVrfRibFilterIpv4Static build() {
            final var _resultValue = new GetLogicalRouterListDataVrfRibFilterIpv4Static();
            _resultValue.routeMap = routeMap;
            return _resultValue;
        }
    }
}
