// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpAdvertiseNetwork;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpAggregate;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpAggregateRoute;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpGlobalBfd;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpGracefulRestart;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpMed;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpPeerGroup;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpPolicy;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpRedistRule;
import com.pulumi.scm.outputs.GetLogicalRouterVrfBgpRedistributionProfile;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetLogicalRouterVrfBgp {
    /**
     * @return Advertise network
     * 
     */
    private GetLogicalRouterVrfBgpAdvertiseNetwork advertiseNetwork;
    /**
     * @return Aggregate
     * 
     */
    private GetLogicalRouterVrfBgpAggregate aggregate;
    /**
     * @return Aggregate routes
     * 
     */
    private List<GetLogicalRouterVrfBgpAggregateRoute> aggregateRoutes;
    /**
     * @return Allow redist default route
     * 
     */
    private Boolean allowRedistDefaultRoute;
    /**
     * @return Always advertise network route
     * 
     */
    private Boolean alwaysAdvertiseNetworkRoute;
    /**
     * @return As format
     * 
     */
    private String asFormat;
    /**
     * @return Confederation member as
     * 
     */
    private String confederationMemberAs;
    /**
     * @return Default local preference
     * 
     */
    private Integer defaultLocalPreference;
    /**
     * @return Ecmp multi as
     * 
     */
    private Boolean ecmpMultiAs;
    /**
     * @return Enable
     * 
     */
    private Boolean enable;
    /**
     * @return Enforce first as
     * 
     */
    private Boolean enforceFirstAs;
    /**
     * @return Fast external failover
     * 
     */
    private Boolean fastExternalFailover;
    /**
     * @return Global bfd
     * 
     */
    private GetLogicalRouterVrfBgpGlobalBfd globalBfd;
    /**
     * @return Graceful restart
     * 
     */
    private GetLogicalRouterVrfBgpGracefulRestart gracefulRestart;
    /**
     * @return Graceful shutdown
     * 
     */
    private Boolean gracefulShutdown;
    /**
     * @return Install route
     * 
     */
    private Boolean installRoute;
    /**
     * @return Local as
     * 
     */
    private String localAs;
    /**
     * @return Med
     * 
     */
    private GetLogicalRouterVrfBgpMed med;
    /**
     * @return Peer group
     * 
     */
    private List<GetLogicalRouterVrfBgpPeerGroup> peerGroups;
    /**
     * @return Policy
     * 
     */
    private GetLogicalRouterVrfBgpPolicy policy;
    /**
     * @return Redist rules
     * 
     */
    private List<GetLogicalRouterVrfBgpRedistRule> redistRules;
    /**
     * @return Redistribution profile
     * 
     */
    private GetLogicalRouterVrfBgpRedistributionProfile redistributionProfile;
    /**
     * @return Reject default route
     * 
     */
    private Boolean rejectDefaultRoute;
    /**
     * @return Router id
     * 
     */
    private String routerId;

    private GetLogicalRouterVrfBgp() {}
    /**
     * @return Advertise network
     * 
     */
    public GetLogicalRouterVrfBgpAdvertiseNetwork advertiseNetwork() {
        return this.advertiseNetwork;
    }
    /**
     * @return Aggregate
     * 
     */
    public GetLogicalRouterVrfBgpAggregate aggregate() {
        return this.aggregate;
    }
    /**
     * @return Aggregate routes
     * 
     */
    public List<GetLogicalRouterVrfBgpAggregateRoute> aggregateRoutes() {
        return this.aggregateRoutes;
    }
    /**
     * @return Allow redist default route
     * 
     */
    public Boolean allowRedistDefaultRoute() {
        return this.allowRedistDefaultRoute;
    }
    /**
     * @return Always advertise network route
     * 
     */
    public Boolean alwaysAdvertiseNetworkRoute() {
        return this.alwaysAdvertiseNetworkRoute;
    }
    /**
     * @return As format
     * 
     */
    public String asFormat() {
        return this.asFormat;
    }
    /**
     * @return Confederation member as
     * 
     */
    public String confederationMemberAs() {
        return this.confederationMemberAs;
    }
    /**
     * @return Default local preference
     * 
     */
    public Integer defaultLocalPreference() {
        return this.defaultLocalPreference;
    }
    /**
     * @return Ecmp multi as
     * 
     */
    public Boolean ecmpMultiAs() {
        return this.ecmpMultiAs;
    }
    /**
     * @return Enable
     * 
     */
    public Boolean enable() {
        return this.enable;
    }
    /**
     * @return Enforce first as
     * 
     */
    public Boolean enforceFirstAs() {
        return this.enforceFirstAs;
    }
    /**
     * @return Fast external failover
     * 
     */
    public Boolean fastExternalFailover() {
        return this.fastExternalFailover;
    }
    /**
     * @return Global bfd
     * 
     */
    public GetLogicalRouterVrfBgpGlobalBfd globalBfd() {
        return this.globalBfd;
    }
    /**
     * @return Graceful restart
     * 
     */
    public GetLogicalRouterVrfBgpGracefulRestart gracefulRestart() {
        return this.gracefulRestart;
    }
    /**
     * @return Graceful shutdown
     * 
     */
    public Boolean gracefulShutdown() {
        return this.gracefulShutdown;
    }
    /**
     * @return Install route
     * 
     */
    public Boolean installRoute() {
        return this.installRoute;
    }
    /**
     * @return Local as
     * 
     */
    public String localAs() {
        return this.localAs;
    }
    /**
     * @return Med
     * 
     */
    public GetLogicalRouterVrfBgpMed med() {
        return this.med;
    }
    /**
     * @return Peer group
     * 
     */
    public List<GetLogicalRouterVrfBgpPeerGroup> peerGroups() {
        return this.peerGroups;
    }
    /**
     * @return Policy
     * 
     */
    public GetLogicalRouterVrfBgpPolicy policy() {
        return this.policy;
    }
    /**
     * @return Redist rules
     * 
     */
    public List<GetLogicalRouterVrfBgpRedistRule> redistRules() {
        return this.redistRules;
    }
    /**
     * @return Redistribution profile
     * 
     */
    public GetLogicalRouterVrfBgpRedistributionProfile redistributionProfile() {
        return this.redistributionProfile;
    }
    /**
     * @return Reject default route
     * 
     */
    public Boolean rejectDefaultRoute() {
        return this.rejectDefaultRoute;
    }
    /**
     * @return Router id
     * 
     */
    public String routerId() {
        return this.routerId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetLogicalRouterVrfBgp defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetLogicalRouterVrfBgpAdvertiseNetwork advertiseNetwork;
        private GetLogicalRouterVrfBgpAggregate aggregate;
        private List<GetLogicalRouterVrfBgpAggregateRoute> aggregateRoutes;
        private Boolean allowRedistDefaultRoute;
        private Boolean alwaysAdvertiseNetworkRoute;
        private String asFormat;
        private String confederationMemberAs;
        private Integer defaultLocalPreference;
        private Boolean ecmpMultiAs;
        private Boolean enable;
        private Boolean enforceFirstAs;
        private Boolean fastExternalFailover;
        private GetLogicalRouterVrfBgpGlobalBfd globalBfd;
        private GetLogicalRouterVrfBgpGracefulRestart gracefulRestart;
        private Boolean gracefulShutdown;
        private Boolean installRoute;
        private String localAs;
        private GetLogicalRouterVrfBgpMed med;
        private List<GetLogicalRouterVrfBgpPeerGroup> peerGroups;
        private GetLogicalRouterVrfBgpPolicy policy;
        private List<GetLogicalRouterVrfBgpRedistRule> redistRules;
        private GetLogicalRouterVrfBgpRedistributionProfile redistributionProfile;
        private Boolean rejectDefaultRoute;
        private String routerId;
        public Builder() {}
        public Builder(GetLogicalRouterVrfBgp defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.advertiseNetwork = defaults.advertiseNetwork;
    	      this.aggregate = defaults.aggregate;
    	      this.aggregateRoutes = defaults.aggregateRoutes;
    	      this.allowRedistDefaultRoute = defaults.allowRedistDefaultRoute;
    	      this.alwaysAdvertiseNetworkRoute = defaults.alwaysAdvertiseNetworkRoute;
    	      this.asFormat = defaults.asFormat;
    	      this.confederationMemberAs = defaults.confederationMemberAs;
    	      this.defaultLocalPreference = defaults.defaultLocalPreference;
    	      this.ecmpMultiAs = defaults.ecmpMultiAs;
    	      this.enable = defaults.enable;
    	      this.enforceFirstAs = defaults.enforceFirstAs;
    	      this.fastExternalFailover = defaults.fastExternalFailover;
    	      this.globalBfd = defaults.globalBfd;
    	      this.gracefulRestart = defaults.gracefulRestart;
    	      this.gracefulShutdown = defaults.gracefulShutdown;
    	      this.installRoute = defaults.installRoute;
    	      this.localAs = defaults.localAs;
    	      this.med = defaults.med;
    	      this.peerGroups = defaults.peerGroups;
    	      this.policy = defaults.policy;
    	      this.redistRules = defaults.redistRules;
    	      this.redistributionProfile = defaults.redistributionProfile;
    	      this.rejectDefaultRoute = defaults.rejectDefaultRoute;
    	      this.routerId = defaults.routerId;
        }

        @CustomType.Setter
        public Builder advertiseNetwork(GetLogicalRouterVrfBgpAdvertiseNetwork advertiseNetwork) {
            if (advertiseNetwork == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "advertiseNetwork");
            }
            this.advertiseNetwork = advertiseNetwork;
            return this;
        }
        @CustomType.Setter
        public Builder aggregate(GetLogicalRouterVrfBgpAggregate aggregate) {
            if (aggregate == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "aggregate");
            }
            this.aggregate = aggregate;
            return this;
        }
        @CustomType.Setter
        public Builder aggregateRoutes(List<GetLogicalRouterVrfBgpAggregateRoute> aggregateRoutes) {
            if (aggregateRoutes == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "aggregateRoutes");
            }
            this.aggregateRoutes = aggregateRoutes;
            return this;
        }
        public Builder aggregateRoutes(GetLogicalRouterVrfBgpAggregateRoute... aggregateRoutes) {
            return aggregateRoutes(List.of(aggregateRoutes));
        }
        @CustomType.Setter
        public Builder allowRedistDefaultRoute(Boolean allowRedistDefaultRoute) {
            if (allowRedistDefaultRoute == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "allowRedistDefaultRoute");
            }
            this.allowRedistDefaultRoute = allowRedistDefaultRoute;
            return this;
        }
        @CustomType.Setter
        public Builder alwaysAdvertiseNetworkRoute(Boolean alwaysAdvertiseNetworkRoute) {
            if (alwaysAdvertiseNetworkRoute == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "alwaysAdvertiseNetworkRoute");
            }
            this.alwaysAdvertiseNetworkRoute = alwaysAdvertiseNetworkRoute;
            return this;
        }
        @CustomType.Setter
        public Builder asFormat(String asFormat) {
            if (asFormat == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "asFormat");
            }
            this.asFormat = asFormat;
            return this;
        }
        @CustomType.Setter
        public Builder confederationMemberAs(String confederationMemberAs) {
            if (confederationMemberAs == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "confederationMemberAs");
            }
            this.confederationMemberAs = confederationMemberAs;
            return this;
        }
        @CustomType.Setter
        public Builder defaultLocalPreference(Integer defaultLocalPreference) {
            if (defaultLocalPreference == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "defaultLocalPreference");
            }
            this.defaultLocalPreference = defaultLocalPreference;
            return this;
        }
        @CustomType.Setter
        public Builder ecmpMultiAs(Boolean ecmpMultiAs) {
            if (ecmpMultiAs == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "ecmpMultiAs");
            }
            this.ecmpMultiAs = ecmpMultiAs;
            return this;
        }
        @CustomType.Setter
        public Builder enable(Boolean enable) {
            if (enable == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "enable");
            }
            this.enable = enable;
            return this;
        }
        @CustomType.Setter
        public Builder enforceFirstAs(Boolean enforceFirstAs) {
            if (enforceFirstAs == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "enforceFirstAs");
            }
            this.enforceFirstAs = enforceFirstAs;
            return this;
        }
        @CustomType.Setter
        public Builder fastExternalFailover(Boolean fastExternalFailover) {
            if (fastExternalFailover == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "fastExternalFailover");
            }
            this.fastExternalFailover = fastExternalFailover;
            return this;
        }
        @CustomType.Setter
        public Builder globalBfd(GetLogicalRouterVrfBgpGlobalBfd globalBfd) {
            if (globalBfd == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "globalBfd");
            }
            this.globalBfd = globalBfd;
            return this;
        }
        @CustomType.Setter
        public Builder gracefulRestart(GetLogicalRouterVrfBgpGracefulRestart gracefulRestart) {
            if (gracefulRestart == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "gracefulRestart");
            }
            this.gracefulRestart = gracefulRestart;
            return this;
        }
        @CustomType.Setter
        public Builder gracefulShutdown(Boolean gracefulShutdown) {
            if (gracefulShutdown == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "gracefulShutdown");
            }
            this.gracefulShutdown = gracefulShutdown;
            return this;
        }
        @CustomType.Setter
        public Builder installRoute(Boolean installRoute) {
            if (installRoute == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "installRoute");
            }
            this.installRoute = installRoute;
            return this;
        }
        @CustomType.Setter
        public Builder localAs(String localAs) {
            if (localAs == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "localAs");
            }
            this.localAs = localAs;
            return this;
        }
        @CustomType.Setter
        public Builder med(GetLogicalRouterVrfBgpMed med) {
            if (med == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "med");
            }
            this.med = med;
            return this;
        }
        @CustomType.Setter
        public Builder peerGroups(List<GetLogicalRouterVrfBgpPeerGroup> peerGroups) {
            if (peerGroups == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "peerGroups");
            }
            this.peerGroups = peerGroups;
            return this;
        }
        public Builder peerGroups(GetLogicalRouterVrfBgpPeerGroup... peerGroups) {
            return peerGroups(List.of(peerGroups));
        }
        @CustomType.Setter
        public Builder policy(GetLogicalRouterVrfBgpPolicy policy) {
            if (policy == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "policy");
            }
            this.policy = policy;
            return this;
        }
        @CustomType.Setter
        public Builder redistRules(List<GetLogicalRouterVrfBgpRedistRule> redistRules) {
            if (redistRules == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "redistRules");
            }
            this.redistRules = redistRules;
            return this;
        }
        public Builder redistRules(GetLogicalRouterVrfBgpRedistRule... redistRules) {
            return redistRules(List.of(redistRules));
        }
        @CustomType.Setter
        public Builder redistributionProfile(GetLogicalRouterVrfBgpRedistributionProfile redistributionProfile) {
            if (redistributionProfile == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "redistributionProfile");
            }
            this.redistributionProfile = redistributionProfile;
            return this;
        }
        @CustomType.Setter
        public Builder rejectDefaultRoute(Boolean rejectDefaultRoute) {
            if (rejectDefaultRoute == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "rejectDefaultRoute");
            }
            this.rejectDefaultRoute = rejectDefaultRoute;
            return this;
        }
        @CustomType.Setter
        public Builder routerId(String routerId) {
            if (routerId == null) {
              throw new MissingRequiredPropertyException("GetLogicalRouterVrfBgp", "routerId");
            }
            this.routerId = routerId;
            return this;
        }
        public GetLogicalRouterVrfBgp build() {
            final var _resultValue = new GetLogicalRouterVrfBgp();
            _resultValue.advertiseNetwork = advertiseNetwork;
            _resultValue.aggregate = aggregate;
            _resultValue.aggregateRoutes = aggregateRoutes;
            _resultValue.allowRedistDefaultRoute = allowRedistDefaultRoute;
            _resultValue.alwaysAdvertiseNetworkRoute = alwaysAdvertiseNetworkRoute;
            _resultValue.asFormat = asFormat;
            _resultValue.confederationMemberAs = confederationMemberAs;
            _resultValue.defaultLocalPreference = defaultLocalPreference;
            _resultValue.ecmpMultiAs = ecmpMultiAs;
            _resultValue.enable = enable;
            _resultValue.enforceFirstAs = enforceFirstAs;
            _resultValue.fastExternalFailover = fastExternalFailover;
            _resultValue.globalBfd = globalBfd;
            _resultValue.gracefulRestart = gracefulRestart;
            _resultValue.gracefulShutdown = gracefulShutdown;
            _resultValue.installRoute = installRoute;
            _resultValue.localAs = localAs;
            _resultValue.med = med;
            _resultValue.peerGroups = peerGroups;
            _resultValue.policy = policy;
            _resultValue.redistRules = redistRules;
            _resultValue.redistributionProfile = redistributionProfile;
            _resultValue.rejectDefaultRoute = rejectDefaultRoute;
            _resultValue.routerId = routerId;
            return _resultValue;
        }
    }
}
