// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetRouteCommunityListListDataTypeExtended;
import com.pulumi.scm.outputs.GetRouteCommunityListListDataTypeLarge;
import com.pulumi.scm.outputs.GetRouteCommunityListListDataTypeRegular;
import java.util.Objects;

@CustomType
public final class GetRouteCommunityListListDataType {
    /**
     * @return Extended
     * &gt; ℹ️ **Note:** You must specify exactly one of `extended`, `large`, and `regular`.
     * 
     */
    private GetRouteCommunityListListDataTypeExtended extended;
    /**
     * @return Large
     * &gt; ℹ️ **Note:** You must specify exactly one of `extended`, `large`, and `regular`.
     * 
     */
    private GetRouteCommunityListListDataTypeLarge large;
    /**
     * @return Regular
     * &gt; ℹ️ **Note:** You must specify exactly one of `extended`, `large`, and `regular`.
     * 
     */
    private GetRouteCommunityListListDataTypeRegular regular;

    private GetRouteCommunityListListDataType() {}
    /**
     * @return Extended
     * &gt; ℹ️ **Note:** You must specify exactly one of `extended`, `large`, and `regular`.
     * 
     */
    public GetRouteCommunityListListDataTypeExtended extended() {
        return this.extended;
    }
    /**
     * @return Large
     * &gt; ℹ️ **Note:** You must specify exactly one of `extended`, `large`, and `regular`.
     * 
     */
    public GetRouteCommunityListListDataTypeLarge large() {
        return this.large;
    }
    /**
     * @return Regular
     * &gt; ℹ️ **Note:** You must specify exactly one of `extended`, `large`, and `regular`.
     * 
     */
    public GetRouteCommunityListListDataTypeRegular regular() {
        return this.regular;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRouteCommunityListListDataType defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetRouteCommunityListListDataTypeExtended extended;
        private GetRouteCommunityListListDataTypeLarge large;
        private GetRouteCommunityListListDataTypeRegular regular;
        public Builder() {}
        public Builder(GetRouteCommunityListListDataType defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.extended = defaults.extended;
    	      this.large = defaults.large;
    	      this.regular = defaults.regular;
        }

        @CustomType.Setter
        public Builder extended(GetRouteCommunityListListDataTypeExtended extended) {
            if (extended == null) {
              throw new MissingRequiredPropertyException("GetRouteCommunityListListDataType", "extended");
            }
            this.extended = extended;
            return this;
        }
        @CustomType.Setter
        public Builder large(GetRouteCommunityListListDataTypeLarge large) {
            if (large == null) {
              throw new MissingRequiredPropertyException("GetRouteCommunityListListDataType", "large");
            }
            this.large = large;
            return this;
        }
        @CustomType.Setter
        public Builder regular(GetRouteCommunityListListDataTypeRegular regular) {
            if (regular == null) {
              throw new MissingRequiredPropertyException("GetRouteCommunityListListDataType", "regular");
            }
            this.regular = regular;
            return this;
        }
        public GetRouteCommunityListListDataType build() {
            final var _resultValue = new GetRouteCommunityListListDataType();
            _resultValue.extended = extended;
            _resultValue.large = large;
            _resultValue.regular = regular;
            return _resultValue;
        }
    }
}
