// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetRoutePathAccessListAspathEntry;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetRoutePathAccessListResult {
    private List<GetRoutePathAccessListAspathEntry> aspathEntries;
    private String description;
    /**
     * @return The device in which the resource is defined
     * 
     */
    private String device;
    private String folder;
    /**
     * @return UUID of the resource
     * 
     */
    private String id;
    private String name;
    private String snippet;
    private String tfid;

    private GetRoutePathAccessListResult() {}
    public List<GetRoutePathAccessListAspathEntry> aspathEntries() {
        return this.aspathEntries;
    }
    public String description() {
        return this.description;
    }
    /**
     * @return The device in which the resource is defined
     * 
     */
    public String device() {
        return this.device;
    }
    public String folder() {
        return this.folder;
    }
    /**
     * @return UUID of the resource
     * 
     */
    public String id() {
        return this.id;
    }
    public String name() {
        return this.name;
    }
    public String snippet() {
        return this.snippet;
    }
    public String tfid() {
        return this.tfid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRoutePathAccessListResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetRoutePathAccessListAspathEntry> aspathEntries;
        private String description;
        private String device;
        private String folder;
        private String id;
        private String name;
        private String snippet;
        private String tfid;
        public Builder() {}
        public Builder(GetRoutePathAccessListResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.aspathEntries = defaults.aspathEntries;
    	      this.description = defaults.description;
    	      this.device = defaults.device;
    	      this.folder = defaults.folder;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.snippet = defaults.snippet;
    	      this.tfid = defaults.tfid;
        }

        @CustomType.Setter
        public Builder aspathEntries(List<GetRoutePathAccessListAspathEntry> aspathEntries) {
            if (aspathEntries == null) {
              throw new MissingRequiredPropertyException("GetRoutePathAccessListResult", "aspathEntries");
            }
            this.aspathEntries = aspathEntries;
            return this;
        }
        public Builder aspathEntries(GetRoutePathAccessListAspathEntry... aspathEntries) {
            return aspathEntries(List.of(aspathEntries));
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetRoutePathAccessListResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder device(String device) {
            if (device == null) {
              throw new MissingRequiredPropertyException("GetRoutePathAccessListResult", "device");
            }
            this.device = device;
            return this;
        }
        @CustomType.Setter
        public Builder folder(String folder) {
            if (folder == null) {
              throw new MissingRequiredPropertyException("GetRoutePathAccessListResult", "folder");
            }
            this.folder = folder;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetRoutePathAccessListResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetRoutePathAccessListResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder snippet(String snippet) {
            if (snippet == null) {
              throw new MissingRequiredPropertyException("GetRoutePathAccessListResult", "snippet");
            }
            this.snippet = snippet;
            return this;
        }
        @CustomType.Setter
        public Builder tfid(String tfid) {
            if (tfid == null) {
              throw new MissingRequiredPropertyException("GetRoutePathAccessListResult", "tfid");
            }
            this.tfid = tfid;
            return this;
        }
        public GetRoutePathAccessListResult build() {
            final var _resultValue = new GetRoutePathAccessListResult();
            _resultValue.aspathEntries = aspathEntries;
            _resultValue.description = description;
            _resultValue.device = device;
            _resultValue.folder = folder;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.snippet = snippet;
            _resultValue.tfid = tfid;
            return _resultValue;
        }
    }
}
