// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetTacacsServerProfileListDataServer;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetTacacsServerProfileListData {
    /**
     * @return The device in which the resource is defined
     * 
     */
    private String device;
    /**
     * @return The folder in which the resource is defined
     * 
     */
    private String folder;
    /**
     * @return The UUID of the TACACS+ server profile
     * 
     */
    private String id;
    /**
     * @return The name of the TACACS+ server profile
     * 
     */
    private String name;
    /**
     * @return The TACACS+ authentication protocol
     * 
     */
    private String protocol;
    /**
     * @return The TACACS+ server configuration
     * 
     */
    private List<GetTacacsServerProfileListDataServer> servers;
    /**
     * @return The snippet in which the resource is defined
     * 
     */
    private String snippet;
    private String tfid;
    /**
     * @return The TACACS+ timeout (seconds)
     * 
     */
    private Integer timeout;
    /**
     * @return Use a single TACACS+ connection?
     * 
     */
    private Boolean useSingleConnection;

    private GetTacacsServerProfileListData() {}
    /**
     * @return The device in which the resource is defined
     * 
     */
    public String device() {
        return this.device;
    }
    /**
     * @return The folder in which the resource is defined
     * 
     */
    public String folder() {
        return this.folder;
    }
    /**
     * @return The UUID of the TACACS+ server profile
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The name of the TACACS+ server profile
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The TACACS+ authentication protocol
     * 
     */
    public String protocol() {
        return this.protocol;
    }
    /**
     * @return The TACACS+ server configuration
     * 
     */
    public List<GetTacacsServerProfileListDataServer> servers() {
        return this.servers;
    }
    /**
     * @return The snippet in which the resource is defined
     * 
     */
    public String snippet() {
        return this.snippet;
    }
    public String tfid() {
        return this.tfid;
    }
    /**
     * @return The TACACS+ timeout (seconds)
     * 
     */
    public Integer timeout() {
        return this.timeout;
    }
    /**
     * @return Use a single TACACS+ connection?
     * 
     */
    public Boolean useSingleConnection() {
        return this.useSingleConnection;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTacacsServerProfileListData defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String device;
        private String folder;
        private String id;
        private String name;
        private String protocol;
        private List<GetTacacsServerProfileListDataServer> servers;
        private String snippet;
        private String tfid;
        private Integer timeout;
        private Boolean useSingleConnection;
        public Builder() {}
        public Builder(GetTacacsServerProfileListData defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.device = defaults.device;
    	      this.folder = defaults.folder;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.protocol = defaults.protocol;
    	      this.servers = defaults.servers;
    	      this.snippet = defaults.snippet;
    	      this.tfid = defaults.tfid;
    	      this.timeout = defaults.timeout;
    	      this.useSingleConnection = defaults.useSingleConnection;
        }

        @CustomType.Setter
        public Builder device(String device) {
            if (device == null) {
              throw new MissingRequiredPropertyException("GetTacacsServerProfileListData", "device");
            }
            this.device = device;
            return this;
        }
        @CustomType.Setter
        public Builder folder(String folder) {
            if (folder == null) {
              throw new MissingRequiredPropertyException("GetTacacsServerProfileListData", "folder");
            }
            this.folder = folder;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetTacacsServerProfileListData", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetTacacsServerProfileListData", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder protocol(String protocol) {
            if (protocol == null) {
              throw new MissingRequiredPropertyException("GetTacacsServerProfileListData", "protocol");
            }
            this.protocol = protocol;
            return this;
        }
        @CustomType.Setter
        public Builder servers(List<GetTacacsServerProfileListDataServer> servers) {
            if (servers == null) {
              throw new MissingRequiredPropertyException("GetTacacsServerProfileListData", "servers");
            }
            this.servers = servers;
            return this;
        }
        public Builder servers(GetTacacsServerProfileListDataServer... servers) {
            return servers(List.of(servers));
        }
        @CustomType.Setter
        public Builder snippet(String snippet) {
            if (snippet == null) {
              throw new MissingRequiredPropertyException("GetTacacsServerProfileListData", "snippet");
            }
            this.snippet = snippet;
            return this;
        }
        @CustomType.Setter
        public Builder tfid(String tfid) {
            if (tfid == null) {
              throw new MissingRequiredPropertyException("GetTacacsServerProfileListData", "tfid");
            }
            this.tfid = tfid;
            return this;
        }
        @CustomType.Setter
        public Builder timeout(Integer timeout) {
            if (timeout == null) {
              throw new MissingRequiredPropertyException("GetTacacsServerProfileListData", "timeout");
            }
            this.timeout = timeout;
            return this;
        }
        @CustomType.Setter
        public Builder useSingleConnection(Boolean useSingleConnection) {
            if (useSingleConnection == null) {
              throw new MissingRequiredPropertyException("GetTacacsServerProfileListData", "useSingleConnection");
            }
            this.useSingleConnection = useSingleConnection;
            return this;
        }
        public GetTacacsServerProfileListData build() {
            final var _resultValue = new GetTacacsServerProfileListData();
            _resultValue.device = device;
            _resultValue.folder = folder;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.protocol = protocol;
            _resultValue.servers = servers;
            _resultValue.snippet = snippet;
            _resultValue.tfid = tfid;
            _resultValue.timeout = timeout;
            _resultValue.useSingleConnection = useSingleConnection;
            return _resultValue;
        }
    }
}
