// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.outputs.GetZoneProtectionProfileFloodUdpRed;
import java.lang.Boolean;
import java.util.Objects;

@CustomType
public final class GetZoneProtectionProfileFloodUdp {
    /**
     * @return Enable protection against UDP floods?
     * 
     */
    private Boolean enable;
    /**
     * @return Red
     * 
     */
    private GetZoneProtectionProfileFloodUdpRed red;

    private GetZoneProtectionProfileFloodUdp() {}
    /**
     * @return Enable protection against UDP floods?
     * 
     */
    public Boolean enable() {
        return this.enable;
    }
    /**
     * @return Red
     * 
     */
    public GetZoneProtectionProfileFloodUdpRed red() {
        return this.red;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetZoneProtectionProfileFloodUdp defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean enable;
        private GetZoneProtectionProfileFloodUdpRed red;
        public Builder() {}
        public Builder(GetZoneProtectionProfileFloodUdp defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enable = defaults.enable;
    	      this.red = defaults.red;
        }

        @CustomType.Setter
        public Builder enable(Boolean enable) {
            if (enable == null) {
              throw new MissingRequiredPropertyException("GetZoneProtectionProfileFloodUdp", "enable");
            }
            this.enable = enable;
            return this;
        }
        @CustomType.Setter
        public Builder red(GetZoneProtectionProfileFloodUdpRed red) {
            if (red == null) {
              throw new MissingRequiredPropertyException("GetZoneProtectionProfileFloodUdp", "red");
            }
            this.red = red;
            return this;
        }
        public GetZoneProtectionProfileFloodUdp build() {
            final var _resultValue = new GetZoneProtectionProfileFloodUdp();
            _resultValue.enable = enable;
            _resultValue.red = red;
            return _resultValue;
        }
    }
}
