// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.util.Objects;

@CustomType
public final class GetZoneProtectionProfileIpv6FilterExtHdr {
    /**
     * @return Discard IPv6 packets that contain the Destination Options extension, which contains options intended only for the destination of the packet.
     * 
     */
    private Boolean destOptionHdr;
    /**
     * @return Discard IPv6 packets that contain the Hop-by-Hop Options extension header.
     * 
     */
    private Boolean hopByHopHdr;
    /**
     * @return Discard IPv6 packets that contain the Routing extension header, which directs packets to one or more intermediate nodes on its way to its destination.
     * 
     */
    private Boolean routingHdr;

    private GetZoneProtectionProfileIpv6FilterExtHdr() {}
    /**
     * @return Discard IPv6 packets that contain the Destination Options extension, which contains options intended only for the destination of the packet.
     * 
     */
    public Boolean destOptionHdr() {
        return this.destOptionHdr;
    }
    /**
     * @return Discard IPv6 packets that contain the Hop-by-Hop Options extension header.
     * 
     */
    public Boolean hopByHopHdr() {
        return this.hopByHopHdr;
    }
    /**
     * @return Discard IPv6 packets that contain the Routing extension header, which directs packets to one or more intermediate nodes on its way to its destination.
     * 
     */
    public Boolean routingHdr() {
        return this.routingHdr;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetZoneProtectionProfileIpv6FilterExtHdr defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean destOptionHdr;
        private Boolean hopByHopHdr;
        private Boolean routingHdr;
        public Builder() {}
        public Builder(GetZoneProtectionProfileIpv6FilterExtHdr defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.destOptionHdr = defaults.destOptionHdr;
    	      this.hopByHopHdr = defaults.hopByHopHdr;
    	      this.routingHdr = defaults.routingHdr;
        }

        @CustomType.Setter
        public Builder destOptionHdr(Boolean destOptionHdr) {
            if (destOptionHdr == null) {
              throw new MissingRequiredPropertyException("GetZoneProtectionProfileIpv6FilterExtHdr", "destOptionHdr");
            }
            this.destOptionHdr = destOptionHdr;
            return this;
        }
        @CustomType.Setter
        public Builder hopByHopHdr(Boolean hopByHopHdr) {
            if (hopByHopHdr == null) {
              throw new MissingRequiredPropertyException("GetZoneProtectionProfileIpv6FilterExtHdr", "hopByHopHdr");
            }
            this.hopByHopHdr = hopByHopHdr;
            return this;
        }
        @CustomType.Setter
        public Builder routingHdr(Boolean routingHdr) {
            if (routingHdr == null) {
              throw new MissingRequiredPropertyException("GetZoneProtectionProfileIpv6FilterExtHdr", "routingHdr");
            }
            this.routingHdr = routingHdr;
            return this;
        }
        public GetZoneProtectionProfileIpv6FilterExtHdr build() {
            final var _resultValue = new GetZoneProtectionProfileIpv6FilterExtHdr();
            _resultValue.destOptionHdr = destOptionHdr;
            _resultValue.hopByHopHdr = hopByHopHdr;
            _resultValue.routingHdr = routingHdr;
            return _resultValue;
        }
    }
}
