// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.scm.outputs.SdwanErrorCorrectionProfileModeForwardErrorCorrection;
import com.pulumi.scm.outputs.SdwanErrorCorrectionProfileModePacketDuplication;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SdwanErrorCorrectionProfileMode {
    /**
     * @return Forward error correction
     * &gt; ℹ️ **Note:** You must specify exactly one of `forwardErrorCorrection` and `packetDuplication`.
     * 
     */
    private @Nullable SdwanErrorCorrectionProfileModeForwardErrorCorrection forwardErrorCorrection;
    /**
     * @return Packet duplication
     * &gt; ℹ️ **Note:** You must specify exactly one of `forwardErrorCorrection` and `packetDuplication`.
     * 
     */
    private @Nullable SdwanErrorCorrectionProfileModePacketDuplication packetDuplication;

    private SdwanErrorCorrectionProfileMode() {}
    /**
     * @return Forward error correction
     * &gt; ℹ️ **Note:** You must specify exactly one of `forwardErrorCorrection` and `packetDuplication`.
     * 
     */
    public Optional<SdwanErrorCorrectionProfileModeForwardErrorCorrection> forwardErrorCorrection() {
        return Optional.ofNullable(this.forwardErrorCorrection);
    }
    /**
     * @return Packet duplication
     * &gt; ℹ️ **Note:** You must specify exactly one of `forwardErrorCorrection` and `packetDuplication`.
     * 
     */
    public Optional<SdwanErrorCorrectionProfileModePacketDuplication> packetDuplication() {
        return Optional.ofNullable(this.packetDuplication);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SdwanErrorCorrectionProfileMode defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable SdwanErrorCorrectionProfileModeForwardErrorCorrection forwardErrorCorrection;
        private @Nullable SdwanErrorCorrectionProfileModePacketDuplication packetDuplication;
        public Builder() {}
        public Builder(SdwanErrorCorrectionProfileMode defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.forwardErrorCorrection = defaults.forwardErrorCorrection;
    	      this.packetDuplication = defaults.packetDuplication;
        }

        @CustomType.Setter
        public Builder forwardErrorCorrection(@Nullable SdwanErrorCorrectionProfileModeForwardErrorCorrection forwardErrorCorrection) {

            this.forwardErrorCorrection = forwardErrorCorrection;
            return this;
        }
        @CustomType.Setter
        public Builder packetDuplication(@Nullable SdwanErrorCorrectionProfileModePacketDuplication packetDuplication) {

            this.packetDuplication = packetDuplication;
            return this;
        }
        public SdwanErrorCorrectionProfileMode build() {
            final var _resultValue = new SdwanErrorCorrectionProfileMode();
            _resultValue.forwardErrorCorrection = forwardErrorCorrection;
            _resultValue.packetDuplication = packetDuplication;
            return _resultValue;
        }
    }
}
