// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm
{
    /// <summary>
    /// AppOverrideRule resource
    /// </summary>
    [ScmResourceType("scm:index/appOverrideRule:AppOverrideRule")]
    public partial class AppOverrideRule : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Application
        /// </summary>
        [Output("application")]
        public Output<string> Application { get; private set; } = null!;

        /// <summary>
        /// Description
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Destination
        /// </summary>
        [Output("destinations")]
        public Output<ImmutableArray<string>> Destinations { get; private set; } = null!;

        /// <summary>
        /// The device in which the resource is defined
        /// </summary>
        [Output("device")]
        public Output<string?> Device { get; private set; } = null!;

        /// <summary>
        /// Disabled
        /// </summary>
        [Output("disabled")]
        public Output<bool> Disabled { get; private set; } = null!;

        /// <summary>
        /// The folder in which the resource is defined
        /// </summary>
        [Output("folder")]
        public Output<string?> Folder { get; private set; } = null!;

        /// <summary>
        /// From
        /// </summary>
        [Output("froms")]
        public Output<ImmutableArray<string>> Froms { get; private set; } = null!;

        /// <summary>
        /// Group tag
        /// </summary>
        [Output("groupTag")]
        public Output<string?> GroupTag { get; private set; } = null!;

        /// <summary>
        /// Name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Negate destination
        /// </summary>
        [Output("negateDestination")]
        public Output<bool> NegateDestination { get; private set; } = null!;

        /// <summary>
        /// Negate source
        /// </summary>
        [Output("negateSource")]
        public Output<bool> NegateSource { get; private set; } = null!;

        /// <summary>
        /// Port
        /// </summary>
        [Output("port")]
        public Output<int> Port { get; private set; } = null!;

        /// <summary>
        /// Protocol
        /// </summary>
        [Output("protocol")]
        public Output<string> Protocol { get; private set; } = null!;

        /// <summary>
        /// The snippet in which the resource is defined
        /// </summary>
        [Output("snippet")]
        public Output<string?> Snippet { get; private set; } = null!;

        /// <summary>
        /// Source
        /// </summary>
        [Output("sources")]
        public Output<ImmutableArray<string>> Sources { get; private set; } = null!;

        /// <summary>
        /// Tag
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        [Output("tfid")]
        public Output<string> Tfid { get; private set; } = null!;

        /// <summary>
        /// To
        /// </summary>
        [Output("tos")]
        public Output<ImmutableArray<string>> Tos { get; private set; } = null!;


        /// <summary>
        /// Create a AppOverrideRule resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AppOverrideRule(string name, AppOverrideRuleArgs args, CustomResourceOptions? options = null)
            : base("scm:index/appOverrideRule:AppOverrideRule", name, args ?? new AppOverrideRuleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AppOverrideRule(string name, Input<string> id, AppOverrideRuleState? state = null, CustomResourceOptions? options = null)
            : base("scm:index/appOverrideRule:AppOverrideRule", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AppOverrideRule resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AppOverrideRule Get(string name, Input<string> id, AppOverrideRuleState? state = null, CustomResourceOptions? options = null)
        {
            return new AppOverrideRule(name, id, state, options);
        }
    }

    public sealed class AppOverrideRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Application
        /// </summary>
        [Input("application", required: true)]
        public Input<string> Application { get; set; } = null!;

        /// <summary>
        /// Description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("destinations", required: true)]
        private InputList<string>? _destinations;

        /// <summary>
        /// Destination
        /// </summary>
        public InputList<string> Destinations
        {
            get => _destinations ?? (_destinations = new InputList<string>());
            set => _destinations = value;
        }

        /// <summary>
        /// The device in which the resource is defined
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        /// <summary>
        /// Disabled
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        /// <summary>
        /// The folder in which the resource is defined
        /// </summary>
        [Input("folder")]
        public Input<string>? Folder { get; set; }

        [Input("froms", required: true)]
        private InputList<string>? _froms;

        /// <summary>
        /// From
        /// </summary>
        public InputList<string> Froms
        {
            get => _froms ?? (_froms = new InputList<string>());
            set => _froms = value;
        }

        /// <summary>
        /// Group tag
        /// </summary>
        [Input("groupTag")]
        public Input<string>? GroupTag { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Negate destination
        /// </summary>
        [Input("negateDestination")]
        public Input<bool>? NegateDestination { get; set; }

        /// <summary>
        /// Negate source
        /// </summary>
        [Input("negateSource")]
        public Input<bool>? NegateSource { get; set; }

        /// <summary>
        /// Port
        /// </summary>
        [Input("port", required: true)]
        public Input<int> Port { get; set; } = null!;

        /// <summary>
        /// Protocol
        /// </summary>
        [Input("protocol", required: true)]
        public Input<string> Protocol { get; set; } = null!;

        /// <summary>
        /// The snippet in which the resource is defined
        /// </summary>
        [Input("snippet")]
        public Input<string>? Snippet { get; set; }

        [Input("sources", required: true)]
        private InputList<string>? _sources;

        /// <summary>
        /// Source
        /// </summary>
        public InputList<string> Sources
        {
            get => _sources ?? (_sources = new InputList<string>());
            set => _sources = value;
        }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Tag
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("tos", required: true)]
        private InputList<string>? _tos;

        /// <summary>
        /// To
        /// </summary>
        public InputList<string> Tos
        {
            get => _tos ?? (_tos = new InputList<string>());
            set => _tos = value;
        }

        public AppOverrideRuleArgs()
        {
        }
        public static new AppOverrideRuleArgs Empty => new AppOverrideRuleArgs();
    }

    public sealed class AppOverrideRuleState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Application
        /// </summary>
        [Input("application")]
        public Input<string>? Application { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("destinations")]
        private InputList<string>? _destinations;

        /// <summary>
        /// Destination
        /// </summary>
        public InputList<string> Destinations
        {
            get => _destinations ?? (_destinations = new InputList<string>());
            set => _destinations = value;
        }

        /// <summary>
        /// The device in which the resource is defined
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        /// <summary>
        /// Disabled
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        /// <summary>
        /// The folder in which the resource is defined
        /// </summary>
        [Input("folder")]
        public Input<string>? Folder { get; set; }

        [Input("froms")]
        private InputList<string>? _froms;

        /// <summary>
        /// From
        /// </summary>
        public InputList<string> Froms
        {
            get => _froms ?? (_froms = new InputList<string>());
            set => _froms = value;
        }

        /// <summary>
        /// Group tag
        /// </summary>
        [Input("groupTag")]
        public Input<string>? GroupTag { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Negate destination
        /// </summary>
        [Input("negateDestination")]
        public Input<bool>? NegateDestination { get; set; }

        /// <summary>
        /// Negate source
        /// </summary>
        [Input("negateSource")]
        public Input<bool>? NegateSource { get; set; }

        /// <summary>
        /// Port
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// Protocol
        /// </summary>
        [Input("protocol")]
        public Input<string>? Protocol { get; set; }

        /// <summary>
        /// The snippet in which the resource is defined
        /// </summary>
        [Input("snippet")]
        public Input<string>? Snippet { get; set; }

        [Input("sources")]
        private InputList<string>? _sources;

        /// <summary>
        /// Source
        /// </summary>
        public InputList<string> Sources
        {
            get => _sources ?? (_sources = new InputList<string>());
            set => _sources = value;
        }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Tag
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("tfid")]
        public Input<string>? Tfid { get; set; }

        [Input("tos")]
        private InputList<string>? _tos;

        /// <summary>
        /// To
        /// </summary>
        public InputList<string> Tos
        {
            get => _tos ?? (_tos = new InputList<string>());
            set => _tos = value;
        }

        public AppOverrideRuleState()
        {
        }
        public static new AppOverrideRuleState Empty => new AppOverrideRuleState();
    }
}
