// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm
{
    public static class GetDnsProxy
    {
        /// <summary>
        /// DnsProxy data source
        /// </summary>
        public static Task<GetDnsProxyResult> InvokeAsync(GetDnsProxyArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDnsProxyResult>("scm:index/getDnsProxy:getDnsProxy", args ?? new GetDnsProxyArgs(), options.WithDefaults());

        /// <summary>
        /// DnsProxy data source
        /// </summary>
        public static Output<GetDnsProxyResult> Invoke(GetDnsProxyInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDnsProxyResult>("scm:index/getDnsProxy:getDnsProxy", args ?? new GetDnsProxyInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// DnsProxy data source
        /// </summary>
        public static Output<GetDnsProxyResult> Invoke(GetDnsProxyInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDnsProxyResult>("scm:index/getDnsProxy:getDnsProxy", args ?? new GetDnsProxyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDnsProxyArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The device in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        [Input("device")]
        public string? Device { get; set; }

        /// <summary>
        /// The folder in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        [Input("folder")]
        public string? Folder { get; set; }

        /// <summary>
        /// UUID of the resource
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// DNS proxy name
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The snippet in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        [Input("snippet")]
        public string? Snippet { get; set; }

        public GetDnsProxyArgs()
        {
        }
        public static new GetDnsProxyArgs Empty => new GetDnsProxyArgs();
    }

    public sealed class GetDnsProxyInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The device in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        /// <summary>
        /// The folder in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        [Input("folder")]
        public Input<string>? Folder { get; set; }

        /// <summary>
        /// UUID of the resource
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// DNS proxy name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The snippet in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        [Input("snippet")]
        public Input<string>? Snippet { get; set; }

        public GetDnsProxyInvokeArgs()
        {
        }
        public static new GetDnsProxyInvokeArgs Empty => new GetDnsProxyInvokeArgs();
    }


    [OutputType]
    public sealed class GetDnsProxyResult
    {
        /// <summary>
        /// Cache
        /// </summary>
        public readonly Outputs.GetDnsProxyCacheResult Cache;
        /// <summary>
        /// Default
        /// </summary>
        public readonly Outputs.GetDnsProxyDefaultResult Default;
        /// <summary>
        /// The device in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        public readonly string Device;
        /// <summary>
        /// DNS proxy rules
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDnsProxyDomainServerResult> DomainServers;
        /// <summary>
        /// Enable DNS proxy?
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// The folder in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        public readonly string Folder;
        /// <summary>
        /// UUID of the resource
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Interfaces on which to enable DNS proxy service
        /// </summary>
        public readonly ImmutableArray<string> Interfaces;
        /// <summary>
        /// DNS proxy name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The snippet in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        public readonly string Snippet;
        /// <summary>
        /// Static entries
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDnsProxyStaticEntryResult> StaticEntries;
        /// <summary>
        /// Tcp queries
        /// </summary>
        public readonly Outputs.GetDnsProxyTcpQueriesResult TcpQueries;
        public readonly string Tfid;
        /// <summary>
        /// Udp queries
        /// </summary>
        public readonly Outputs.GetDnsProxyUdpQueriesResult UdpQueries;

        [OutputConstructor]
        private GetDnsProxyResult(
            Outputs.GetDnsProxyCacheResult cache,

            Outputs.GetDnsProxyDefaultResult @default,

            string device,

            ImmutableArray<Outputs.GetDnsProxyDomainServerResult> domainServers,

            bool enabled,

            string folder,

            string id,

            ImmutableArray<string> interfaces,

            string name,

            string snippet,

            ImmutableArray<Outputs.GetDnsProxyStaticEntryResult> staticEntries,

            Outputs.GetDnsProxyTcpQueriesResult tcpQueries,

            string tfid,

            Outputs.GetDnsProxyUdpQueriesResult udpQueries)
        {
            Cache = cache;
            Default = @default;
            Device = device;
            DomainServers = domainServers;
            Enabled = enabled;
            Folder = folder;
            Id = id;
            Interfaces = interfaces;
            Name = name;
            Snippet = snippet;
            StaticEntries = staticEntries;
            TcpQueries = tcpQueries;
            Tfid = tfid;
            UdpQueries = udpQueries;
        }
    }
}
