// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm
{
    public static class GetSdwanErrorCorrectionProfile
    {
        /// <summary>
        /// SdwanErrorCorrectionProfile data source
        /// </summary>
        public static Task<GetSdwanErrorCorrectionProfileResult> InvokeAsync(GetSdwanErrorCorrectionProfileArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSdwanErrorCorrectionProfileResult>("scm:index/getSdwanErrorCorrectionProfile:getSdwanErrorCorrectionProfile", args ?? new GetSdwanErrorCorrectionProfileArgs(), options.WithDefaults());

        /// <summary>
        /// SdwanErrorCorrectionProfile data source
        /// </summary>
        public static Output<GetSdwanErrorCorrectionProfileResult> Invoke(GetSdwanErrorCorrectionProfileInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSdwanErrorCorrectionProfileResult>("scm:index/getSdwanErrorCorrectionProfile:getSdwanErrorCorrectionProfile", args ?? new GetSdwanErrorCorrectionProfileInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// SdwanErrorCorrectionProfile data source
        /// </summary>
        public static Output<GetSdwanErrorCorrectionProfileResult> Invoke(GetSdwanErrorCorrectionProfileInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSdwanErrorCorrectionProfileResult>("scm:index/getSdwanErrorCorrectionProfile:getSdwanErrorCorrectionProfile", args ?? new GetSdwanErrorCorrectionProfileInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSdwanErrorCorrectionProfileArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// UUID of the resource
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// Name
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetSdwanErrorCorrectionProfileArgs()
        {
        }
        public static new GetSdwanErrorCorrectionProfileArgs Empty => new GetSdwanErrorCorrectionProfileArgs();
    }

    public sealed class GetSdwanErrorCorrectionProfileInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// UUID of the resource
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetSdwanErrorCorrectionProfileInvokeArgs()
        {
        }
        public static new GetSdwanErrorCorrectionProfileInvokeArgs Empty => new GetSdwanErrorCorrectionProfileInvokeArgs();
    }


    [OutputType]
    public sealed class GetSdwanErrorCorrectionProfileResult
    {
        /// <summary>
        /// Activation threshold
        /// </summary>
        public readonly double ActivationThreshold;
        /// <summary>
        /// The device in which the resource is defined
        /// </summary>
        public readonly string Device;
        /// <summary>
        /// The folder in which the resource is defined
        /// </summary>
        public readonly string Folder;
        /// <summary>
        /// UUID of the resource
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Mode
        /// </summary>
        public readonly Outputs.GetSdwanErrorCorrectionProfileModeResult Mode;
        /// <summary>
        /// Name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The snippet in which the resource is defined
        /// </summary>
        public readonly string Snippet;
        public readonly string Tfid;

        [OutputConstructor]
        private GetSdwanErrorCorrectionProfileResult(
            double activationThreshold,

            string device,

            string folder,

            string id,

            Outputs.GetSdwanErrorCorrectionProfileModeResult mode,

            string name,

            string snippet,

            string tfid)
        {
            ActivationThreshold = activationThreshold;
            Device = device;
            Folder = folder;
            Id = id;
            Mode = mode;
            Name = name;
            Snippet = snippet;
            Tfid = tfid;
        }
    }
}
