// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scm

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-scm/sdk/go/scm/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ApplicationFilter data source
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-scm/sdk/go/scm"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			scmApplicationFilterDs, err := scm.LookupApplicationFilter(ctx, &scm.LookupApplicationFilterArgs{
//				Id: "52ee6475-a99c-42d7-be0a-e251c05e805b",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("applicationFiltersDataSourceResults", scmApplicationFilterDs)
//			return nil
//		})
//	}
//
// ```
func LookupApplicationFilter(ctx *pulumi.Context, args *LookupApplicationFilterArgs, opts ...pulumi.InvokeOption) (*LookupApplicationFilterResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupApplicationFilterResult
	err := ctx.Invoke("scm:index/getApplicationFilter:getApplicationFilter", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApplicationFilter.
type LookupApplicationFilterArgs struct {
	// UUID of the resource
	Id string `pulumi:"id"`
	// Alphanumeric string [ 0-9a-zA-Z._-]
	Name *string `pulumi:"name"`
}

// A collection of values returned by getApplicationFilter.
type LookupApplicationFilterResult struct {
	// Category
	Categories []string `pulumi:"categories"`
	// The device in which the resource is defined
	Device                  string   `pulumi:"device"`
	Evasive                 bool     `pulumi:"evasive"`
	ExcessiveBandwidthUse   bool     `pulumi:"excessiveBandwidthUse"`
	Excludes                []string `pulumi:"excludes"`
	Folder                  string   `pulumi:"folder"`
	HasKnownVulnerabilities bool     `pulumi:"hasKnownVulnerabilities"`
	// UUID of the resource
	Id     string `pulumi:"id"`
	IsSaas bool   `pulumi:"isSaas"`
	// Alphanumeric string [ 0-9a-zA-Z._-]
	Name               string                      `pulumi:"name"`
	NewAppid           bool                        `pulumi:"newAppid"`
	Pervasive          bool                        `pulumi:"pervasive"`
	ProneToMisuse      bool                        `pulumi:"proneToMisuse"`
	Risks              []int                       `pulumi:"risks"`
	SaasCertifications []string                    `pulumi:"saasCertifications"`
	SaasRisks          []string                    `pulumi:"saasRisks"`
	Snippet            string                      `pulumi:"snippet"`
	Subcategories      []string                    `pulumi:"subcategories"`
	Tagging            GetApplicationFilterTagging `pulumi:"tagging"`
	Technologies       []string                    `pulumi:"technologies"`
	Tfid               string                      `pulumi:"tfid"`
	TransfersFiles     bool                        `pulumi:"transfersFiles"`
	TunnelsOtherApps   bool                        `pulumi:"tunnelsOtherApps"`
	UsedByMalware      bool                        `pulumi:"usedByMalware"`
}

func LookupApplicationFilterOutput(ctx *pulumi.Context, args LookupApplicationFilterOutputArgs, opts ...pulumi.InvokeOption) LookupApplicationFilterResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupApplicationFilterResultOutput, error) {
			args := v.(LookupApplicationFilterArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("scm:index/getApplicationFilter:getApplicationFilter", args, LookupApplicationFilterResultOutput{}, options).(LookupApplicationFilterResultOutput), nil
		}).(LookupApplicationFilterResultOutput)
}

// A collection of arguments for invoking getApplicationFilter.
type LookupApplicationFilterOutputArgs struct {
	// UUID of the resource
	Id pulumi.StringInput `pulumi:"id"`
	// Alphanumeric string [ 0-9a-zA-Z._-]
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupApplicationFilterOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApplicationFilterArgs)(nil)).Elem()
}

// A collection of values returned by getApplicationFilter.
type LookupApplicationFilterResultOutput struct{ *pulumi.OutputState }

func (LookupApplicationFilterResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApplicationFilterResult)(nil)).Elem()
}

func (o LookupApplicationFilterResultOutput) ToLookupApplicationFilterResultOutput() LookupApplicationFilterResultOutput {
	return o
}

func (o LookupApplicationFilterResultOutput) ToLookupApplicationFilterResultOutputWithContext(ctx context.Context) LookupApplicationFilterResultOutput {
	return o
}

// Category
func (o LookupApplicationFilterResultOutput) Categories() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) []string { return v.Categories }).(pulumi.StringArrayOutput)
}

// The device in which the resource is defined
func (o LookupApplicationFilterResultOutput) Device() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) string { return v.Device }).(pulumi.StringOutput)
}

func (o LookupApplicationFilterResultOutput) Evasive() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) bool { return v.Evasive }).(pulumi.BoolOutput)
}

func (o LookupApplicationFilterResultOutput) ExcessiveBandwidthUse() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) bool { return v.ExcessiveBandwidthUse }).(pulumi.BoolOutput)
}

func (o LookupApplicationFilterResultOutput) Excludes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) []string { return v.Excludes }).(pulumi.StringArrayOutput)
}

func (o LookupApplicationFilterResultOutput) Folder() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) string { return v.Folder }).(pulumi.StringOutput)
}

func (o LookupApplicationFilterResultOutput) HasKnownVulnerabilities() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) bool { return v.HasKnownVulnerabilities }).(pulumi.BoolOutput)
}

// UUID of the resource
func (o LookupApplicationFilterResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupApplicationFilterResultOutput) IsSaas() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) bool { return v.IsSaas }).(pulumi.BoolOutput)
}

// Alphanumeric string [ 0-9a-zA-Z._-]
func (o LookupApplicationFilterResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupApplicationFilterResultOutput) NewAppid() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) bool { return v.NewAppid }).(pulumi.BoolOutput)
}

func (o LookupApplicationFilterResultOutput) Pervasive() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) bool { return v.Pervasive }).(pulumi.BoolOutput)
}

func (o LookupApplicationFilterResultOutput) ProneToMisuse() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) bool { return v.ProneToMisuse }).(pulumi.BoolOutput)
}

func (o LookupApplicationFilterResultOutput) Risks() pulumi.IntArrayOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) []int { return v.Risks }).(pulumi.IntArrayOutput)
}

func (o LookupApplicationFilterResultOutput) SaasCertifications() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) []string { return v.SaasCertifications }).(pulumi.StringArrayOutput)
}

func (o LookupApplicationFilterResultOutput) SaasRisks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) []string { return v.SaasRisks }).(pulumi.StringArrayOutput)
}

func (o LookupApplicationFilterResultOutput) Snippet() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) string { return v.Snippet }).(pulumi.StringOutput)
}

func (o LookupApplicationFilterResultOutput) Subcategories() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) []string { return v.Subcategories }).(pulumi.StringArrayOutput)
}

func (o LookupApplicationFilterResultOutput) Tagging() GetApplicationFilterTaggingOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) GetApplicationFilterTagging { return v.Tagging }).(GetApplicationFilterTaggingOutput)
}

func (o LookupApplicationFilterResultOutput) Technologies() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) []string { return v.Technologies }).(pulumi.StringArrayOutput)
}

func (o LookupApplicationFilterResultOutput) Tfid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) string { return v.Tfid }).(pulumi.StringOutput)
}

func (o LookupApplicationFilterResultOutput) TransfersFiles() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) bool { return v.TransfersFiles }).(pulumi.BoolOutput)
}

func (o LookupApplicationFilterResultOutput) TunnelsOtherApps() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) bool { return v.TunnelsOtherApps }).(pulumi.BoolOutput)
}

func (o LookupApplicationFilterResultOutput) UsedByMalware() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupApplicationFilterResult) bool { return v.UsedByMalware }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupApplicationFilterResultOutput{})
}
