// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scm

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-scm/sdk/go/scm/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves a listing of config items.
func GetBgpAuthProfileList(ctx *pulumi.Context, args *GetBgpAuthProfileListArgs, opts ...pulumi.InvokeOption) (*GetBgpAuthProfileListResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetBgpAuthProfileListResult
	err := ctx.Invoke("scm:index/getBgpAuthProfileList:getBgpAuthProfileList", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBgpAuthProfileList.
type GetBgpAuthProfileListArgs struct {
	// The device of the item.
	Device *string `pulumi:"device"`
	// The folder of the item. Default: Shared.
	Folder *string `pulumi:"folder"`
	// The max number of items to return. Default: 200.
	Limit *int `pulumi:"limit"`
	// The name of the item.
	Name *string `pulumi:"name"`
	// The offset of the first item to return.
	Offset *int `pulumi:"offset"`
	// The snippet of the item.
	Snippet *string `pulumi:"snippet"`
}

// A collection of values returned by getBgpAuthProfileList.
type GetBgpAuthProfileListResult struct {
	// The data.
	Datas []GetBgpAuthProfileListData `pulumi:"datas"`
	// The device of the item.
	Device *string `pulumi:"device"`
	// The folder of the item. Default: Shared.
	Folder *string `pulumi:"folder"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The max number of items to return. Default: 200.
	Limit *int `pulumi:"limit"`
	// The name of the item.
	Name *string `pulumi:"name"`
	// The offset of the first item to return.
	Offset *int `pulumi:"offset"`
	// The snippet of the item.
	Snippet *string `pulumi:"snippet"`
	Tfid    string  `pulumi:"tfid"`
	// The total number of items.
	Total int `pulumi:"total"`
}

func GetBgpAuthProfileListOutput(ctx *pulumi.Context, args GetBgpAuthProfileListOutputArgs, opts ...pulumi.InvokeOption) GetBgpAuthProfileListResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetBgpAuthProfileListResultOutput, error) {
			args := v.(GetBgpAuthProfileListArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("scm:index/getBgpAuthProfileList:getBgpAuthProfileList", args, GetBgpAuthProfileListResultOutput{}, options).(GetBgpAuthProfileListResultOutput), nil
		}).(GetBgpAuthProfileListResultOutput)
}

// A collection of arguments for invoking getBgpAuthProfileList.
type GetBgpAuthProfileListOutputArgs struct {
	// The device of the item.
	Device pulumi.StringPtrInput `pulumi:"device"`
	// The folder of the item. Default: Shared.
	Folder pulumi.StringPtrInput `pulumi:"folder"`
	// The max number of items to return. Default: 200.
	Limit pulumi.IntPtrInput `pulumi:"limit"`
	// The name of the item.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The offset of the first item to return.
	Offset pulumi.IntPtrInput `pulumi:"offset"`
	// The snippet of the item.
	Snippet pulumi.StringPtrInput `pulumi:"snippet"`
}

func (GetBgpAuthProfileListOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBgpAuthProfileListArgs)(nil)).Elem()
}

// A collection of values returned by getBgpAuthProfileList.
type GetBgpAuthProfileListResultOutput struct{ *pulumi.OutputState }

func (GetBgpAuthProfileListResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBgpAuthProfileListResult)(nil)).Elem()
}

func (o GetBgpAuthProfileListResultOutput) ToGetBgpAuthProfileListResultOutput() GetBgpAuthProfileListResultOutput {
	return o
}

func (o GetBgpAuthProfileListResultOutput) ToGetBgpAuthProfileListResultOutputWithContext(ctx context.Context) GetBgpAuthProfileListResultOutput {
	return o
}

// The data.
func (o GetBgpAuthProfileListResultOutput) Datas() GetBgpAuthProfileListDataArrayOutput {
	return o.ApplyT(func(v GetBgpAuthProfileListResult) []GetBgpAuthProfileListData { return v.Datas }).(GetBgpAuthProfileListDataArrayOutput)
}

// The device of the item.
func (o GetBgpAuthProfileListResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetBgpAuthProfileListResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

// The folder of the item. Default: Shared.
func (o GetBgpAuthProfileListResultOutput) Folder() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetBgpAuthProfileListResult) *string { return v.Folder }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetBgpAuthProfileListResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetBgpAuthProfileListResult) string { return v.Id }).(pulumi.StringOutput)
}

// The max number of items to return. Default: 200.
func (o GetBgpAuthProfileListResultOutput) Limit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetBgpAuthProfileListResult) *int { return v.Limit }).(pulumi.IntPtrOutput)
}

// The name of the item.
func (o GetBgpAuthProfileListResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetBgpAuthProfileListResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// The offset of the first item to return.
func (o GetBgpAuthProfileListResultOutput) Offset() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetBgpAuthProfileListResult) *int { return v.Offset }).(pulumi.IntPtrOutput)
}

// The snippet of the item.
func (o GetBgpAuthProfileListResultOutput) Snippet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetBgpAuthProfileListResult) *string { return v.Snippet }).(pulumi.StringPtrOutput)
}

func (o GetBgpAuthProfileListResultOutput) Tfid() pulumi.StringOutput {
	return o.ApplyT(func(v GetBgpAuthProfileListResult) string { return v.Tfid }).(pulumi.StringOutput)
}

// The total number of items.
func (o GetBgpAuthProfileListResultOutput) Total() pulumi.IntOutput {
	return o.ApplyT(func(v GetBgpAuthProfileListResult) int { return v.Total }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetBgpAuthProfileListResultOutput{})
}
