// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scm

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-scm/sdk/go/scm/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves a listing of config items.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-scm/sdk/go/scm"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			example, err := scm.GetBandwidthAllocationList(ctx, &scm.GetBandwidthAllocationListArgs{
//				Name:   pulumi.StringRef("taiwan"),
//				Limit:  pulumi.IntRef(50),
//				Offset: pulumi.IntRef(0),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("allocationList", example.Datas)
//			return nil
//		})
//	}
//
// ```
func GetBandwidthAllocationList(ctx *pulumi.Context, args *GetBandwidthAllocationListArgs, opts ...pulumi.InvokeOption) (*GetBandwidthAllocationListResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetBandwidthAllocationListResult
	err := ctx.Invoke("scm:index/getBandwidthAllocationList:getBandwidthAllocationList", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBandwidthAllocationList.
type GetBandwidthAllocationListArgs struct {
	// The device of the item.
	Device *string `pulumi:"device"`
	// The folder of the item. Default: Shared.
	Folder *string `pulumi:"folder"`
	// The max number of items to return. Default: 200.
	Limit *int `pulumi:"limit"`
	// The name of the item.
	Name *string `pulumi:"name"`
	// The offset of the first item to return.
	Offset *int `pulumi:"offset"`
	// The snippet of the item.
	Snippet *string `pulumi:"snippet"`
}

// A collection of values returned by getBandwidthAllocationList.
type GetBandwidthAllocationListResult struct {
	// The data.
	Datas []GetBandwidthAllocationListData `pulumi:"datas"`
	// The device of the item.
	Device *string `pulumi:"device"`
	// The folder of the item. Default: Shared.
	Folder *string `pulumi:"folder"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The max number of items to return. Default: 200.
	Limit *int `pulumi:"limit"`
	// The name of the item.
	Name *string `pulumi:"name"`
	// The offset of the first item to return.
	Offset *int `pulumi:"offset"`
	// The snippet of the item.
	Snippet *string `pulumi:"snippet"`
	// The Terraform ID.
	Tfid string `pulumi:"tfid"`
	// The total number of items.
	Total int `pulumi:"total"`
}

func GetBandwidthAllocationListOutput(ctx *pulumi.Context, args GetBandwidthAllocationListOutputArgs, opts ...pulumi.InvokeOption) GetBandwidthAllocationListResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetBandwidthAllocationListResultOutput, error) {
			args := v.(GetBandwidthAllocationListArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("scm:index/getBandwidthAllocationList:getBandwidthAllocationList", args, GetBandwidthAllocationListResultOutput{}, options).(GetBandwidthAllocationListResultOutput), nil
		}).(GetBandwidthAllocationListResultOutput)
}

// A collection of arguments for invoking getBandwidthAllocationList.
type GetBandwidthAllocationListOutputArgs struct {
	// The device of the item.
	Device pulumi.StringPtrInput `pulumi:"device"`
	// The folder of the item. Default: Shared.
	Folder pulumi.StringPtrInput `pulumi:"folder"`
	// The max number of items to return. Default: 200.
	Limit pulumi.IntPtrInput `pulumi:"limit"`
	// The name of the item.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The offset of the first item to return.
	Offset pulumi.IntPtrInput `pulumi:"offset"`
	// The snippet of the item.
	Snippet pulumi.StringPtrInput `pulumi:"snippet"`
}

func (GetBandwidthAllocationListOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBandwidthAllocationListArgs)(nil)).Elem()
}

// A collection of values returned by getBandwidthAllocationList.
type GetBandwidthAllocationListResultOutput struct{ *pulumi.OutputState }

func (GetBandwidthAllocationListResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBandwidthAllocationListResult)(nil)).Elem()
}

func (o GetBandwidthAllocationListResultOutput) ToGetBandwidthAllocationListResultOutput() GetBandwidthAllocationListResultOutput {
	return o
}

func (o GetBandwidthAllocationListResultOutput) ToGetBandwidthAllocationListResultOutputWithContext(ctx context.Context) GetBandwidthAllocationListResultOutput {
	return o
}

// The data.
func (o GetBandwidthAllocationListResultOutput) Datas() GetBandwidthAllocationListDataArrayOutput {
	return o.ApplyT(func(v GetBandwidthAllocationListResult) []GetBandwidthAllocationListData { return v.Datas }).(GetBandwidthAllocationListDataArrayOutput)
}

// The device of the item.
func (o GetBandwidthAllocationListResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetBandwidthAllocationListResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

// The folder of the item. Default: Shared.
func (o GetBandwidthAllocationListResultOutput) Folder() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetBandwidthAllocationListResult) *string { return v.Folder }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetBandwidthAllocationListResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetBandwidthAllocationListResult) string { return v.Id }).(pulumi.StringOutput)
}

// The max number of items to return. Default: 200.
func (o GetBandwidthAllocationListResultOutput) Limit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetBandwidthAllocationListResult) *int { return v.Limit }).(pulumi.IntPtrOutput)
}

// The name of the item.
func (o GetBandwidthAllocationListResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetBandwidthAllocationListResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// The offset of the first item to return.
func (o GetBandwidthAllocationListResultOutput) Offset() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetBandwidthAllocationListResult) *int { return v.Offset }).(pulumi.IntPtrOutput)
}

// The snippet of the item.
func (o GetBandwidthAllocationListResultOutput) Snippet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetBandwidthAllocationListResult) *string { return v.Snippet }).(pulumi.StringPtrOutput)
}

// The Terraform ID.
func (o GetBandwidthAllocationListResultOutput) Tfid() pulumi.StringOutput {
	return o.ApplyT(func(v GetBandwidthAllocationListResult) string { return v.Tfid }).(pulumi.StringOutput)
}

// The total number of items.
func (o GetBandwidthAllocationListResultOutput) Total() pulumi.IntOutput {
	return o.ApplyT(func(v GetBandwidthAllocationListResult) int { return v.Total }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetBandwidthAllocationListResultOutput{})
}
