// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scm

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-scm/sdk/go/scm/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves a listing of config items.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-scm/sdk/go/scm"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := scm.GetRemoteNetworkList(ctx, &scm.GetRemoteNetworkListArgs{
//				Folder: pulumi.StringRef("Remote Networks"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetRemoteNetworkList(ctx *pulumi.Context, args *GetRemoteNetworkListArgs, opts ...pulumi.InvokeOption) (*GetRemoteNetworkListResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetRemoteNetworkListResult
	err := ctx.Invoke("scm:index/getRemoteNetworkList:getRemoteNetworkList", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getRemoteNetworkList.
type GetRemoteNetworkListArgs struct {
	// The Folder param. String can either be a specific string(`"Remote Networks"`) or match this regex: `^[\s0-9a-zA-Z._-]{1,}$`. Default: `"Remote Networks"`.
	Folder *string `pulumi:"folder"`
	// The Limit param. A limit of -1 will return all configured items. Default: `200`.
	Limit *int `pulumi:"limit"`
	// The Name param.
	Name *string `pulumi:"name"`
	// The Offset param. Default: `0`.
	Offset *int `pulumi:"offset"`
}

// A collection of values returned by getRemoteNetworkList.
type GetRemoteNetworkListResult struct {
	// The Data param.
	Datas []GetRemoteNetworkListData `pulumi:"datas"`
	// The Folder param. String can either be a specific string(`"Remote Networks"`) or match this regex: `^[\s0-9a-zA-Z._-]{1,}$`. Default: `"Remote Networks"`.
	Folder string `pulumi:"folder"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The Limit param. A limit of -1 will return all configured items. Default: `200`.
	Limit int `pulumi:"limit"`
	// The Name param.
	Name *string `pulumi:"name"`
	// The Offset param. Default: `0`.
	Offset int    `pulumi:"offset"`
	Tfid   string `pulumi:"tfid"`
	// The Total param.
	Total int `pulumi:"total"`
}

func GetRemoteNetworkListOutput(ctx *pulumi.Context, args GetRemoteNetworkListOutputArgs, opts ...pulumi.InvokeOption) GetRemoteNetworkListResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetRemoteNetworkListResultOutput, error) {
			args := v.(GetRemoteNetworkListArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("scm:index/getRemoteNetworkList:getRemoteNetworkList", args, GetRemoteNetworkListResultOutput{}, options).(GetRemoteNetworkListResultOutput), nil
		}).(GetRemoteNetworkListResultOutput)
}

// A collection of arguments for invoking getRemoteNetworkList.
type GetRemoteNetworkListOutputArgs struct {
	// The Folder param. String can either be a specific string(`"Remote Networks"`) or match this regex: `^[\s0-9a-zA-Z._-]{1,}$`. Default: `"Remote Networks"`.
	Folder pulumi.StringPtrInput `pulumi:"folder"`
	// The Limit param. A limit of -1 will return all configured items. Default: `200`.
	Limit pulumi.IntPtrInput `pulumi:"limit"`
	// The Name param.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The Offset param. Default: `0`.
	Offset pulumi.IntPtrInput `pulumi:"offset"`
}

func (GetRemoteNetworkListOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRemoteNetworkListArgs)(nil)).Elem()
}

// A collection of values returned by getRemoteNetworkList.
type GetRemoteNetworkListResultOutput struct{ *pulumi.OutputState }

func (GetRemoteNetworkListResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRemoteNetworkListResult)(nil)).Elem()
}

func (o GetRemoteNetworkListResultOutput) ToGetRemoteNetworkListResultOutput() GetRemoteNetworkListResultOutput {
	return o
}

func (o GetRemoteNetworkListResultOutput) ToGetRemoteNetworkListResultOutputWithContext(ctx context.Context) GetRemoteNetworkListResultOutput {
	return o
}

// The Data param.
func (o GetRemoteNetworkListResultOutput) Datas() GetRemoteNetworkListDataArrayOutput {
	return o.ApplyT(func(v GetRemoteNetworkListResult) []GetRemoteNetworkListData { return v.Datas }).(GetRemoteNetworkListDataArrayOutput)
}

// The Folder param. String can either be a specific string(`"Remote Networks"`) or match this regex: `^[\s0-9a-zA-Z._-]{1,}$`. Default: `"Remote Networks"`.
func (o GetRemoteNetworkListResultOutput) Folder() pulumi.StringOutput {
	return o.ApplyT(func(v GetRemoteNetworkListResult) string { return v.Folder }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetRemoteNetworkListResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetRemoteNetworkListResult) string { return v.Id }).(pulumi.StringOutput)
}

// The Limit param. A limit of -1 will return all configured items. Default: `200`.
func (o GetRemoteNetworkListResultOutput) Limit() pulumi.IntOutput {
	return o.ApplyT(func(v GetRemoteNetworkListResult) int { return v.Limit }).(pulumi.IntOutput)
}

// The Name param.
func (o GetRemoteNetworkListResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetRemoteNetworkListResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// The Offset param. Default: `0`.
func (o GetRemoteNetworkListResultOutput) Offset() pulumi.IntOutput {
	return o.ApplyT(func(v GetRemoteNetworkListResult) int { return v.Offset }).(pulumi.IntOutput)
}

func (o GetRemoteNetworkListResultOutput) Tfid() pulumi.StringOutput {
	return o.ApplyT(func(v GetRemoteNetworkListResult) string { return v.Tfid }).(pulumi.StringOutput)
}

// The Total param.
func (o GetRemoteNetworkListResultOutput) Total() pulumi.IntOutput {
	return o.ApplyT(func(v GetRemoteNetworkListResult) int { return v.Total }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetRemoteNetworkListResultOutput{})
}
