// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scm

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-scm/sdk/go/scm/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves a listing of config items.
func GetScheduleList(ctx *pulumi.Context, args *GetScheduleListArgs, opts ...pulumi.InvokeOption) (*GetScheduleListResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetScheduleListResult
	err := ctx.Invoke("scm:index/getScheduleList:getScheduleList", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getScheduleList.
type GetScheduleListArgs struct {
	// The device of the item.
	Device *string `pulumi:"device"`
	// The folder of the item. Default: Shared.
	Folder *string `pulumi:"folder"`
	// The max number of items to return. Default: 200.
	Limit *int `pulumi:"limit"`
	// The name of the item.
	Name *string `pulumi:"name"`
	// The offset of the first item to return.
	Offset *int `pulumi:"offset"`
	// The snippet of the item.
	Snippet *string `pulumi:"snippet"`
}

// A collection of values returned by getScheduleList.
type GetScheduleListResult struct {
	// The data.
	Datas []GetScheduleListData `pulumi:"datas"`
	// The device of the item.
	Device *string `pulumi:"device"`
	// The folder of the item. Default: Shared.
	Folder *string `pulumi:"folder"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The max number of items to return. Default: 200.
	Limit *int `pulumi:"limit"`
	// The name of the item.
	Name *string `pulumi:"name"`
	// The offset of the first item to return.
	Offset *int `pulumi:"offset"`
	// The snippet of the item.
	Snippet *string `pulumi:"snippet"`
	Tfid    string  `pulumi:"tfid"`
	// The total number of items.
	Total int `pulumi:"total"`
}

func GetScheduleListOutput(ctx *pulumi.Context, args GetScheduleListOutputArgs, opts ...pulumi.InvokeOption) GetScheduleListResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetScheduleListResultOutput, error) {
			args := v.(GetScheduleListArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("scm:index/getScheduleList:getScheduleList", args, GetScheduleListResultOutput{}, options).(GetScheduleListResultOutput), nil
		}).(GetScheduleListResultOutput)
}

// A collection of arguments for invoking getScheduleList.
type GetScheduleListOutputArgs struct {
	// The device of the item.
	Device pulumi.StringPtrInput `pulumi:"device"`
	// The folder of the item. Default: Shared.
	Folder pulumi.StringPtrInput `pulumi:"folder"`
	// The max number of items to return. Default: 200.
	Limit pulumi.IntPtrInput `pulumi:"limit"`
	// The name of the item.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The offset of the first item to return.
	Offset pulumi.IntPtrInput `pulumi:"offset"`
	// The snippet of the item.
	Snippet pulumi.StringPtrInput `pulumi:"snippet"`
}

func (GetScheduleListOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetScheduleListArgs)(nil)).Elem()
}

// A collection of values returned by getScheduleList.
type GetScheduleListResultOutput struct{ *pulumi.OutputState }

func (GetScheduleListResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetScheduleListResult)(nil)).Elem()
}

func (o GetScheduleListResultOutput) ToGetScheduleListResultOutput() GetScheduleListResultOutput {
	return o
}

func (o GetScheduleListResultOutput) ToGetScheduleListResultOutputWithContext(ctx context.Context) GetScheduleListResultOutput {
	return o
}

// The data.
func (o GetScheduleListResultOutput) Datas() GetScheduleListDataArrayOutput {
	return o.ApplyT(func(v GetScheduleListResult) []GetScheduleListData { return v.Datas }).(GetScheduleListDataArrayOutput)
}

// The device of the item.
func (o GetScheduleListResultOutput) Device() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetScheduleListResult) *string { return v.Device }).(pulumi.StringPtrOutput)
}

// The folder of the item. Default: Shared.
func (o GetScheduleListResultOutput) Folder() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetScheduleListResult) *string { return v.Folder }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetScheduleListResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetScheduleListResult) string { return v.Id }).(pulumi.StringOutput)
}

// The max number of items to return. Default: 200.
func (o GetScheduleListResultOutput) Limit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetScheduleListResult) *int { return v.Limit }).(pulumi.IntPtrOutput)
}

// The name of the item.
func (o GetScheduleListResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetScheduleListResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// The offset of the first item to return.
func (o GetScheduleListResultOutput) Offset() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetScheduleListResult) *int { return v.Offset }).(pulumi.IntPtrOutput)
}

// The snippet of the item.
func (o GetScheduleListResultOutput) Snippet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetScheduleListResult) *string { return v.Snippet }).(pulumi.StringPtrOutput)
}

func (o GetScheduleListResultOutput) Tfid() pulumi.StringOutput {
	return o.ApplyT(func(v GetScheduleListResult) string { return v.Tfid }).(pulumi.StringOutput)
}

// The total number of items.
func (o GetScheduleListResultOutput) Total() pulumi.IntOutput {
	return o.ApplyT(func(v GetScheduleListResult) int { return v.Total }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetScheduleListResultOutput{})
}
