// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scm

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-scm/sdk/go/scm/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SamlServerProfile data source
func LookupSamlServerProfile(ctx *pulumi.Context, args *LookupSamlServerProfileArgs, opts ...pulumi.InvokeOption) (*LookupSamlServerProfileResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSamlServerProfileResult
	err := ctx.Invoke("scm:index/getSamlServerProfile:getSamlServerProfile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSamlServerProfile.
type LookupSamlServerProfileArgs struct {
	// The device in which the resource is defined
	// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
	Device *string `pulumi:"device"`
	// The folder in which the resource is defined
	// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
	Folder *string `pulumi:"folder"`
	// The UUID of the SAML server profile
	Id string `pulumi:"id"`
	// The name of the SAML server profile
	Name *string `pulumi:"name"`
	// The snippet in which the resource is defined
	// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
	Snippet *string `pulumi:"snippet"`
}

// A collection of values returned by getSamlServerProfile.
type LookupSamlServerProfileResult struct {
	// The identity provider certificate
	Certificate string `pulumi:"certificate"`
	// The device in which the resource is defined
	// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
	Device string `pulumi:"device"`
	// The identity provider ID
	EntityId string `pulumi:"entityId"`
	// The folder in which the resource is defined
	// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
	Folder string `pulumi:"folder"`
	// The UUID of the SAML server profile
	Id string `pulumi:"id"`
	// Maxiumum clock skew
	MaxClockSkew int `pulumi:"maxClockSkew"`
	// The name of the SAML server profile
	Name string `pulumi:"name"`
	// SAML HTTP binding for SLO requests to the identity provider
	SloBindings string `pulumi:"sloBindings"`
	// The snippet in which the resource is defined
	// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
	Snippet string `pulumi:"snippet"`
	// SAML HTTP binding for SSO requests to the identity provider
	SsoBindings string `pulumi:"ssoBindings"`
	// Identity provider SSO URL
	SsoUrl string `pulumi:"ssoUrl"`
	Tfid   string `pulumi:"tfid"`
	// Validate the identity provider certificate?
	ValidateIdpCertificate bool `pulumi:"validateIdpCertificate"`
	// Sign SAML message to the identity provider?
	WantAuthRequestsSigned bool `pulumi:"wantAuthRequestsSigned"`
}

func LookupSamlServerProfileOutput(ctx *pulumi.Context, args LookupSamlServerProfileOutputArgs, opts ...pulumi.InvokeOption) LookupSamlServerProfileResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSamlServerProfileResultOutput, error) {
			args := v.(LookupSamlServerProfileArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("scm:index/getSamlServerProfile:getSamlServerProfile", args, LookupSamlServerProfileResultOutput{}, options).(LookupSamlServerProfileResultOutput), nil
		}).(LookupSamlServerProfileResultOutput)
}

// A collection of arguments for invoking getSamlServerProfile.
type LookupSamlServerProfileOutputArgs struct {
	// The device in which the resource is defined
	// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
	Device pulumi.StringPtrInput `pulumi:"device"`
	// The folder in which the resource is defined
	// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
	Folder pulumi.StringPtrInput `pulumi:"folder"`
	// The UUID of the SAML server profile
	Id pulumi.StringInput `pulumi:"id"`
	// The name of the SAML server profile
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The snippet in which the resource is defined
	// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
	Snippet pulumi.StringPtrInput `pulumi:"snippet"`
}

func (LookupSamlServerProfileOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSamlServerProfileArgs)(nil)).Elem()
}

// A collection of values returned by getSamlServerProfile.
type LookupSamlServerProfileResultOutput struct{ *pulumi.OutputState }

func (LookupSamlServerProfileResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSamlServerProfileResult)(nil)).Elem()
}

func (o LookupSamlServerProfileResultOutput) ToLookupSamlServerProfileResultOutput() LookupSamlServerProfileResultOutput {
	return o
}

func (o LookupSamlServerProfileResultOutput) ToLookupSamlServerProfileResultOutputWithContext(ctx context.Context) LookupSamlServerProfileResultOutput {
	return o
}

// The identity provider certificate
func (o LookupSamlServerProfileResultOutput) Certificate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) string { return v.Certificate }).(pulumi.StringOutput)
}

// The device in which the resource is defined
// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
func (o LookupSamlServerProfileResultOutput) Device() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) string { return v.Device }).(pulumi.StringOutput)
}

// The identity provider ID
func (o LookupSamlServerProfileResultOutput) EntityId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) string { return v.EntityId }).(pulumi.StringOutput)
}

// The folder in which the resource is defined
// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
func (o LookupSamlServerProfileResultOutput) Folder() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) string { return v.Folder }).(pulumi.StringOutput)
}

// The UUID of the SAML server profile
func (o LookupSamlServerProfileResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) string { return v.Id }).(pulumi.StringOutput)
}

// Maxiumum clock skew
func (o LookupSamlServerProfileResultOutput) MaxClockSkew() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) int { return v.MaxClockSkew }).(pulumi.IntOutput)
}

// The name of the SAML server profile
func (o LookupSamlServerProfileResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) string { return v.Name }).(pulumi.StringOutput)
}

// SAML HTTP binding for SLO requests to the identity provider
func (o LookupSamlServerProfileResultOutput) SloBindings() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) string { return v.SloBindings }).(pulumi.StringOutput)
}

// The snippet in which the resource is defined
// > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
func (o LookupSamlServerProfileResultOutput) Snippet() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) string { return v.Snippet }).(pulumi.StringOutput)
}

// SAML HTTP binding for SSO requests to the identity provider
func (o LookupSamlServerProfileResultOutput) SsoBindings() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) string { return v.SsoBindings }).(pulumi.StringOutput)
}

// Identity provider SSO URL
func (o LookupSamlServerProfileResultOutput) SsoUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) string { return v.SsoUrl }).(pulumi.StringOutput)
}

func (o LookupSamlServerProfileResultOutput) Tfid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) string { return v.Tfid }).(pulumi.StringOutput)
}

// Validate the identity provider certificate?
func (o LookupSamlServerProfileResultOutput) ValidateIdpCertificate() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) bool { return v.ValidateIdpCertificate }).(pulumi.BoolOutput)
}

// Sign SAML message to the identity provider?
func (o LookupSamlServerProfileResultOutput) WantAuthRequestsSigned() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSamlServerProfileResult) bool { return v.WantAuthRequestsSigned }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSamlServerProfileResultOutput{})
}
