// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;




public final class AntiSpywareSignatureDefaultActionAlertArgs extends com.pulumi.resources.ResourceArgs {

    public static final AntiSpywareSignatureDefaultActionAlertArgs Empty = new AntiSpywareSignatureDefaultActionAlertArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private AntiSpywareSignatureDefaultActionAlertArgs $;

        public Builder() {
            $ = new AntiSpywareSignatureDefaultActionAlertArgs();
        }
        public AntiSpywareSignatureDefaultActionAlertArgs build() {
            return $;
        }
    }

}
