// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BandwidthAllocationQosArgs extends com.pulumi.resources.ResourceArgs {

    public static final BandwidthAllocationQosArgs Empty = new BandwidthAllocationQosArgs();

    /**
     * Customized
     * 
     */
    @Import(name="customized")
    private @Nullable Output<Boolean> customized;

    /**
     * @return Customized
     * 
     */
    public Optional<Output<Boolean>> customized() {
        return Optional.ofNullable(this.customized);
    }

    /**
     * Enabled
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Enabled
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Guaranteed ratio
     * 
     */
    @Import(name="guaranteedRatio")
    private @Nullable Output<Double> guaranteedRatio;

    /**
     * @return Guaranteed ratio
     * 
     */
    public Optional<Output<Double>> guaranteedRatio() {
        return Optional.ofNullable(this.guaranteedRatio);
    }

    /**
     * Profile
     * 
     */
    @Import(name="profile")
    private @Nullable Output<String> profile;

    /**
     * @return Profile
     * 
     */
    public Optional<Output<String>> profile() {
        return Optional.ofNullable(this.profile);
    }

    private BandwidthAllocationQosArgs() {}

    private BandwidthAllocationQosArgs(BandwidthAllocationQosArgs $) {
        this.customized = $.customized;
        this.enabled = $.enabled;
        this.guaranteedRatio = $.guaranteedRatio;
        this.profile = $.profile;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BandwidthAllocationQosArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BandwidthAllocationQosArgs $;

        public Builder() {
            $ = new BandwidthAllocationQosArgs();
        }

        public Builder(BandwidthAllocationQosArgs defaults) {
            $ = new BandwidthAllocationQosArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param customized Customized
         * 
         * @return builder
         * 
         */
        public Builder customized(@Nullable Output<Boolean> customized) {
            $.customized = customized;
            return this;
        }

        /**
         * @param customized Customized
         * 
         * @return builder
         * 
         */
        public Builder customized(Boolean customized) {
            return customized(Output.of(customized));
        }

        /**
         * @param enabled Enabled
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Enabled
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param guaranteedRatio Guaranteed ratio
         * 
         * @return builder
         * 
         */
        public Builder guaranteedRatio(@Nullable Output<Double> guaranteedRatio) {
            $.guaranteedRatio = guaranteedRatio;
            return this;
        }

        /**
         * @param guaranteedRatio Guaranteed ratio
         * 
         * @return builder
         * 
         */
        public Builder guaranteedRatio(Double guaranteedRatio) {
            return guaranteedRatio(Output.of(guaranteedRatio));
        }

        /**
         * @param profile Profile
         * 
         * @return builder
         * 
         */
        public Builder profile(@Nullable Output<String> profile) {
            $.profile = profile;
            return this;
        }

        /**
         * @param profile Profile
         * 
         * @return builder
         * 
         */
        public Builder profile(String profile) {
            return profile(Output.of(profile));
        }

        public BandwidthAllocationQosArgs build() {
            return $;
        }
    }

}
