// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;




public final class BgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelfArgs extends com.pulumi.resources.ResourceArgs {

    public static final BgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelfArgs Empty = new BgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelfArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private BgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelfArgs $;

        public Builder() {
            $ = new BgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelfArgs();
        }
        public BgpAddressFamilyProfileIpv4Ipv4MulticastNextHopSelfArgs build() {
            return $;
        }
    }

}
