// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.scm.inputs.BgpRouteMapRouteMapMatchIpv4AddressArgs;
import com.pulumi.scm.inputs.BgpRouteMapRouteMapMatchIpv4NextHopArgs;
import com.pulumi.scm.inputs.BgpRouteMapRouteMapMatchIpv4RouteSourceArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BgpRouteMapRouteMapMatchIpv4Args extends com.pulumi.resources.ResourceArgs {

    public static final BgpRouteMapRouteMapMatchIpv4Args Empty = new BgpRouteMapRouteMapMatchIpv4Args();

    /**
     * Address
     * 
     */
    @Import(name="address")
    private @Nullable Output<BgpRouteMapRouteMapMatchIpv4AddressArgs> address;

    /**
     * @return Address
     * 
     */
    public Optional<Output<BgpRouteMapRouteMapMatchIpv4AddressArgs>> address() {
        return Optional.ofNullable(this.address);
    }

    /**
     * Next hop
     * 
     */
    @Import(name="nextHop")
    private @Nullable Output<BgpRouteMapRouteMapMatchIpv4NextHopArgs> nextHop;

    /**
     * @return Next hop
     * 
     */
    public Optional<Output<BgpRouteMapRouteMapMatchIpv4NextHopArgs>> nextHop() {
        return Optional.ofNullable(this.nextHop);
    }

    /**
     * Route source
     * 
     */
    @Import(name="routeSource")
    private @Nullable Output<BgpRouteMapRouteMapMatchIpv4RouteSourceArgs> routeSource;

    /**
     * @return Route source
     * 
     */
    public Optional<Output<BgpRouteMapRouteMapMatchIpv4RouteSourceArgs>> routeSource() {
        return Optional.ofNullable(this.routeSource);
    }

    private BgpRouteMapRouteMapMatchIpv4Args() {}

    private BgpRouteMapRouteMapMatchIpv4Args(BgpRouteMapRouteMapMatchIpv4Args $) {
        this.address = $.address;
        this.nextHop = $.nextHop;
        this.routeSource = $.routeSource;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BgpRouteMapRouteMapMatchIpv4Args defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BgpRouteMapRouteMapMatchIpv4Args $;

        public Builder() {
            $ = new BgpRouteMapRouteMapMatchIpv4Args();
        }

        public Builder(BgpRouteMapRouteMapMatchIpv4Args defaults) {
            $ = new BgpRouteMapRouteMapMatchIpv4Args(Objects.requireNonNull(defaults));
        }

        /**
         * @param address Address
         * 
         * @return builder
         * 
         */
        public Builder address(@Nullable Output<BgpRouteMapRouteMapMatchIpv4AddressArgs> address) {
            $.address = address;
            return this;
        }

        /**
         * @param address Address
         * 
         * @return builder
         * 
         */
        public Builder address(BgpRouteMapRouteMapMatchIpv4AddressArgs address) {
            return address(Output.of(address));
        }

        /**
         * @param nextHop Next hop
         * 
         * @return builder
         * 
         */
        public Builder nextHop(@Nullable Output<BgpRouteMapRouteMapMatchIpv4NextHopArgs> nextHop) {
            $.nextHop = nextHop;
            return this;
        }

        /**
         * @param nextHop Next hop
         * 
         * @return builder
         * 
         */
        public Builder nextHop(BgpRouteMapRouteMapMatchIpv4NextHopArgs nextHop) {
            return nextHop(Output.of(nextHop));
        }

        /**
         * @param routeSource Route source
         * 
         * @return builder
         * 
         */
        public Builder routeSource(@Nullable Output<BgpRouteMapRouteMapMatchIpv4RouteSourceArgs> routeSource) {
            $.routeSource = routeSource;
            return this;
        }

        /**
         * @param routeSource Route source
         * 
         * @return builder
         * 
         */
        public Builder routeSource(BgpRouteMapRouteMapMatchIpv4RouteSourceArgs routeSource) {
            return routeSource(Output.of(routeSource));
        }

        public BgpRouteMapRouteMapMatchIpv4Args build() {
            return $;
        }
    }

}
