// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAggregateEthernetInterfacePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAggregateEthernetInterfacePlainArgs Empty = new GetAggregateEthernetInterfacePlainArgs();

    /**
     * UUID of the resource
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return UUID of the resource
     * 
     */
    public String id() {
        return this.id;
    }

    /**
     * Aggregate interface name
     * 
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return Aggregate interface name
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    private GetAggregateEthernetInterfacePlainArgs() {}

    private GetAggregateEthernetInterfacePlainArgs(GetAggregateEthernetInterfacePlainArgs $) {
        this.id = $.id;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAggregateEthernetInterfacePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAggregateEthernetInterfacePlainArgs $;

        public Builder() {
            $ = new GetAggregateEthernetInterfacePlainArgs();
        }

        public Builder(GetAggregateEthernetInterfacePlainArgs defaults) {
            $ = new GetAggregateEthernetInterfacePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id UUID of the resource
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        /**
         * @param name Aggregate interface name
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        public GetAggregateEthernetInterfacePlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetAggregateEthernetInterfacePlainArgs", "id");
            }
            return $;
        }
    }

}
