// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetServiceConnectionGroupPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetServiceConnectionGroupPlainArgs Empty = new GetServiceConnectionGroupPlainArgs();

    /**
     * The folder in which the resource is defined
     * 
     */
    @Import(name="folder")
    private @Nullable String folder;

    /**
     * @return The folder in which the resource is defined
     * 
     */
    public Optional<String> folder() {
        return Optional.ofNullable(this.folder);
    }

    /**
     * The UUID of the service connection group
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return The UUID of the service connection group
     * 
     */
    public String id() {
        return this.id;
    }

    /**
     * Name
     * 
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return Name
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    private GetServiceConnectionGroupPlainArgs() {}

    private GetServiceConnectionGroupPlainArgs(GetServiceConnectionGroupPlainArgs $) {
        this.folder = $.folder;
        this.id = $.id;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetServiceConnectionGroupPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetServiceConnectionGroupPlainArgs $;

        public Builder() {
            $ = new GetServiceConnectionGroupPlainArgs();
        }

        public Builder(GetServiceConnectionGroupPlainArgs defaults) {
            $ = new GetServiceConnectionGroupPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param folder The folder in which the resource is defined
         * 
         * @return builder
         * 
         */
        public Builder folder(@Nullable String folder) {
            $.folder = folder;
            return this;
        }

        /**
         * @param id The UUID of the service connection group
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        /**
         * @param name Name
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        public GetServiceConnectionGroupPlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetServiceConnectionGroupPlainArgs", "id");
            }
            return $;
        }
    }

}
