// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.scm.inputs.LogicalRouterVrfRoutingTableIpStaticRouteArgs;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogicalRouterVrfRoutingTableIpArgs extends com.pulumi.resources.ResourceArgs {

    public static final LogicalRouterVrfRoutingTableIpArgs Empty = new LogicalRouterVrfRoutingTableIpArgs();

    /**
     * Static route
     * 
     */
    @Import(name="staticRoutes")
    private @Nullable Output<List<LogicalRouterVrfRoutingTableIpStaticRouteArgs>> staticRoutes;

    /**
     * @return Static route
     * 
     */
    public Optional<Output<List<LogicalRouterVrfRoutingTableIpStaticRouteArgs>>> staticRoutes() {
        return Optional.ofNullable(this.staticRoutes);
    }

    private LogicalRouterVrfRoutingTableIpArgs() {}

    private LogicalRouterVrfRoutingTableIpArgs(LogicalRouterVrfRoutingTableIpArgs $) {
        this.staticRoutes = $.staticRoutes;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogicalRouterVrfRoutingTableIpArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogicalRouterVrfRoutingTableIpArgs $;

        public Builder() {
            $ = new LogicalRouterVrfRoutingTableIpArgs();
        }

        public Builder(LogicalRouterVrfRoutingTableIpArgs defaults) {
            $ = new LogicalRouterVrfRoutingTableIpArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param staticRoutes Static route
         * 
         * @return builder
         * 
         */
        public Builder staticRoutes(@Nullable Output<List<LogicalRouterVrfRoutingTableIpStaticRouteArgs>> staticRoutes) {
            $.staticRoutes = staticRoutes;
            return this;
        }

        /**
         * @param staticRoutes Static route
         * 
         * @return builder
         * 
         */
        public Builder staticRoutes(List<LogicalRouterVrfRoutingTableIpStaticRouteArgs> staticRoutes) {
            return staticRoutes(Output.of(staticRoutes));
        }

        /**
         * @param staticRoutes Static route
         * 
         * @return builder
         * 
         */
        public Builder staticRoutes(LogicalRouterVrfRoutingTableIpStaticRouteArgs... staticRoutes) {
            return staticRoutes(List.of(staticRoutes));
        }

        public LogicalRouterVrfRoutingTableIpArgs build() {
            return $;
        }
    }

}
