// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogicalRouterVrfRipGlobalOutboundDistributeListArgs extends com.pulumi.resources.ResourceArgs {

    public static final LogicalRouterVrfRipGlobalOutboundDistributeListArgs Empty = new LogicalRouterVrfRipGlobalOutboundDistributeListArgs();

    /**
     * Access list
     * 
     */
    @Import(name="accessList")
    private @Nullable Output<String> accessList;

    /**
     * @return Access list
     * 
     */
    public Optional<Output<String>> accessList() {
        return Optional.ofNullable(this.accessList);
    }

    private LogicalRouterVrfRipGlobalOutboundDistributeListArgs() {}

    private LogicalRouterVrfRipGlobalOutboundDistributeListArgs(LogicalRouterVrfRipGlobalOutboundDistributeListArgs $) {
        this.accessList = $.accessList;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogicalRouterVrfRipGlobalOutboundDistributeListArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogicalRouterVrfRipGlobalOutboundDistributeListArgs $;

        public Builder() {
            $ = new LogicalRouterVrfRipGlobalOutboundDistributeListArgs();
        }

        public Builder(LogicalRouterVrfRipGlobalOutboundDistributeListArgs defaults) {
            $ = new LogicalRouterVrfRipGlobalOutboundDistributeListArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessList Access list
         * 
         * @return builder
         * 
         */
        public Builder accessList(@Nullable Output<String> accessList) {
            $.accessList = accessList;
            return this;
        }

        /**
         * @param accessList Access list
         * 
         * @return builder
         * 
         */
        public Builder accessList(String accessList) {
            return accessList(Output.of(accessList));
        }

        public LogicalRouterVrfRipGlobalOutboundDistributeListArgs build() {
            return $;
        }
    }

}
