// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs extends com.pulumi.resources.ResourceArgs {

    public static final LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs Empty = new LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs();

    /**
     * Dead counts
     * 
     */
    @Import(name="deadCounts")
    private @Nullable Output<Integer> deadCounts;

    /**
     * @return Dead counts
     * 
     */
    public Optional<Output<Integer>> deadCounts() {
        return Optional.ofNullable(this.deadCounts);
    }

    /**
     * Gr delay
     * 
     */
    @Import(name="grDelay")
    private @Nullable Output<Integer> grDelay;

    /**
     * @return Gr delay
     * 
     */
    public Optional<Output<Integer>> grDelay() {
        return Optional.ofNullable(this.grDelay);
    }

    /**
     * Hello interval
     * 
     */
    @Import(name="helloInterval")
    private @Nullable Output<Integer> helloInterval;

    /**
     * @return Hello interval
     * 
     */
    public Optional<Output<Integer>> helloInterval() {
        return Optional.ofNullable(this.helloInterval);
    }

    /**
     * Retransmit interval
     * 
     */
    @Import(name="retransmitInterval")
    private @Nullable Output<Integer> retransmitInterval;

    /**
     * @return Retransmit interval
     * 
     */
    public Optional<Output<Integer>> retransmitInterval() {
        return Optional.ofNullable(this.retransmitInterval);
    }

    /**
     * Transit delay
     * 
     */
    @Import(name="transitDelay")
    private @Nullable Output<Integer> transitDelay;

    /**
     * @return Transit delay
     * 
     */
    public Optional<Output<Integer>> transitDelay() {
        return Optional.ofNullable(this.transitDelay);
    }

    private LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs() {}

    private LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs(LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs $) {
        this.deadCounts = $.deadCounts;
        this.grDelay = $.grDelay;
        this.helloInterval = $.helloInterval;
        this.retransmitInterval = $.retransmitInterval;
        this.transitDelay = $.transitDelay;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs $;

        public Builder() {
            $ = new LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs();
        }

        public Builder(LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs defaults) {
            $ = new LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param deadCounts Dead counts
         * 
         * @return builder
         * 
         */
        public Builder deadCounts(@Nullable Output<Integer> deadCounts) {
            $.deadCounts = deadCounts;
            return this;
        }

        /**
         * @param deadCounts Dead counts
         * 
         * @return builder
         * 
         */
        public Builder deadCounts(Integer deadCounts) {
            return deadCounts(Output.of(deadCounts));
        }

        /**
         * @param grDelay Gr delay
         * 
         * @return builder
         * 
         */
        public Builder grDelay(@Nullable Output<Integer> grDelay) {
            $.grDelay = grDelay;
            return this;
        }

        /**
         * @param grDelay Gr delay
         * 
         * @return builder
         * 
         */
        public Builder grDelay(Integer grDelay) {
            return grDelay(Output.of(grDelay));
        }

        /**
         * @param helloInterval Hello interval
         * 
         * @return builder
         * 
         */
        public Builder helloInterval(@Nullable Output<Integer> helloInterval) {
            $.helloInterval = helloInterval;
            return this;
        }

        /**
         * @param helloInterval Hello interval
         * 
         * @return builder
         * 
         */
        public Builder helloInterval(Integer helloInterval) {
            return helloInterval(Output.of(helloInterval));
        }

        /**
         * @param retransmitInterval Retransmit interval
         * 
         * @return builder
         * 
         */
        public Builder retransmitInterval(@Nullable Output<Integer> retransmitInterval) {
            $.retransmitInterval = retransmitInterval;
            return this;
        }

        /**
         * @param retransmitInterval Retransmit interval
         * 
         * @return builder
         * 
         */
        public Builder retransmitInterval(Integer retransmitInterval) {
            return retransmitInterval(Output.of(retransmitInterval));
        }

        /**
         * @param transitDelay Transit delay
         * 
         * @return builder
         * 
         */
        public Builder transitDelay(@Nullable Output<Integer> transitDelay) {
            $.transitDelay = transitDelay;
            return this;
        }

        /**
         * @param transitDelay Transit delay
         * 
         * @return builder
         * 
         */
        public Builder transitDelay(Integer transitDelay) {
            return transitDelay(Output.of(transitDelay));
        }

        public LogicalRouterVrfOspfv3AreaInterfaceVrTimingArgs build() {
            return $;
        }
    }

}
