// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.scm.inputs.LogicalRouterVrfBgpPeerGroupTypeEbgpArgs;
import com.pulumi.scm.inputs.LogicalRouterVrfBgpPeerGroupTypeEbgpConfedArgs;
import com.pulumi.scm.inputs.LogicalRouterVrfBgpPeerGroupTypeIbgpArgs;
import com.pulumi.scm.inputs.LogicalRouterVrfBgpPeerGroupTypeIbgpConfedArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogicalRouterVrfBgpPeerGroupTypeArgs extends com.pulumi.resources.ResourceArgs {

    public static final LogicalRouterVrfBgpPeerGroupTypeArgs Empty = new LogicalRouterVrfBgpPeerGroupTypeArgs();

    /**
     * Ebgp
     * 
     */
    @Import(name="ebgp")
    private @Nullable Output<LogicalRouterVrfBgpPeerGroupTypeEbgpArgs> ebgp;

    /**
     * @return Ebgp
     * 
     */
    public Optional<Output<LogicalRouterVrfBgpPeerGroupTypeEbgpArgs>> ebgp() {
        return Optional.ofNullable(this.ebgp);
    }

    /**
     * Ebgp confed
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
     * 
     */
    @Import(name="ebgpConfed")
    private @Nullable Output<LogicalRouterVrfBgpPeerGroupTypeEbgpConfedArgs> ebgpConfed;

    /**
     * @return Ebgp confed
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
     * 
     */
    public Optional<Output<LogicalRouterVrfBgpPeerGroupTypeEbgpConfedArgs>> ebgpConfed() {
        return Optional.ofNullable(this.ebgpConfed);
    }

    /**
     * Ibgp
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
     * 
     */
    @Import(name="ibgp")
    private @Nullable Output<LogicalRouterVrfBgpPeerGroupTypeIbgpArgs> ibgp;

    /**
     * @return Ibgp
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
     * 
     */
    public Optional<Output<LogicalRouterVrfBgpPeerGroupTypeIbgpArgs>> ibgp() {
        return Optional.ofNullable(this.ibgp);
    }

    /**
     * Ibgp confed
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
     * 
     */
    @Import(name="ibgpConfed")
    private @Nullable Output<LogicalRouterVrfBgpPeerGroupTypeIbgpConfedArgs> ibgpConfed;

    /**
     * @return Ibgp confed
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
     * 
     */
    public Optional<Output<LogicalRouterVrfBgpPeerGroupTypeIbgpConfedArgs>> ibgpConfed() {
        return Optional.ofNullable(this.ibgpConfed);
    }

    private LogicalRouterVrfBgpPeerGroupTypeArgs() {}

    private LogicalRouterVrfBgpPeerGroupTypeArgs(LogicalRouterVrfBgpPeerGroupTypeArgs $) {
        this.ebgp = $.ebgp;
        this.ebgpConfed = $.ebgpConfed;
        this.ibgp = $.ibgp;
        this.ibgpConfed = $.ibgpConfed;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogicalRouterVrfBgpPeerGroupTypeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogicalRouterVrfBgpPeerGroupTypeArgs $;

        public Builder() {
            $ = new LogicalRouterVrfBgpPeerGroupTypeArgs();
        }

        public Builder(LogicalRouterVrfBgpPeerGroupTypeArgs defaults) {
            $ = new LogicalRouterVrfBgpPeerGroupTypeArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param ebgp Ebgp
         * 
         * @return builder
         * 
         */
        public Builder ebgp(@Nullable Output<LogicalRouterVrfBgpPeerGroupTypeEbgpArgs> ebgp) {
            $.ebgp = ebgp;
            return this;
        }

        /**
         * @param ebgp Ebgp
         * 
         * @return builder
         * 
         */
        public Builder ebgp(LogicalRouterVrfBgpPeerGroupTypeEbgpArgs ebgp) {
            return ebgp(Output.of(ebgp));
        }

        /**
         * @param ebgpConfed Ebgp confed
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
         * 
         * @return builder
         * 
         */
        public Builder ebgpConfed(@Nullable Output<LogicalRouterVrfBgpPeerGroupTypeEbgpConfedArgs> ebgpConfed) {
            $.ebgpConfed = ebgpConfed;
            return this;
        }

        /**
         * @param ebgpConfed Ebgp confed
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
         * 
         * @return builder
         * 
         */
        public Builder ebgpConfed(LogicalRouterVrfBgpPeerGroupTypeEbgpConfedArgs ebgpConfed) {
            return ebgpConfed(Output.of(ebgpConfed));
        }

        /**
         * @param ibgp Ibgp
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
         * 
         * @return builder
         * 
         */
        public Builder ibgp(@Nullable Output<LogicalRouterVrfBgpPeerGroupTypeIbgpArgs> ibgp) {
            $.ibgp = ibgp;
            return this;
        }

        /**
         * @param ibgp Ibgp
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
         * 
         * @return builder
         * 
         */
        public Builder ibgp(LogicalRouterVrfBgpPeerGroupTypeIbgpArgs ibgp) {
            return ibgp(Output.of(ibgp));
        }

        /**
         * @param ibgpConfed Ibgp confed
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
         * 
         * @return builder
         * 
         */
        public Builder ibgpConfed(@Nullable Output<LogicalRouterVrfBgpPeerGroupTypeIbgpConfedArgs> ibgpConfed) {
            $.ibgpConfed = ibgpConfed;
            return this;
        }

        /**
         * @param ibgpConfed Ibgp confed
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `ebgp`, `ebgpConfed`, `ibgp`, and `ibgpConfed`.
         * 
         * @return builder
         * 
         */
        public Builder ibgpConfed(LogicalRouterVrfBgpPeerGroupTypeIbgpConfedArgs ibgpConfed) {
            return ibgpConfed(Output.of(ibgpConfed));
        }

        public LogicalRouterVrfBgpPeerGroupTypeArgs build() {
            return $;
        }
    }

}
