// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogicalRouterVrfBgpRedistributionProfileIpv4Args extends com.pulumi.resources.ResourceArgs {

    public static final LogicalRouterVrfBgpRedistributionProfileIpv4Args Empty = new LogicalRouterVrfBgpRedistributionProfileIpv4Args();

    /**
     * Unicast
     * 
     */
    @Import(name="unicast")
    private @Nullable Output<String> unicast;

    /**
     * @return Unicast
     * 
     */
    public Optional<Output<String>> unicast() {
        return Optional.ofNullable(this.unicast);
    }

    private LogicalRouterVrfBgpRedistributionProfileIpv4Args() {}

    private LogicalRouterVrfBgpRedistributionProfileIpv4Args(LogicalRouterVrfBgpRedistributionProfileIpv4Args $) {
        this.unicast = $.unicast;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogicalRouterVrfBgpRedistributionProfileIpv4Args defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogicalRouterVrfBgpRedistributionProfileIpv4Args $;

        public Builder() {
            $ = new LogicalRouterVrfBgpRedistributionProfileIpv4Args();
        }

        public Builder(LogicalRouterVrfBgpRedistributionProfileIpv4Args defaults) {
            $ = new LogicalRouterVrfBgpRedistributionProfileIpv4Args(Objects.requireNonNull(defaults));
        }

        /**
         * @param unicast Unicast
         * 
         * @return builder
         * 
         */
        public Builder unicast(@Nullable Output<String> unicast) {
            $.unicast = unicast;
            return this;
        }

        /**
         * @param unicast Unicast
         * 
         * @return builder
         * 
         */
        public Builder unicast(String unicast) {
            return unicast(Output.of(unicast));
        }

        public LogicalRouterVrfBgpRedistributionProfileIpv4Args build() {
            return $;
        }
    }

}
