// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.scm.inputs.QosProfileClassBandwidthTypeMbpsArgs;
import com.pulumi.scm.inputs.QosProfileClassBandwidthTypePercentageArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class QosProfileClassBandwidthTypeArgs extends com.pulumi.resources.ResourceArgs {

    public static final QosProfileClassBandwidthTypeArgs Empty = new QosProfileClassBandwidthTypeArgs();

    /**
     * Mbps
     * 
     */
    @Import(name="mbps")
    private @Nullable Output<QosProfileClassBandwidthTypeMbpsArgs> mbps;

    /**
     * @return Mbps
     * 
     */
    public Optional<Output<QosProfileClassBandwidthTypeMbpsArgs>> mbps() {
        return Optional.ofNullable(this.mbps);
    }

    /**
     * Percentage
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `mbps` and `percentage`.
     * 
     */
    @Import(name="percentage")
    private @Nullable Output<QosProfileClassBandwidthTypePercentageArgs> percentage;

    /**
     * @return Percentage
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `mbps` and `percentage`.
     * 
     */
    public Optional<Output<QosProfileClassBandwidthTypePercentageArgs>> percentage() {
        return Optional.ofNullable(this.percentage);
    }

    private QosProfileClassBandwidthTypeArgs() {}

    private QosProfileClassBandwidthTypeArgs(QosProfileClassBandwidthTypeArgs $) {
        this.mbps = $.mbps;
        this.percentage = $.percentage;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(QosProfileClassBandwidthTypeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private QosProfileClassBandwidthTypeArgs $;

        public Builder() {
            $ = new QosProfileClassBandwidthTypeArgs();
        }

        public Builder(QosProfileClassBandwidthTypeArgs defaults) {
            $ = new QosProfileClassBandwidthTypeArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param mbps Mbps
         * 
         * @return builder
         * 
         */
        public Builder mbps(@Nullable Output<QosProfileClassBandwidthTypeMbpsArgs> mbps) {
            $.mbps = mbps;
            return this;
        }

        /**
         * @param mbps Mbps
         * 
         * @return builder
         * 
         */
        public Builder mbps(QosProfileClassBandwidthTypeMbpsArgs mbps) {
            return mbps(Output.of(mbps));
        }

        /**
         * @param percentage Percentage
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `mbps` and `percentage`.
         * 
         * @return builder
         * 
         */
        public Builder percentage(@Nullable Output<QosProfileClassBandwidthTypePercentageArgs> percentage) {
            $.percentage = percentage;
            return this;
        }

        /**
         * @param percentage Percentage
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `mbps` and `percentage`.
         * 
         * @return builder
         * 
         */
        public Builder percentage(QosProfileClassBandwidthTypePercentageArgs percentage) {
            return percentage(Output.of(percentage));
        }

        public QosProfileClassBandwidthTypeArgs build() {
            return $;
        }
    }

}
