// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ScepProfileAlgorithmRsaArgs extends com.pulumi.resources.ResourceArgs {

    public static final ScepProfileAlgorithmRsaArgs Empty = new ScepProfileAlgorithmRsaArgs();

    /**
     * Rsa nbits
     * 
     */
    @Import(name="rsaNbits", required=true)
    private Output<String> rsaNbits;

    /**
     * @return Rsa nbits
     * 
     */
    public Output<String> rsaNbits() {
        return this.rsaNbits;
    }

    private ScepProfileAlgorithmRsaArgs() {}

    private ScepProfileAlgorithmRsaArgs(ScepProfileAlgorithmRsaArgs $) {
        this.rsaNbits = $.rsaNbits;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ScepProfileAlgorithmRsaArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ScepProfileAlgorithmRsaArgs $;

        public Builder() {
            $ = new ScepProfileAlgorithmRsaArgs();
        }

        public Builder(ScepProfileAlgorithmRsaArgs defaults) {
            $ = new ScepProfileAlgorithmRsaArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param rsaNbits Rsa nbits
         * 
         * @return builder
         * 
         */
        public Builder rsaNbits(Output<String> rsaNbits) {
            $.rsaNbits = rsaNbits;
            return this;
        }

        /**
         * @param rsaNbits Rsa nbits
         * 
         * @return builder
         * 
         */
        public Builder rsaNbits(String rsaNbits) {
            return rsaNbits(Output.of(rsaNbits));
        }

        public ScepProfileAlgorithmRsaArgs build() {
            if ($.rsaNbits == null) {
                throw new MissingRequiredPropertyException("ScepProfileAlgorithmRsaArgs", "rsaNbits");
            }
            return $;
        }
    }

}
