// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.scm.inputs.TlsServiceProfileProtocolSettingsArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TlsServiceProfileState extends com.pulumi.resources.ResourceArgs {

    public static final TlsServiceProfileState Empty = new TlsServiceProfileState();

    /**
     * Certificate name
     * 
     */
    @Import(name="certificate")
    private @Nullable Output<String> certificate;

    /**
     * @return Certificate name
     * 
     */
    public Optional<Output<String>> certificate() {
        return Optional.ofNullable(this.certificate);
    }

    /**
     * The device in which the resource is defined
     * 
     */
    @Import(name="device")
    private @Nullable Output<String> device;

    /**
     * @return The device in which the resource is defined
     * 
     */
    public Optional<Output<String>> device() {
        return Optional.ofNullable(this.device);
    }

    /**
     * The folder in which the resource is defined
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    @Import(name="folder")
    private @Nullable Output<String> folder;

    /**
     * @return The folder in which the resource is defined
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    public Optional<Output<String>> folder() {
        return Optional.ofNullable(this.folder);
    }

    /**
     * TLS service profile name. The value is `muCustomDomainSSLProfile` when it is used on mobile-agent infra settings.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return TLS service profile name. The value is `muCustomDomainSSLProfile` when it is used on mobile-agent infra settings.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Protocol settings
     * 
     */
    @Import(name="protocolSettings")
    private @Nullable Output<TlsServiceProfileProtocolSettingsArgs> protocolSettings;

    /**
     * @return Protocol settings
     * 
     */
    public Optional<Output<TlsServiceProfileProtocolSettingsArgs>> protocolSettings() {
        return Optional.ofNullable(this.protocolSettings);
    }

    /**
     * The snippet in which the resource is defined
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    @Import(name="snippet")
    private @Nullable Output<String> snippet;

    /**
     * @return The snippet in which the resource is defined
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    public Optional<Output<String>> snippet() {
        return Optional.ofNullable(this.snippet);
    }

    @Import(name="tfid")
    private @Nullable Output<String> tfid;

    public Optional<Output<String>> tfid() {
        return Optional.ofNullable(this.tfid);
    }

    private TlsServiceProfileState() {}

    private TlsServiceProfileState(TlsServiceProfileState $) {
        this.certificate = $.certificate;
        this.device = $.device;
        this.folder = $.folder;
        this.name = $.name;
        this.protocolSettings = $.protocolSettings;
        this.snippet = $.snippet;
        this.tfid = $.tfid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TlsServiceProfileState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TlsServiceProfileState $;

        public Builder() {
            $ = new TlsServiceProfileState();
        }

        public Builder(TlsServiceProfileState defaults) {
            $ = new TlsServiceProfileState(Objects.requireNonNull(defaults));
        }

        /**
         * @param certificate Certificate name
         * 
         * @return builder
         * 
         */
        public Builder certificate(@Nullable Output<String> certificate) {
            $.certificate = certificate;
            return this;
        }

        /**
         * @param certificate Certificate name
         * 
         * @return builder
         * 
         */
        public Builder certificate(String certificate) {
            return certificate(Output.of(certificate));
        }

        /**
         * @param device The device in which the resource is defined
         * 
         * @return builder
         * 
         */
        public Builder device(@Nullable Output<String> device) {
            $.device = device;
            return this;
        }

        /**
         * @param device The device in which the resource is defined
         * 
         * @return builder
         * 
         */
        public Builder device(String device) {
            return device(Output.of(device));
        }

        /**
         * @param folder The folder in which the resource is defined
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
         * 
         * @return builder
         * 
         */
        public Builder folder(@Nullable Output<String> folder) {
            $.folder = folder;
            return this;
        }

        /**
         * @param folder The folder in which the resource is defined
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
         * 
         * @return builder
         * 
         */
        public Builder folder(String folder) {
            return folder(Output.of(folder));
        }

        /**
         * @param name TLS service profile name. The value is `muCustomDomainSSLProfile` when it is used on mobile-agent infra settings.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name TLS service profile name. The value is `muCustomDomainSSLProfile` when it is used on mobile-agent infra settings.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param protocolSettings Protocol settings
         * 
         * @return builder
         * 
         */
        public Builder protocolSettings(@Nullable Output<TlsServiceProfileProtocolSettingsArgs> protocolSettings) {
            $.protocolSettings = protocolSettings;
            return this;
        }

        /**
         * @param protocolSettings Protocol settings
         * 
         * @return builder
         * 
         */
        public Builder protocolSettings(TlsServiceProfileProtocolSettingsArgs protocolSettings) {
            return protocolSettings(Output.of(protocolSettings));
        }

        /**
         * @param snippet The snippet in which the resource is defined
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
         * 
         * @return builder
         * 
         */
        public Builder snippet(@Nullable Output<String> snippet) {
            $.snippet = snippet;
            return this;
        }

        /**
         * @param snippet The snippet in which the resource is defined
         * 
         * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
         * 
         * @return builder
         * 
         */
        public Builder snippet(String snippet) {
            return snippet(Output.of(snippet));
        }

        public Builder tfid(@Nullable Output<String> tfid) {
            $.tfid = tfid;
            return this;
        }

        public Builder tfid(String tfid) {
            return tfid(Output.of(tfid));
        }

        public TlsServiceProfileState build() {
            return $;
        }
    }

}
