// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class AuthenticationProfileMethod
    {
        /// <summary>
        /// Cloud
        /// </summary>
        public readonly Outputs.AuthenticationProfileMethodCloud? Cloud;
        /// <summary>
        /// Kerberos
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Cloud`, `Kerberos`, `Ldap`, `LocalDatabase`, `Radius`, `SamlIdp`, and `Tacplus`.
        /// </summary>
        public readonly Outputs.AuthenticationProfileMethodKerberos? Kerberos;
        /// <summary>
        /// Ldap
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Cloud`, `Kerberos`, `Ldap`, `LocalDatabase`, `Radius`, `SamlIdp`, and `Tacplus`.
        /// </summary>
        public readonly Outputs.AuthenticationProfileMethodLdap? Ldap;
        /// <summary>
        /// Local database
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Cloud`, `Kerberos`, `Ldap`, `LocalDatabase`, `Radius`, `SamlIdp`, and `Tacplus`.
        /// </summary>
        public readonly Outputs.AuthenticationProfileMethodLocalDatabase? LocalDatabase;
        /// <summary>
        /// Radius
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Cloud`, `Kerberos`, `Ldap`, `LocalDatabase`, `Radius`, `SamlIdp`, and `Tacplus`.
        /// </summary>
        public readonly Outputs.AuthenticationProfileMethodRadius? Radius;
        /// <summary>
        /// Saml idp
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Cloud`, `Kerberos`, `Ldap`, `LocalDatabase`, `Radius`, `SamlIdp`, and `Tacplus`.
        /// </summary>
        public readonly Outputs.AuthenticationProfileMethodSamlIdp? SamlIdp;
        /// <summary>
        /// Tacplus
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Cloud`, `Kerberos`, `Ldap`, `LocalDatabase`, `Radius`, `SamlIdp`, and `Tacplus`.
        /// </summary>
        public readonly Outputs.AuthenticationProfileMethodTacplus? Tacplus;

        [OutputConstructor]
        private AuthenticationProfileMethod(
            Outputs.AuthenticationProfileMethodCloud? cloud,

            Outputs.AuthenticationProfileMethodKerberos? kerberos,

            Outputs.AuthenticationProfileMethodLdap? ldap,

            Outputs.AuthenticationProfileMethodLocalDatabase? localDatabase,

            Outputs.AuthenticationProfileMethodRadius? radius,

            Outputs.AuthenticationProfileMethodSamlIdp? samlIdp,

            Outputs.AuthenticationProfileMethodTacplus? tacplus)
        {
            Cloud = cloud;
            Kerberos = kerberos;
            Ldap = ldap;
            LocalDatabase = localDatabase;
            Radius = radius;
            SamlIdp = samlIdp;
            Tacplus = tacplus;
        }
    }
}
