// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class BgpRouteMapRedistributionOspfRibRouteMap
    {
        /// <summary>
        /// Action
        /// </summary>
        public readonly string? Action;
        /// <summary>
        /// Description
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// Match
        /// </summary>
        public readonly Outputs.BgpRouteMapRedistributionOspfRibRouteMapMatch? Match;
        /// <summary>
        /// Sequence number
        /// </summary>
        public readonly int? Name;
        /// <summary>
        /// Set
        /// </summary>
        public readonly Outputs.BgpRouteMapRedistributionOspfRibRouteMapSet? Set;

        [OutputConstructor]
        private BgpRouteMapRedistributionOspfRibRouteMap(
            string? action,

            string? description,

            Outputs.BgpRouteMapRedistributionOspfRibRouteMapMatch? match,

            int? name,

            Outputs.BgpRouteMapRedistributionOspfRibRouteMapSet? set)
        {
            Action = action;
            Description = description;
            Match = match;
            Name = name;
            Set = set;
        }
    }
}
