// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetAuthenticationRuleListDataResult
    {
        /// <summary>
        /// the authentication profile name to apply to authentication rule.
        /// </summary>
        public readonly string AuthenticationEnforcement;
        /// <summary>
        /// The Categories param.
        /// </summary>
        public readonly ImmutableArray<string> Categories;
        /// <summary>
        /// The Description param.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The DestinationHips param.
        /// </summary>
        public readonly ImmutableArray<string> DestinationHips;
        /// <summary>
        /// The Destinations param.
        /// </summary>
        public readonly ImmutableArray<string> Destinations;
        /// <summary>
        /// The Disabled param. Default: `false`.
        /// </summary>
        public readonly bool Disabled;
        /// <summary>
        /// The Froms param.
        /// </summary>
        public readonly ImmutableArray<string> Froms;
        /// <summary>
        /// The GroupTag param.
        /// </summary>
        public readonly string GroupTag;
        /// <summary>
        /// The HipProfiles param.
        /// </summary>
        public readonly ImmutableArray<string> HipProfiles;
        /// <summary>
        /// UUID of the resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The LogAuthenticationTimeout param. Default: `false`.
        /// </summary>
        public readonly bool LogAuthenticationTimeout;
        /// <summary>
        /// The LogSetting param.
        /// </summary>
        public readonly string LogSetting;
        /// <summary>
        /// The Name param.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The NegateDestination param. Default: `false`.
        /// </summary>
        public readonly bool NegateDestination;
        /// <summary>
        /// The NegateSource param. Default: `false`.
        /// </summary>
        public readonly bool NegateSource;
        /// <summary>
        /// The Services param.
        /// </summary>
        public readonly ImmutableArray<string> Services;
        /// <summary>
        /// The SourceHips param.
        /// </summary>
        public readonly ImmutableArray<string> SourceHips;
        /// <summary>
        /// The SourceUsers param.
        /// </summary>
        public readonly ImmutableArray<string> SourceUsers;
        /// <summary>
        /// The Sources param.
        /// </summary>
        public readonly ImmutableArray<string> Sources;
        /// <summary>
        /// The Tags param.
        /// </summary>
        public readonly ImmutableArray<string> Tags;
        /// <summary>
        /// The Timeout param. Value must be between 1 and 1440.
        /// </summary>
        public readonly int Timeout;
        /// <summary>
        /// The Tos param.
        /// </summary>
        public readonly ImmutableArray<string> Tos;

        [OutputConstructor]
        private GetAuthenticationRuleListDataResult(
            string authenticationEnforcement,

            ImmutableArray<string> categories,

            string description,

            ImmutableArray<string> destinationHips,

            ImmutableArray<string> destinations,

            bool disabled,

            ImmutableArray<string> froms,

            string groupTag,

            ImmutableArray<string> hipProfiles,

            string id,

            bool logAuthenticationTimeout,

            string logSetting,

            string name,

            bool negateDestination,

            bool negateSource,

            ImmutableArray<string> services,

            ImmutableArray<string> sourceHips,

            ImmutableArray<string> sourceUsers,

            ImmutableArray<string> sources,

            ImmutableArray<string> tags,

            int timeout,

            ImmutableArray<string> tos)
        {
            AuthenticationEnforcement = authenticationEnforcement;
            Categories = categories;
            Description = description;
            DestinationHips = destinationHips;
            Destinations = destinations;
            Disabled = disabled;
            Froms = froms;
            GroupTag = groupTag;
            HipProfiles = hipProfiles;
            Id = id;
            LogAuthenticationTimeout = logAuthenticationTimeout;
            LogSetting = logSetting;
            Name = name;
            NegateDestination = negateDestination;
            NegateSource = negateSource;
            Services = services;
            SourceHips = sourceHips;
            SourceUsers = sourceUsers;
            Sources = sources;
            Tags = tags;
            Timeout = timeout;
            Tos = tos;
        }
    }
}
