// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetBgpRoutingRoutingPreferenceResult
    {
        /// <summary>
        /// Default
        /// </summary>
        public readonly Outputs.GetBgpRoutingRoutingPreferenceDefaultResult Default;
        /// <summary>
        /// Hot potato routing
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Default` and `HotPotatoRouting`.
        /// </summary>
        public readonly Outputs.GetBgpRoutingRoutingPreferenceHotPotatoRoutingResult HotPotatoRouting;

        [OutputConstructor]
        private GetBgpRoutingRoutingPreferenceResult(
            Outputs.GetBgpRoutingRoutingPreferenceDefaultResult @default,

            Outputs.GetBgpRoutingRoutingPreferenceHotPotatoRoutingResult hotPotatoRouting)
        {
            Default = @default;
            HotPotatoRouting = hotPotatoRouting;
        }
    }
}
