// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetDosProtectionProfileFloodResult
    {
        /// <summary>
        /// Icmp
        /// </summary>
        public readonly Outputs.GetDosProtectionProfileFloodIcmpResult Icmp;
        /// <summary>
        /// Icmpv6
        /// </summary>
        public readonly Outputs.GetDosProtectionProfileFloodIcmpv6Result Icmpv6;
        /// <summary>
        /// Other ip
        /// </summary>
        public readonly Outputs.GetDosProtectionProfileFloodOtherIpResult OtherIp;
        /// <summary>
        /// Tcp syn
        /// </summary>
        public readonly Outputs.GetDosProtectionProfileFloodTcpSynResult TcpSyn;
        /// <summary>
        /// Udp
        /// </summary>
        public readonly Outputs.GetDosProtectionProfileFloodUdpResult Udp;

        [OutputConstructor]
        private GetDosProtectionProfileFloodResult(
            Outputs.GetDosProtectionProfileFloodIcmpResult icmp,

            Outputs.GetDosProtectionProfileFloodIcmpv6Result icmpv6,

            Outputs.GetDosProtectionProfileFloodOtherIpResult otherIp,

            Outputs.GetDosProtectionProfileFloodTcpSynResult tcpSyn,

            Outputs.GetDosProtectionProfileFloodUdpResult udp)
        {
            Icmp = icmp;
            Icmpv6 = icmpv6;
            OtherIp = otherIp;
            TcpSyn = tcpSyn;
            Udp = udp;
        }
    }
}
