// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetDataObjectPatternTypePredefinedPatternResult
    {
        /// <summary>
        /// File type
        /// </summary>
        public readonly ImmutableArray<string> FileTypes;
        /// <summary>
        /// Name
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetDataObjectPatternTypePredefinedPatternResult(
            ImmutableArray<string> fileTypes,

            string name)
        {
            FileTypes = fileTypes;
            Name = name;
        }
    }
}
