// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetFileBlockingProfileListDataResult
    {
        /// <summary>
        /// Description
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The device in which the resource is defined
        /// </summary>
        public readonly string Device;
        /// <summary>
        /// The folder of the item. Default: Shared.
        /// </summary>
        public readonly string Folder;
        /// <summary>
        /// The UUID of the file blocking profile
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the item.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// A list of file blocking rules
        /// </summary>
        public readonly ImmutableArray<Outputs.GetFileBlockingProfileListDataRuleResult> Rules;
        /// <summary>
        /// The snippet of the item.
        /// </summary>
        public readonly string Snippet;
        /// <summary>
        /// The Terraform ID.
        /// </summary>
        public readonly string Tfid;

        [OutputConstructor]
        private GetFileBlockingProfileListDataResult(
            string description,

            string device,

            string folder,

            string id,

            string name,

            ImmutableArray<Outputs.GetFileBlockingProfileListDataRuleResult> rules,

            string snippet,

            string tfid)
        {
            Description = description;
            Device = device;
            Folder = folder;
            Id = id;
            Name = name;
            Rules = rules;
            Snippet = snippet;
            Tfid = tfid;
        }
    }
}
