// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetGeneralSettingListDataResult
    {
        /// <summary>
        /// The device in which the resource is defined
        /// </summary>
        public readonly string Device;
        /// <summary>
        /// The folder of the item. Default: Shared.
        /// </summary>
        public readonly string Folder;
        /// <summary>
        /// General
        /// </summary>
        public readonly Outputs.GetGeneralSettingListDataGeneralResult General;
        /// <summary>
        /// UUID of the resource
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The snippet of the item.
        /// </summary>
        public readonly string Snippet;
        /// <summary>
        /// The Terraform ID.
        /// </summary>
        public readonly string Tfid;

        [OutputConstructor]
        private GetGeneralSettingListDataResult(
            string device,

            string folder,

            Outputs.GetGeneralSettingListDataGeneralResult general,

            string id,

            string snippet,

            string tfid)
        {
            Device = device;
            Folder = folder;
            General = general;
            Id = id;
            Snippet = snippet;
            Tfid = tfid;
        }
    }
}
