// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetIpsecTunnelListDataAutoKeyProxyIdProtocolResult
    {
        /// <summary>
        /// IP protocol number
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Number`, `Tcp`, and `Udp`.
        /// </summary>
        public readonly int Number;
        /// <summary>
        /// IPv4 type of proxy*id protocol values for TCP protocol
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Number`, `Tcp`, and `Udp`.
        /// </summary>
        public readonly Outputs.GetIpsecTunnelListDataAutoKeyProxyIdProtocolTcpResult Tcp;
        /// <summary>
        /// IPv6 type of proxy*id protocol values for UDP protocol
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Number`, `Tcp`, and `Udp`.
        /// </summary>
        public readonly Outputs.GetIpsecTunnelListDataAutoKeyProxyIdProtocolUdpResult Udp;

        [OutputConstructor]
        private GetIpsecTunnelListDataAutoKeyProxyIdProtocolResult(
            int number,

            Outputs.GetIpsecTunnelListDataAutoKeyProxyIdProtocolTcpResult tcp,

            Outputs.GetIpsecTunnelListDataAutoKeyProxyIdProtocolUdpResult udp)
        {
            Number = number;
            Tcp = tcp;
            Udp = udp;
        }
    }
}
