// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetIkeGatewayListDataProtocolIkev1Result
    {
        /// <summary>
        /// Dpd
        /// </summary>
        public readonly Outputs.GetIkeGatewayListDataProtocolIkev1DpdResult Dpd;
        /// <summary>
        /// Ike crypto profile
        /// </summary>
        public readonly string IkeCryptoProfile;

        [OutputConstructor]
        private GetIkeGatewayListDataProtocolIkev1Result(
            Outputs.GetIkeGatewayListDataProtocolIkev1DpdResult dpd,

            string ikeCryptoProfile)
        {
            Dpd = dpd;
            IkeCryptoProfile = ikeCryptoProfile;
        }
    }
}
