// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetIpsecTunnelListDataResult
    {
        /// <summary>
        /// Enable Anti-Replay check on this tunnel
        /// </summary>
        public readonly bool AntiReplay;
        /// <summary>
        /// Auto key
        /// </summary>
        public readonly Outputs.GetIpsecTunnelListDataAutoKeyResult AutoKey;
        /// <summary>
        /// Copy IP TOS bits from inner packet to IPSec packet (not recommended)
        /// </summary>
        public readonly bool CopyTos;
        /// <summary>
        /// The device in which the resource is defined
        /// </summary>
        public readonly string Device;
        /// <summary>
        /// allow GRE over IPSec
        /// </summary>
        public readonly bool EnableGreEncapsulation;
        /// <summary>
        /// The folder of the item. Default: Shared.
        /// </summary>
        public readonly string Folder;
        /// <summary>
        /// UUID of the resource
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the item.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The snippet of the item.
        /// </summary>
        public readonly string Snippet;
        /// <summary>
        /// The Terraform ID.
        /// </summary>
        public readonly string Tfid;
        /// <summary>
        /// Tunnel interface variable or hardcoded tunnel. Default will be tunnels.
        /// </summary>
        public readonly string TunnelInterface;
        /// <summary>
        /// Tunnel monitor
        /// </summary>
        public readonly Outputs.GetIpsecTunnelListDataTunnelMonitorResult TunnelMonitor;

        [OutputConstructor]
        private GetIpsecTunnelListDataResult(
            bool antiReplay,

            Outputs.GetIpsecTunnelListDataAutoKeyResult autoKey,

            bool copyTos,

            string device,

            bool enableGreEncapsulation,

            string folder,

            string id,

            string name,

            string snippet,

            string tfid,

            string tunnelInterface,

            Outputs.GetIpsecTunnelListDataTunnelMonitorResult tunnelMonitor)
        {
            AntiReplay = antiReplay;
            AutoKey = autoKey;
            CopyTos = copyTos;
            Device = device;
            EnableGreEncapsulation = enableGreEncapsulation;
            Folder = folder;
            Id = id;
            Name = name;
            Snippet = snippet;
            Tfid = tfid;
            TunnelInterface = tunnelInterface;
            TunnelMonitor = tunnelMonitor;
        }
    }
}
