// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetLayer3SubinterfacePppoeStaticAddressResult
    {
        /// <summary>
        /// Static IP address
        /// </summary>
        public readonly string Ip;

        [OutputConstructor]
        private GetLayer3SubinterfacePppoeStaticAddressResult(string ip)
        {
            Ip = ip;
        }
    }
}
