// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetLogicalRouterVrfOspfv3AreaTypeNormalResult
    {
        /// <summary>
        /// Abr
        /// </summary>
        public readonly Outputs.GetLogicalRouterVrfOspfv3AreaTypeNormalAbrResult Abr;

        [OutputConstructor]
        private GetLogicalRouterVrfOspfv3AreaTypeNormalResult(Outputs.GetLogicalRouterVrfOspfv3AreaTypeNormalAbrResult abr)
        {
            Abr = abr;
        }
    }
}
