// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetLogicalRouterListDataVrfRoutingTableIpStaticRouteNexthopResult
    {
        /// <summary>
        /// Discard
        /// </summary>
        public readonly Outputs.GetLogicalRouterListDataVrfRoutingTableIpStaticRouteNexthopDiscardResult Discard;
        /// <summary>
        /// Fqdn
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Discard`, `Fqdn`, `IpAddress`, `Ipv6Address`, `NextLr`, `NextVr`, `Receive`, and `Tunnel`.
        /// </summary>
        public readonly string Fqdn;
        /// <summary>
        /// Ip address
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Discard`, `Fqdn`, `IpAddress`, `Ipv6Address`, `NextLr`, `NextVr`, `Receive`, and `Tunnel`.
        /// </summary>
        public readonly string IpAddress;
        /// <summary>
        /// Ipv6 address
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Discard`, `Fqdn`, `IpAddress`, `Ipv6Address`, `NextLr`, `NextVr`, `Receive`, and `Tunnel`.
        /// </summary>
        public readonly string Ipv6Address;
        /// <summary>
        /// Next lr
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Discard`, `Fqdn`, `IpAddress`, `Ipv6Address`, `NextLr`, `NextVr`, `Receive`, and `Tunnel`.
        /// </summary>
        public readonly string NextLr;
        /// <summary>
        /// Next vr
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Discard`, `Fqdn`, `IpAddress`, `Ipv6Address`, `NextLr`, `NextVr`, `Receive`, and `Tunnel`.
        /// </summary>
        public readonly string NextVr;
        /// <summary>
        /// Receive
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Discard`, `Fqdn`, `IpAddress`, `Ipv6Address`, `NextLr`, `NextVr`, `Receive`, and `Tunnel`.
        /// </summary>
        public readonly Outputs.GetLogicalRouterListDataVrfRoutingTableIpStaticRouteNexthopReceiveResult Receive;
        /// <summary>
        /// Tunnel
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Discard`, `Fqdn`, `IpAddress`, `Ipv6Address`, `NextLr`, `NextVr`, `Receive`, and `Tunnel`.
        /// </summary>
        public readonly string Tunnel;

        [OutputConstructor]
        private GetLogicalRouterListDataVrfRoutingTableIpStaticRouteNexthopResult(
            Outputs.GetLogicalRouterListDataVrfRoutingTableIpStaticRouteNexthopDiscardResult discard,

            string fqdn,

            string ipAddress,

            string ipv6Address,

            string nextLr,

            string nextVr,

            Outputs.GetLogicalRouterListDataVrfRoutingTableIpStaticRouteNexthopReceiveResult receive,

            string tunnel)
        {
            Discard = discard;
            Fqdn = fqdn;
            IpAddress = ipAddress;
            Ipv6Address = ipv6Address;
            NextLr = nextLr;
            NextVr = nextVr;
            Receive = receive;
            Tunnel = tunnel;
        }
    }
}
