// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetRemoteNetworkEcmpTunnelResult
    {
        /// <summary>
        /// Ipsec tunnel
        /// </summary>
        public readonly string IpsecTunnel;
        /// <summary>
        /// Name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Protocol
        /// </summary>
        public readonly Outputs.GetRemoteNetworkEcmpTunnelProtocolResult Protocol;

        [OutputConstructor]
        private GetRemoteNetworkEcmpTunnelResult(
            string ipsecTunnel,

            string name,

            Outputs.GetRemoteNetworkEcmpTunnelProtocolResult protocol)
        {
            IpsecTunnel = ipsecTunnel;
            Name = name;
            Protocol = protocol;
        }
    }
}
