// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetRoutePrefixListIpv4Result
    {
        /// <summary>
        /// IPv4 prefix lists
        /// </summary>
        public readonly ImmutableArray<Outputs.GetRoutePrefixListIpv4Ipv4EntryResult> Ipv4Entries;

        [OutputConstructor]
        private GetRoutePrefixListIpv4Result(ImmutableArray<Outputs.GetRoutePrefixListIpv4Ipv4EntryResult> ipv4Entries)
        {
            Ipv4Entries = ipv4Entries;
        }
    }
}
