// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetServiceSettingListDataResult
    {
        /// <summary>
        /// The device in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        public readonly string Device;
        /// <summary>
        /// Map of sensitive values returned from the API.
        /// </summary>
        public readonly ImmutableDictionary<string, string> EncryptedValues;
        /// <summary>
        /// The folder in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        public readonly string Folder;
        /// <summary>
        /// UUID of the resource
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Services
        /// </summary>
        public readonly Outputs.GetServiceSettingListDataServicesResult Services;
        /// <summary>
        /// The snippet in which the resource is defined
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Device`, `Folder`, and `Snippet`.
        /// </summary>
        public readonly string Snippet;
        public readonly string Tfid;

        [OutputConstructor]
        private GetServiceSettingListDataResult(
            string device,

            ImmutableDictionary<string, string> encryptedValues,

            string folder,

            string id,

            Outputs.GetServiceSettingListDataServicesResult services,

            string snippet,

            string tfid)
        {
            Device = device;
            EncryptedValues = encryptedValues;
            Folder = folder;
            Id = id;
            Services = services;
            Snippet = snippet;
            Tfid = tfid;
        }
    }
}
