// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class GetUrlAccessProfileListDataCredentialEnforcementModeResult
    {
        /// <summary>
        /// Disabled
        /// </summary>
        public readonly Outputs.GetUrlAccessProfileListDataCredentialEnforcementModeDisabledResult Disabled;
        /// <summary>
        /// Domain credentials
        /// </summary>
        public readonly Outputs.GetUrlAccessProfileListDataCredentialEnforcementModeDomainCredentialsResult DomainCredentials;
        /// <summary>
        /// Group mapping
        /// </summary>
        public readonly string GroupMapping;
        /// <summary>
        /// Ip user
        /// </summary>
        public readonly Outputs.GetUrlAccessProfileListDataCredentialEnforcementModeIpUserResult IpUser;

        [OutputConstructor]
        private GetUrlAccessProfileListDataCredentialEnforcementModeResult(
            Outputs.GetUrlAccessProfileListDataCredentialEnforcementModeDisabledResult disabled,

            Outputs.GetUrlAccessProfileListDataCredentialEnforcementModeDomainCredentialsResult domainCredentials,

            string groupMapping,

            Outputs.GetUrlAccessProfileListDataCredentialEnforcementModeIpUserResult ipUser)
        {
            Disabled = disabled;
            DomainCredentials = domainCredentials;
            GroupMapping = groupMapping;
            IpUser = ipUser;
        }
    }
}
