// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Outputs
{

    [OutputType]
    public sealed class ScheduleScheduleTypeRecurringWeekly
    {
        /// <summary>
        /// The FridayList param. Individual elements in this list are subject to additional validation. String length must be between 11 and 11 characters. String validation regex: `([01][0-9]|[2][0-3]):([0-5][0-9])-([01][0-9]|[2][0-3]):([0-5][0-9])`.
        /// </summary>
        public readonly ImmutableArray<string> FridayLists;
        /// <summary>
        /// The MondayList param. Individual elements in this list are subject to additional validation. String length must be between 11 and 11 characters. String validation regex: `([01][0-9]|[2][0-3]):([0-5][0-9])-([01][0-9]|[2][0-3]):([0-5][0-9])`.
        /// </summary>
        public readonly ImmutableArray<string> MondayLists;
        /// <summary>
        /// The SaturdayList param. Individual elements in this list are subject to additional validation. String length must be between 11 and 11 characters. String validation regex: `([01][0-9]|[2][0-3]):([0-5][0-9])-([01][0-9]|[2][0-3]):([0-5][0-9])`.
        /// </summary>
        public readonly ImmutableArray<string> SaturdayLists;
        /// <summary>
        /// The SundayList param. Individual elements in this list are subject to additional validation. String length must be between 11 and 11 characters. String validation regex: `([01][0-9]|[2][0-3]):([0-5][0-9])-([01][0-9]|[2][0-3]):([0-5][0-9])`.
        /// </summary>
        public readonly ImmutableArray<string> SundayLists;
        /// <summary>
        /// The ThursdayList param. Individual elements in this list are subject to additional validation. String length must be between 11 and 11 characters. String validation regex: `([01][0-9]|[2][0-3]):([0-5][0-9])-([01][0-9]|[2][0-3]):([0-5][0-9])`.
        /// </summary>
        public readonly ImmutableArray<string> ThursdayLists;
        /// <summary>
        /// The TuesdayList param. Individual elements in this list are subject to additional validation. String length must be between 11 and 11 characters. String validation regex: `([01][0-9]|[2][0-3]):([0-5][0-9])-([01][0-9]|[2][0-3]):([0-5][0-9])`.
        /// </summary>
        public readonly ImmutableArray<string> TuesdayLists;
        /// <summary>
        /// The WednesdayList param. Individual elements in this list are subject to additional validation. String length must be between 11 and 11 characters. String validation regex: `([01][0-9]|[2][0-3]):([0-5][0-9])-([01][0-9]|[2][0-3]):([0-5][0-9])`.
        /// </summary>
        public readonly ImmutableArray<string> WednesdayLists;

        [OutputConstructor]
        private ScheduleScheduleTypeRecurringWeekly(
            ImmutableArray<string> fridayLists,

            ImmutableArray<string> mondayLists,

            ImmutableArray<string> saturdayLists,

            ImmutableArray<string> sundayLists,

            ImmutableArray<string> thursdayLists,

            ImmutableArray<string> tuesdayLists,

            ImmutableArray<string> wednesdayLists)
        {
            FridayLists = fridayLists;
            MondayLists = mondayLists;
            SaturdayLists = saturdayLists;
            SundayLists = sundayLists;
            ThursdayLists = thursdayLists;
            TuesdayLists = tuesdayLists;
            WednesdayLists = wednesdayLists;
        }
    }
}
