// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.scm.HttpServerProfileArgs;
import com.pulumi.scm.Utilities;
import com.pulumi.scm.inputs.HttpServerProfileState;
import com.pulumi.scm.outputs.HttpServerProfileFormat;
import com.pulumi.scm.outputs.HttpServerProfileServer;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * HttpServerProfile resource
 * 
 * ## Import
 * 
 * The following command can be used to import a resource not managed by Terraform:
 * 
 * bash
 * 
 * ```sh
 * $ pulumi import scm:index/httpServerProfile:HttpServerProfile example folder:::id
 * ```
 * 
 * or
 * 
 * bash
 * 
 * ```sh
 * $ pulumi import scm:index/httpServerProfile:HttpServerProfile example :snippet::id
 * ```
 * 
 * or
 * 
 * bash
 * 
 * ```sh
 * $ pulumi import scm:index/httpServerProfile:HttpServerProfile example ::device:id
 * ```
 * 
 */
@ResourceType(type="scm:index/httpServerProfile:HttpServerProfile")
public class HttpServerProfile extends com.pulumi.resources.CustomResource {
    /**
     * The device in which the resource is defined
     * 
     */
    @Export(name="device", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> device;

    /**
     * @return The device in which the resource is defined
     * 
     */
    public Output<Optional<String>> device() {
        return Codegen.optional(this.device);
    }
    /**
     * The folder in which the resource is defined
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    @Export(name="folder", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> folder;

    /**
     * @return The folder in which the resource is defined
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    public Output<Optional<String>> folder() {
        return Codegen.optional(this.folder);
    }
    /**
     * Format
     * 
     */
    @Export(name="format", refs={HttpServerProfileFormat.class}, tree="[0]")
    private Output</* @Nullable */ HttpServerProfileFormat> format;

    /**
     * @return Format
     * 
     */
    public Output<Optional<HttpServerProfileFormat>> format() {
        return Codegen.optional(this.format);
    }
    /**
     * The name of the profile
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the profile
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Server
     * 
     */
    @Export(name="servers", refs={List.class,HttpServerProfileServer.class}, tree="[0,1]")
    private Output</* @Nullable */ List<HttpServerProfileServer>> servers;

    /**
     * @return Server
     * 
     */
    public Output<Optional<List<HttpServerProfileServer>>> servers() {
        return Codegen.optional(this.servers);
    }
    /**
     * The snippet in which the resource is defined
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    @Export(name="snippet", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> snippet;

    /**
     * @return The snippet in which the resource is defined
     * 
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    public Output<Optional<String>> snippet() {
        return Codegen.optional(this.snippet);
    }
    /**
     * Register tags on match
     * 
     */
    @Export(name="tagRegistration", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> tagRegistration;

    /**
     * @return Register tags on match
     * 
     */
    public Output<Optional<Boolean>> tagRegistration() {
        return Codegen.optional(this.tagRegistration);
    }
    @Export(name="tfid", refs={String.class}, tree="[0]")
    private Output<String> tfid;

    public Output<String> tfid() {
        return this.tfid;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public HttpServerProfile(java.lang.String name) {
        this(name, HttpServerProfileArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public HttpServerProfile(java.lang.String name, @Nullable HttpServerProfileArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public HttpServerProfile(java.lang.String name, @Nullable HttpServerProfileArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("scm:index/httpServerProfile:HttpServerProfile", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private HttpServerProfile(java.lang.String name, Output<java.lang.String> id, @Nullable HttpServerProfileState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("scm:index/httpServerProfile:HttpServerProfile", name, state, makeResourceOptions(options, id), false);
    }

    private static HttpServerProfileArgs makeArgs(@Nullable HttpServerProfileArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? HttpServerProfileArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static HttpServerProfile get(java.lang.String name, Output<java.lang.String> id, @Nullable HttpServerProfileState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new HttpServerProfile(name, id, state, options);
    }
}
