// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.scm.NatRuleArgs;
import com.pulumi.scm.Utilities;
import com.pulumi.scm.inputs.NatRuleState;
import com.pulumi.scm.outputs.NatRuleDestinationTranslation;
import com.pulumi.scm.outputs.NatRuleDynamicDestinationTranslation;
import com.pulumi.scm.outputs.NatRuleSourceTranslation;
import com.pulumi.scm.outputs.NatRuleTarget;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Retrieves a config item.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.scm.NatRule;
 * import com.pulumi.scm.NatRuleArgs;
 * import com.pulumi.scm.inputs.NatRuleSourceTranslationArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new NatRule("example", NatRuleArgs.builder()
 *             .folder("folder1")
 *             .name("example_nat1")
 *             .description("Example source nat")
 *             .sources("10.10.10.10/24")
 *             .froms("any")
 *             .tos("untrust")
 *             .sourceTranslation(NatRuleSourceTranslationArgs.builder()
 *                 .translated_address_single("192.168.10.100")
 *                 .bi_directional("no")
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
@ResourceType(type="scm:index/natRule:NatRule")
public class NatRule extends com.pulumi.resources.CustomResource {
    /**
     * The ActiveActiveDeviceBinding param. String must be one of these: `&#34;primary&#34;`, `&#34;both&#34;`, `&#34;0&#34;`, `&#34;1&#34;`.
     * 
     */
    @Export(name="activeActiveDeviceBinding", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> activeActiveDeviceBinding;

    /**
     * @return The ActiveActiveDeviceBinding param. String must be one of these: `&#34;primary&#34;`, `&#34;both&#34;`, `&#34;0&#34;`, `&#34;1&#34;`.
     * 
     */
    public Output<Optional<String>> activeActiveDeviceBinding() {
        return Codegen.optional(this.activeActiveDeviceBinding);
    }
    /**
     * The Description param.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return The Description param.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Static destination translation parameter.
     * 
     */
    @Export(name="destinationTranslation", refs={NatRuleDestinationTranslation.class}, tree="[0]")
    private Output</* @Nullable */ NatRuleDestinationTranslation> destinationTranslation;

    /**
     * @return Static destination translation parameter.
     * 
     */
    public Output<Optional<NatRuleDestinationTranslation>> destinationTranslation() {
        return Codegen.optional(this.destinationTranslation);
    }
    /**
     * The destination address(es). Individual elements in this list are subject to additional validation. String must be one of these: `&#34;any&#34;`.
     * 
     */
    @Export(name="destinations", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> destinations;

    /**
     * @return The destination address(es). Individual elements in this list are subject to additional validation. String must be one of these: `&#34;any&#34;`.
     * 
     */
    public Output<List<String>> destinations() {
        return this.destinations;
    }
    /**
     * The device in which the resource is defined. String length must not exceed 64 characters. String validation regex: `^[a-zA-Z\d-_\. ]+$`.
     * 
     */
    @Export(name="device", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> device;

    /**
     * @return The device in which the resource is defined. String length must not exceed 64 characters. String validation regex: `^[a-zA-Z\d-_\. ]+$`.
     * 
     */
    public Output<Optional<String>> device() {
        return Codegen.optional(this.device);
    }
    /**
     * The Disabled param.
     * 
     */
    @Export(name="disabled", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> disabled;

    /**
     * @return The Disabled param.
     * 
     */
    public Output<Optional<Boolean>> disabled() {
        return Codegen.optional(this.disabled);
    }
    /**
     * Dynamic destination translation parameter.
     * 
     */
    @Export(name="dynamicDestinationTranslation", refs={NatRuleDynamicDestinationTranslation.class}, tree="[0]")
    private Output</* @Nullable */ NatRuleDynamicDestinationTranslation> dynamicDestinationTranslation;

    /**
     * @return Dynamic destination translation parameter.
     * 
     */
    public Output<Optional<NatRuleDynamicDestinationTranslation>> dynamicDestinationTranslation() {
        return Codegen.optional(this.dynamicDestinationTranslation);
    }
    /**
     * The folder in which the resource is defined. String length must not exceed 64 characters. String validation regex: `^[a-zA-Z\d-_\. ]+$`.
     * 
     */
    @Export(name="folder", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> folder;

    /**
     * @return The folder in which the resource is defined. String length must not exceed 64 characters. String validation regex: `^[a-zA-Z\d-_\. ]+$`.
     * 
     */
    public Output<Optional<String>> folder() {
        return Codegen.optional(this.folder);
    }
    /**
     * The source security zone(s). Individual elements in this list are subject to additional validation. String must be one of these: `&#34;any&#34;`.
     * 
     */
    @Export(name="froms", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> froms;

    /**
     * @return The source security zone(s). Individual elements in this list are subject to additional validation. String must be one of these: `&#34;any&#34;`.
     * 
     */
    public Output<List<String>> froms() {
        return this.froms;
    }
    /**
     * The GroupTag param.
     * 
     */
    @Export(name="groupTag", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> groupTag;

    /**
     * @return The GroupTag param.
     * 
     */
    public Output<Optional<String>> groupTag() {
        return Codegen.optional(this.groupTag);
    }
    /**
     * The Name param.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The Name param.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The NatType param. String must be one of these: `&#34;ipv4&#34;`, `&#34;nat64&#34;`, `&#34;nptv6&#34;`.
     * 
     */
    @Export(name="natType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> natType;

    /**
     * @return The NatType param. String must be one of these: `&#34;ipv4&#34;`, `&#34;nat64&#34;`, `&#34;nptv6&#34;`.
     * 
     */
    public Output<Optional<String>> natType() {
        return Codegen.optional(this.natType);
    }
    /**
     * The Position param. String must be one of these: `&#34;pre&#34;`, `&#34;post&#34;`. Default: `&#34;pre&#34;`.
     * 
     */
    @Export(name="position", refs={String.class}, tree="[0]")
    private Output<String> position;

    /**
     * @return The Position param. String must be one of these: `&#34;pre&#34;`, `&#34;post&#34;`. Default: `&#34;pre&#34;`.
     * 
     */
    public Output<String> position() {
        return this.position;
    }
    /**
     * The Service param.
     * 
     */
    @Export(name="service", refs={String.class}, tree="[0]")
    private Output<String> service;

    /**
     * @return The Service param.
     * 
     */
    public Output<String> service() {
        return this.service;
    }
    /**
     * The snippet in which the resource is defined. String length must not exceed 64 characters. String validation regex: `^[a-zA-Z\d-_\. ]+$`.
     * 
     */
    @Export(name="snippet", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> snippet;

    /**
     * @return The snippet in which the resource is defined. String length must not exceed 64 characters. String validation regex: `^[a-zA-Z\d-_\. ]+$`.
     * 
     */
    public Output<Optional<String>> snippet() {
        return Codegen.optional(this.snippet);
    }
    /**
     * The SourceTranslation param.
     * 
     */
    @Export(name="sourceTranslation", refs={NatRuleSourceTranslation.class}, tree="[0]")
    private Output</* @Nullable */ NatRuleSourceTranslation> sourceTranslation;

    /**
     * @return The SourceTranslation param.
     * 
     */
    public Output<Optional<NatRuleSourceTranslation>> sourceTranslation() {
        return Codegen.optional(this.sourceTranslation);
    }
    /**
     * The source address(es). Individual elements in this list are subject to additional validation. String must be one of these: `&#34;any&#34;`.
     * 
     */
    @Export(name="sources", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> sources;

    /**
     * @return The source address(es). Individual elements in this list are subject to additional validation. String must be one of these: `&#34;any&#34;`.
     * 
     */
    public Output<List<String>> sources() {
        return this.sources;
    }
    /**
     * The Tags param.
     * 
     */
    @Export(name="tags", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> tags;

    /**
     * @return The Tags param.
     * 
     */
    public Output<Optional<List<String>>> tags() {
        return Codegen.optional(this.tags);
    }
    /**
     * The Target param.
     * 
     */
    @Export(name="target", refs={NatRuleTarget.class}, tree="[0]")
    private Output</* @Nullable */ NatRuleTarget> target;

    /**
     * @return The Target param.
     * 
     */
    public Output<Optional<NatRuleTarget>> target() {
        return Codegen.optional(this.target);
    }
    @Export(name="tfid", refs={String.class}, tree="[0]")
    private Output<String> tfid;

    public Output<String> tfid() {
        return this.tfid;
    }
    /**
     * The ToInterface param. String must be one of these: `&#34;any&#34;`.
     * 
     */
    @Export(name="toInterface", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> toInterface;

    /**
     * @return The ToInterface param. String must be one of these: `&#34;any&#34;`.
     * 
     */
    public Output<Optional<String>> toInterface() {
        return Codegen.optional(this.toInterface);
    }
    /**
     * The destination security zone(s).
     * 
     */
    @Export(name="tos", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> tos;

    /**
     * @return The destination security zone(s).
     * 
     */
    public Output<List<String>> tos() {
        return this.tos;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public NatRule(String name) {
        this(name, NatRuleArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public NatRule(String name, NatRuleArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public NatRule(String name, NatRuleArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("scm:index/natRule:NatRule", name, args == null ? NatRuleArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private NatRule(String name, Output<String> id, @Nullable NatRuleState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("scm:index/natRule:NatRule", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static NatRule get(String name, Output<String> id, @Nullable NatRuleState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new NatRule(name, id, state, options);
    }
}
