// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.scm.inputs.RadiusServerProfileProtocolArgs;
import com.pulumi.scm.inputs.RadiusServerProfileServerArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RadiusServerProfileArgs extends com.pulumi.resources.ResourceArgs {

    public static final RadiusServerProfileArgs Empty = new RadiusServerProfileArgs();

    /**
     * The device in which the resource is defined
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    @Import(name="device")
    private @Nullable Output<String> device;

    /**
     * @return The device in which the resource is defined
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    public Optional<Output<String>> device() {
        return Optional.ofNullable(this.device);
    }

    /**
     * The folder in which the resource is defined
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    @Import(name="folder")
    private @Nullable Output<String> folder;

    /**
     * @return The folder in which the resource is defined
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    public Optional<Output<String>> folder() {
        return Optional.ofNullable(this.folder);
    }

    /**
     * The name of the RADIUS server profile
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the RADIUS server profile
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The RADIUS authentication protocol
     * 
     */
    @Import(name="protocol", required=true)
    private Output<RadiusServerProfileProtocolArgs> protocol;

    /**
     * @return The RADIUS authentication protocol
     * 
     */
    public Output<RadiusServerProfileProtocolArgs> protocol() {
        return this.protocol;
    }

    /**
     * The number of RADIUS server retries
     * 
     */
    @Import(name="retries")
    private @Nullable Output<Integer> retries;

    /**
     * @return The number of RADIUS server retries
     * 
     */
    public Optional<Output<Integer>> retries() {
        return Optional.ofNullable(this.retries);
    }

    /**
     * Server
     * 
     */
    @Import(name="servers", required=true)
    private Output<List<RadiusServerProfileServerArgs>> servers;

    /**
     * @return Server
     * 
     */
    public Output<List<RadiusServerProfileServerArgs>> servers() {
        return this.servers;
    }

    /**
     * The snippet in which the resource is defined
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    @Import(name="snippet")
    private @Nullable Output<String> snippet;

    /**
     * @return The snippet in which the resource is defined
     * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
     * 
     */
    public Optional<Output<String>> snippet() {
        return Optional.ofNullable(this.snippet);
    }

    /**
     * The RADIUS server authentication timeout (seconds)
     * 
     */
    @Import(name="timeout")
    private @Nullable Output<Integer> timeout;

    /**
     * @return The RADIUS server authentication timeout (seconds)
     * 
     */
    public Optional<Output<Integer>> timeout() {
        return Optional.ofNullable(this.timeout);
    }

    private RadiusServerProfileArgs() {}

    private RadiusServerProfileArgs(RadiusServerProfileArgs $) {
        this.device = $.device;
        this.folder = $.folder;
        this.name = $.name;
        this.protocol = $.protocol;
        this.retries = $.retries;
        this.servers = $.servers;
        this.snippet = $.snippet;
        this.timeout = $.timeout;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RadiusServerProfileArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RadiusServerProfileArgs $;

        public Builder() {
            $ = new RadiusServerProfileArgs();
        }

        public Builder(RadiusServerProfileArgs defaults) {
            $ = new RadiusServerProfileArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param device The device in which the resource is defined
         * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
         * 
         * @return builder
         * 
         */
        public Builder device(@Nullable Output<String> device) {
            $.device = device;
            return this;
        }

        /**
         * @param device The device in which the resource is defined
         * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
         * 
         * @return builder
         * 
         */
        public Builder device(String device) {
            return device(Output.of(device));
        }

        /**
         * @param folder The folder in which the resource is defined
         * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
         * 
         * @return builder
         * 
         */
        public Builder folder(@Nullable Output<String> folder) {
            $.folder = folder;
            return this;
        }

        /**
         * @param folder The folder in which the resource is defined
         * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
         * 
         * @return builder
         * 
         */
        public Builder folder(String folder) {
            return folder(Output.of(folder));
        }

        /**
         * @param name The name of the RADIUS server profile
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the RADIUS server profile
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param protocol The RADIUS authentication protocol
         * 
         * @return builder
         * 
         */
        public Builder protocol(Output<RadiusServerProfileProtocolArgs> protocol) {
            $.protocol = protocol;
            return this;
        }

        /**
         * @param protocol The RADIUS authentication protocol
         * 
         * @return builder
         * 
         */
        public Builder protocol(RadiusServerProfileProtocolArgs protocol) {
            return protocol(Output.of(protocol));
        }

        /**
         * @param retries The number of RADIUS server retries
         * 
         * @return builder
         * 
         */
        public Builder retries(@Nullable Output<Integer> retries) {
            $.retries = retries;
            return this;
        }

        /**
         * @param retries The number of RADIUS server retries
         * 
         * @return builder
         * 
         */
        public Builder retries(Integer retries) {
            return retries(Output.of(retries));
        }

        /**
         * @param servers Server
         * 
         * @return builder
         * 
         */
        public Builder servers(Output<List<RadiusServerProfileServerArgs>> servers) {
            $.servers = servers;
            return this;
        }

        /**
         * @param servers Server
         * 
         * @return builder
         * 
         */
        public Builder servers(List<RadiusServerProfileServerArgs> servers) {
            return servers(Output.of(servers));
        }

        /**
         * @param servers Server
         * 
         * @return builder
         * 
         */
        public Builder servers(RadiusServerProfileServerArgs... servers) {
            return servers(List.of(servers));
        }

        /**
         * @param snippet The snippet in which the resource is defined
         * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
         * 
         * @return builder
         * 
         */
        public Builder snippet(@Nullable Output<String> snippet) {
            $.snippet = snippet;
            return this;
        }

        /**
         * @param snippet The snippet in which the resource is defined
         * &gt; ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
         * 
         * @return builder
         * 
         */
        public Builder snippet(String snippet) {
            return snippet(Output.of(snippet));
        }

        /**
         * @param timeout The RADIUS server authentication timeout (seconds)
         * 
         * @return builder
         * 
         */
        public Builder timeout(@Nullable Output<Integer> timeout) {
            $.timeout = timeout;
            return this;
        }

        /**
         * @param timeout The RADIUS server authentication timeout (seconds)
         * 
         * @return builder
         * 
         */
        public Builder timeout(Integer timeout) {
            return timeout(Output.of(timeout));
        }

        public RadiusServerProfileArgs build() {
            if ($.protocol == null) {
                throw new MissingRequiredPropertyException("RadiusServerProfileArgs", "protocol");
            }
            if ($.servers == null) {
                throw new MissingRequiredPropertyException("RadiusServerProfileArgs", "servers");
            }
            return $;
        }
    }

}
