// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.scm;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.scm.ScepProfileArgs;
import com.pulumi.scm.Utilities;
import com.pulumi.scm.inputs.ScepProfileState;
import com.pulumi.scm.outputs.ScepProfileAlgorithm;
import com.pulumi.scm.outputs.ScepProfileCertificateAttributes;
import com.pulumi.scm.outputs.ScepProfileScepChallenge;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ScepProfile resource
 * 
 */
@ResourceType(type="scm:index/scepProfile:ScepProfile")
public class ScepProfile extends com.pulumi.resources.CustomResource {
    /**
     * Algorithm
     * 
     */
    @Export(name="algorithm", refs={ScepProfileAlgorithm.class}, tree="[0]")
    private Output<ScepProfileAlgorithm> algorithm;

    /**
     * @return Algorithm
     * 
     */
    public Output<ScepProfileAlgorithm> algorithm() {
        return this.algorithm;
    }
    /**
     * Certificate Authority identity
     * 
     */
    @Export(name="caIdentityName", refs={String.class}, tree="[0]")
    private Output<String> caIdentityName;

    /**
     * @return Certificate Authority identity
     * 
     */
    public Output<String> caIdentityName() {
        return this.caIdentityName;
    }
    /**
     * Subject Alternative name type
     * 
     */
    @Export(name="certificateAttributes", refs={ScepProfileCertificateAttributes.class}, tree="[0]")
    private Output</* @Nullable */ ScepProfileCertificateAttributes> certificateAttributes;

    /**
     * @return Subject Alternative name type
     * 
     */
    public Output<Optional<ScepProfileCertificateAttributes>> certificateAttributes() {
        return Codegen.optional(this.certificateAttributes);
    }
    /**
     * The device in which the resource is defined
     * 
     */
    @Export(name="device", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> device;

    /**
     * @return The device in which the resource is defined
     * 
     */
    public Output<Optional<String>> device() {
        return Codegen.optional(this.device);
    }
    /**
     * Digest for CSR
     * 
     */
    @Export(name="digest", refs={String.class}, tree="[0]")
    private Output<String> digest;

    /**
     * @return Digest for CSR
     * 
     */
    public Output<String> digest() {
        return this.digest;
    }
    /**
     * Map of sensitive values returned from the API.
     * 
     */
    @Export(name="encryptedValues", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output<Map<String,String>> encryptedValues;

    /**
     * @return Map of sensitive values returned from the API.
     * 
     */
    public Output<Map<String,String>> encryptedValues() {
        return this.encryptedValues;
    }
    /**
     * CA certificate fingerprint
     * 
     */
    @Export(name="fingerprint", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> fingerprint;

    /**
     * @return CA certificate fingerprint
     * 
     */
    public Output<Optional<String>> fingerprint() {
        return Codegen.optional(this.fingerprint);
    }
    /**
     * The folder in which the resource is defined
     * 
     */
    @Export(name="folder", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> folder;

    /**
     * @return The folder in which the resource is defined
     * 
     */
    public Output<Optional<String>> folder() {
        return Codegen.optional(this.folder);
    }
    /**
     * The name of the SCEP profile
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the SCEP profile
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * SCEP server CA certificate
     * 
     */
    @Export(name="scepCaCert", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> scepCaCert;

    /**
     * @return SCEP server CA certificate
     * 
     */
    public Output<Optional<String>> scepCaCert() {
        return Codegen.optional(this.scepCaCert);
    }
    /**
     * One Time Password challenge
     * 
     */
    @Export(name="scepChallenge", refs={ScepProfileScepChallenge.class}, tree="[0]")
    private Output<ScepProfileScepChallenge> scepChallenge;

    /**
     * @return One Time Password challenge
     * 
     */
    public Output<ScepProfileScepChallenge> scepChallenge() {
        return this.scepChallenge;
    }
    /**
     * SCEP client ceertificate
     * 
     */
    @Export(name="scepClientCert", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> scepClientCert;

    /**
     * @return SCEP client ceertificate
     * 
     */
    public Output<Optional<String>> scepClientCert() {
        return Codegen.optional(this.scepClientCert);
    }
    /**
     * SCEP server URL
     * 
     */
    @Export(name="scepUrl", refs={String.class}, tree="[0]")
    private Output<String> scepUrl;

    /**
     * @return SCEP server URL
     * 
     */
    public Output<String> scepUrl() {
        return this.scepUrl;
    }
    /**
     * The snippet in which the resource is defined
     * 
     */
    @Export(name="snippet", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> snippet;

    /**
     * @return The snippet in which the resource is defined
     * 
     */
    public Output<Optional<String>> snippet() {
        return Codegen.optional(this.snippet);
    }
    /**
     * Subject
     * 
     */
    @Export(name="subject", refs={String.class}, tree="[0]")
    private Output<String> subject;

    /**
     * @return Subject
     * 
     */
    public Output<String> subject() {
        return this.subject;
    }
    @Export(name="tfid", refs={String.class}, tree="[0]")
    private Output<String> tfid;

    public Output<String> tfid() {
        return this.tfid;
    }
    /**
     * Use as digital signature?
     * 
     */
    @Export(name="useAsDigitalSignature", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> useAsDigitalSignature;

    /**
     * @return Use as digital signature?
     * 
     */
    public Output<Optional<Boolean>> useAsDigitalSignature() {
        return Codegen.optional(this.useAsDigitalSignature);
    }
    /**
     * Use for key encipherment?
     * 
     */
    @Export(name="useForKeyEncipherment", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> useForKeyEncipherment;

    /**
     * @return Use for key encipherment?
     * 
     */
    public Output<Optional<Boolean>> useForKeyEncipherment() {
        return Codegen.optional(this.useForKeyEncipherment);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ScepProfile(java.lang.String name) {
        this(name, ScepProfileArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ScepProfile(java.lang.String name, ScepProfileArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ScepProfile(java.lang.String name, ScepProfileArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("scm:index/scepProfile:ScepProfile", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ScepProfile(java.lang.String name, Output<java.lang.String> id, @Nullable ScepProfileState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("scm:index/scepProfile:ScepProfile", name, state, makeResourceOptions(options, id), false);
    }

    private static ScepProfileArgs makeArgs(ScepProfileArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ScepProfileArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "encryptedValues"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ScepProfile get(java.lang.String name, Output<java.lang.String> id, @Nullable ScepProfileState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ScepProfile(name, id, state, options);
    }
}
