// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class AddressGroupDynamicValueArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Tag based filter defining group membership e.g. `tag1 AND tag2 OR tag3`. String length must not exceed 2047 characters.
        /// </summary>
        [Input("filter", required: true)]
        public Input<string> Filter { get; set; } = null!;

        public AddressGroupDynamicValueArgs()
        {
        }
        public static new AddressGroupDynamicValueArgs Empty => new AddressGroupDynamicValueArgs();
    }
}
