// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class ApplicationDefaultArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Ident by icmp6 type
        /// </summary>
        [Input("identByIcmp6Type")]
        public Input<Inputs.ApplicationDefaultIdentByIcmp6TypeArgs>? IdentByIcmp6Type { get; set; }

        /// <summary>
        /// Ident by icmp type
        /// </summary>
        [Input("identByIcmpType")]
        public Input<Inputs.ApplicationDefaultIdentByIcmpTypeArgs>? IdentByIcmpType { get; set; }

        /// <summary>
        /// Ident by ip protocol
        /// </summary>
        [Input("identByIpProtocol")]
        public Input<string>? IdentByIpProtocol { get; set; }

        [Input("ports")]
        private InputList<string>? _ports;

        /// <summary>
        /// Port
        /// </summary>
        public InputList<string> Ports
        {
            get => _ports ?? (_ports = new InputList<string>());
            set => _ports = value;
        }

        public ApplicationDefaultArgs()
        {
        }
        public static new ApplicationDefaultArgs Empty => new ApplicationDefaultArgs();
    }
}
