// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class AuthenticationSettingAuthenticationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Accounting server profile
        /// </summary>
        [Input("accountingServerProfile")]
        public Input<string>? AccountingServerProfile { get; set; }

        /// <summary>
        /// Authentication profile
        /// </summary>
        [Input("authenticationProfile")]
        public Input<string>? AuthenticationProfile { get; set; }

        /// <summary>
        /// Certificate profile
        /// </summary>
        [Input("certificateProfile")]
        public Input<string>? CertificateProfile { get; set; }

        public AuthenticationSettingAuthenticationGetArgs()
        {
        }
        public static new AuthenticationSettingAuthenticationGetArgs Empty => new AuthenticationSettingAuthenticationGetArgs();
    }
}
