// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class BgpAddressFamilyProfileIpv4GetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Multicast
        /// </summary>
        [Input("multicast")]
        public Input<Inputs.BgpAddressFamilyProfileIpv4MulticastGetArgs>? Multicast { get; set; }

        /// <summary>
        /// Unicast
        /// </summary>
        [Input("unicast")]
        public Input<Inputs.BgpAddressFamilyProfileIpv4UnicastGetArgs>? Unicast { get; set; }

        public BgpAddressFamilyProfileIpv4GetArgs()
        {
        }
        public static new BgpAddressFamilyProfileIpv4GetArgs Empty => new BgpAddressFamilyProfileIpv4GetArgs();
    }
}
