// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class BgpAddressFamilyProfileIpv4Ipv4MulticastGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Add path
        /// </summary>
        [Input("addPath")]
        public Input<Inputs.BgpAddressFamilyProfileIpv4Ipv4MulticastAddPathGetArgs>? AddPath { get; set; }

        /// <summary>
        /// Allowas in
        /// </summary>
        [Input("allowasIn")]
        public Input<Inputs.BgpAddressFamilyProfileIpv4Ipv4MulticastAllowasInGetArgs>? AllowasIn { get; set; }

        /// <summary>
        /// Override ASNs in outbound updates if AS-Path equals Remote-AS?
        /// </summary>
        [Input("asOverride")]
        public Input<bool>? AsOverride { get; set; }

        /// <summary>
        /// Originate default route?
        /// </summary>
        [Input("defaultOriginate")]
        public Input<bool>? DefaultOriginate { get; set; }

        /// <summary>
        /// Default originate route map
        /// </summary>
        [Input("defaultOriginateMap")]
        public Input<string>? DefaultOriginateMap { get; set; }

        /// <summary>
        /// Enable?
        /// </summary>
        [Input("enable")]
        public Input<bool>? Enable { get; set; }

        /// <summary>
        /// Maximum prefix
        /// </summary>
        [Input("maximumPrefix")]
        public Input<Inputs.BgpAddressFamilyProfileIpv4Ipv4MulticastMaximumPrefixGetArgs>? MaximumPrefix { get; set; }

        /// <summary>
        /// Next hop
        /// </summary>
        [Input("nextHop")]
        public Input<Inputs.BgpAddressFamilyProfileIpv4Ipv4MulticastNextHopGetArgs>? NextHop { get; set; }

        /// <summary>
        /// Orf
        /// </summary>
        [Input("orf")]
        public Input<Inputs.BgpAddressFamilyProfileIpv4Ipv4MulticastOrfGetArgs>? Orf { get; set; }

        /// <summary>
        /// Remove private a s
        /// </summary>
        [Input("removePrivateAS")]
        public Input<Inputs.BgpAddressFamilyProfileIpv4Ipv4MulticastRemovePrivateASGetArgs>? RemovePrivateAS { get; set; }

        /// <summary>
        /// Route reflector client?
        /// </summary>
        [Input("routeReflectorClient")]
        public Input<bool>? RouteReflectorClient { get; set; }

        /// <summary>
        /// Send community
        /// </summary>
        [Input("sendCommunity")]
        public Input<Inputs.BgpAddressFamilyProfileIpv4Ipv4MulticastSendCommunityGetArgs>? SendCommunity { get; set; }

        /// <summary>
        /// Soft reconfiguration of peer with stored routes?
        /// </summary>
        [Input("softReconfigWithStoredInfo")]
        public Input<bool>? SoftReconfigWithStoredInfo { get; set; }

        public BgpAddressFamilyProfileIpv4Ipv4MulticastGetArgs()
        {
        }
        public static new BgpAddressFamilyProfileIpv4Ipv4MulticastGetArgs Empty => new BgpAddressFamilyProfileIpv4Ipv4MulticastGetArgs();
    }
}
