// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class BgpRouteMapRedistributionBgpOspfRouteMapMatchIpv4Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// bgp-route-map-redistributions ipv4 object address
        /// </summary>
        [Input("address")]
        public Input<Inputs.BgpRouteMapRedistributionBgpOspfRouteMapMatchIpv4AddressArgs>? Address { get; set; }

        /// <summary>
        /// bgp-route-map-redistributions ipv4 object next*hop
        /// </summary>
        [Input("nextHop")]
        public Input<Inputs.BgpRouteMapRedistributionBgpOspfRouteMapMatchIpv4NextHopArgs>? NextHop { get; set; }

        /// <summary>
        /// bgp-route-map-redistributions ipv4 object route*source
        /// </summary>
        [Input("routeSource")]
        public Input<Inputs.BgpRouteMapRedistributionBgpOspfRouteMapMatchIpv4RouteSourceArgs>? RouteSource { get; set; }

        public BgpRouteMapRedistributionBgpOspfRouteMapMatchIpv4Args()
        {
        }
        public static new BgpRouteMapRedistributionBgpOspfRouteMapMatchIpv4Args Empty => new BgpRouteMapRedistributionBgpOspfRouteMapMatchIpv4Args();
    }
}
