// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class ExternalDynamicListTypeDomainRecurringArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Daily
        /// </summary>
        [Input("daily")]
        public Input<Inputs.ExternalDynamicListTypeDomainRecurringDailyArgs>? Daily { get; set; }

        /// <summary>
        /// Five minute
        /// </summary>
        [Input("fiveMinute")]
        public Input<Inputs.ExternalDynamicListTypeDomainRecurringFiveMinuteArgs>? FiveMinute { get; set; }

        /// <summary>
        /// Hourly
        /// </summary>
        [Input("hourly")]
        public Input<Inputs.ExternalDynamicListTypeDomainRecurringHourlyArgs>? Hourly { get; set; }

        /// <summary>
        /// Monthly
        /// </summary>
        [Input("monthly")]
        public Input<Inputs.ExternalDynamicListTypeDomainRecurringMonthlyArgs>? Monthly { get; set; }

        /// <summary>
        /// Weekly
        /// </summary>
        [Input("weekly")]
        public Input<Inputs.ExternalDynamicListTypeDomainRecurringWeeklyArgs>? Weekly { get; set; }

        public ExternalDynamicListTypeDomainRecurringArgs()
        {
        }
        public static new ExternalDynamicListTypeDomainRecurringArgs Empty => new ExternalDynamicListTypeDomainRecurringArgs();
    }
}
