// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class HipObjectNetworkInfoCriteriaNetworkIsNotGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Ethernet
        /// </summary>
        [Input("ethernet")]
        public Input<Inputs.HipObjectNetworkInfoCriteriaNetworkIsNotEthernetGetArgs>? Ethernet { get; set; }

        /// <summary>
        /// Mobile
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Ethernet`, `Mobile`, `Unknown`, and `Wifi`.
        /// </summary>
        [Input("mobile")]
        public Input<Inputs.HipObjectNetworkInfoCriteriaNetworkIsNotMobileGetArgs>? Mobile { get; set; }

        /// <summary>
        /// Unknown
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Ethernet`, `Mobile`, `Unknown`, and `Wifi`.
        /// </summary>
        [Input("unknown")]
        public Input<Inputs.HipObjectNetworkInfoCriteriaNetworkIsNotUnknownGetArgs>? Unknown { get; set; }

        /// <summary>
        /// Wifi
        /// 
        /// &gt; ℹ️ **Note:** You must specify exactly one of `Ethernet`, `Mobile`, `Unknown`, and `Wifi`.
        /// </summary>
        [Input("wifi")]
        public Input<Inputs.HipObjectNetworkInfoCriteriaNetworkIsNotWifiGetArgs>? Wifi { get; set; }

        public HipObjectNetworkInfoCriteriaNetworkIsNotGetArgs()
        {
        }
        public static new HipObjectNetworkInfoCriteriaNetworkIsNotGetArgs Empty => new HipObjectNetworkInfoCriteriaNetworkIsNotGetArgs();
    }
}
