// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class IkeGatewayLocalAddressGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Interface variable or hardcoded vlan/loopback. vlan will be passed as default value
        /// </summary>
        [Input("interface")]
        public Input<string>? Interface { get; set; }

        /// <summary>
        /// IP Prefix of the assigned interface
        /// </summary>
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        public IkeGatewayLocalAddressGetArgs()
        {
        }
        public static new IkeGatewayLocalAddressGetArgs Empty => new IkeGatewayLocalAddressGetArgs();
    }
}
