// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class LogicalRouterVrfVrAdminDistsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Ebgp
        /// </summary>
        [Input("ebgp")]
        public Input<double>? Ebgp { get; set; }

        /// <summary>
        /// Ibgp
        /// </summary>
        [Input("ibgp")]
        public Input<double>? Ibgp { get; set; }

        /// <summary>
        /// Ospf ext
        /// </summary>
        [Input("ospfExt")]
        public Input<double>? OspfExt { get; set; }

        /// <summary>
        /// Ospf int
        /// </summary>
        [Input("ospfInt")]
        public Input<double>? OspfInt { get; set; }

        /// <summary>
        /// Ospfv3 ext
        /// </summary>
        [Input("ospfv3Ext")]
        public Input<double>? Ospfv3Ext { get; set; }

        /// <summary>
        /// Ospfv3 int
        /// </summary>
        [Input("ospfv3Int")]
        public Input<double>? Ospfv3Int { get; set; }

        /// <summary>
        /// Rip
        /// </summary>
        [Input("rip")]
        public Input<double>? Rip { get; set; }

        /// <summary>
        /// Static
        /// </summary>
        [Input("static")]
        public Input<double>? Static { get; set; }

        /// <summary>
        /// Static ipv6
        /// </summary>
        [Input("staticIpv6")]
        public Input<double>? StaticIpv6 { get; set; }

        public LogicalRouterVrfVrAdminDistsGetArgs()
        {
        }
        public static new LogicalRouterVrfVrAdminDistsGetArgs Empty => new LogicalRouterVrfVrAdminDistsGetArgs();
    }
}
