// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class LogicalRouterVrfBgpPolicyExportRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Action
        /// </summary>
        [Input("action")]
        public Input<Inputs.LogicalRouterVrfBgpPolicyExportRuleActionArgs>? Action { get; set; }

        /// <summary>
        /// Enable
        /// </summary>
        [Input("enable")]
        public Input<bool>? Enable { get; set; }

        /// <summary>
        /// Match
        /// </summary>
        [Input("match")]
        public Input<Inputs.LogicalRouterVrfBgpPolicyExportRuleMatchArgs>? Match { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("usedBies")]
        private InputList<string>? _usedBies;

        /// <summary>
        /// Used by
        /// </summary>
        public InputList<string> UsedBies
        {
            get => _usedBies ?? (_usedBies = new InputList<string>());
            set => _usedBies = value;
        }

        public LogicalRouterVrfBgpPolicyExportRuleArgs()
        {
        }
        public static new LogicalRouterVrfBgpPolicyExportRuleArgs Empty => new LogicalRouterVrfBgpPolicyExportRuleArgs();
    }
}
