// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class LogicalRouterVrfMulticastMsdpArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable
        /// </summary>
        [Input("enable")]
        public Input<bool>? Enable { get; set; }

        /// <summary>
        /// Global authentication
        /// </summary>
        [Input("globalAuthentication")]
        public Input<string>? GlobalAuthentication { get; set; }

        /// <summary>
        /// Global timer
        /// </summary>
        [Input("globalTimer")]
        public Input<string>? GlobalTimer { get; set; }

        /// <summary>
        /// Originator id
        /// </summary>
        [Input("originatorId")]
        public Input<Inputs.LogicalRouterVrfMulticastMsdpOriginatorIdArgs>? OriginatorId { get; set; }

        [Input("peers")]
        private InputList<Inputs.LogicalRouterVrfMulticastMsdpPeerArgs>? _peers;

        /// <summary>
        /// Peer
        /// </summary>
        public InputList<Inputs.LogicalRouterVrfMulticastMsdpPeerArgs> Peers
        {
            get => _peers ?? (_peers = new InputList<Inputs.LogicalRouterVrfMulticastMsdpPeerArgs>());
            set => _peers = value;
        }

        public LogicalRouterVrfMulticastMsdpArgs()
        {
        }
        public static new LogicalRouterVrfMulticastMsdpArgs Empty => new LogicalRouterVrfMulticastMsdpArgs();
    }
}
