// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class LogicalRouterVrfBgpPolicyAggregationAddressSuppressFilterArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable
        /// </summary>
        [Input("enable")]
        public Input<bool>? Enable { get; set; }

        /// <summary>
        /// Match
        /// </summary>
        [Input("match")]
        public Input<Inputs.LogicalRouterVrfBgpPolicyAggregationAddressSuppressFilterMatchArgs>? Match { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public LogicalRouterVrfBgpPolicyAggregationAddressSuppressFilterArgs()
        {
        }
        public static new LogicalRouterVrfBgpPolicyAggregationAddressSuppressFilterArgs Empty => new LogicalRouterVrfBgpPolicyAggregationAddressSuppressFilterArgs();
    }
}
