// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class RegionGeoLocationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// latitude coordinate. Value must be between -90 and 90.
        /// </summary>
        [Input("latitude", required: true)]
        public Input<double> Latitude { get; set; } = null!;

        /// <summary>
        /// longitude coordinate. Value must be between -180 and 180.
        /// </summary>
        [Input("longitude", required: true)]
        public Input<double> Longitude { get; set; } = null!;

        public RegionGeoLocationArgs()
        {
        }
        public static new RegionGeoLocationArgs Empty => new RegionGeoLocationArgs();
    }
}
