// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class SecurityRuleDefaultProfileSettingsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Dlp
        /// </summary>
        [Input("dlp")]
        public Input<string>? Dlp { get; set; }

        /// <summary>
        /// File control
        /// </summary>
        [Input("fileControl")]
        public Input<Inputs.SecurityRuleDefaultProfileSettingsFileControlGetArgs>? FileControl { get; set; }

        public SecurityRuleDefaultProfileSettingsGetArgs()
        {
        }
        public static new SecurityRuleDefaultProfileSettingsGetArgs Empty => new SecurityRuleDefaultProfileSettingsGetArgs();
    }
}
