// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class ServiceRouteRouteDestinationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Source
        /// </summary>
        [Input("source")]
        public Input<Inputs.ServiceRouteRouteDestinationSourceGetArgs>? Source { get; set; }

        public ServiceRouteRouteDestinationGetArgs()
        {
        }
        public static new ServiceRouteRouteDestinationGetArgs Empty => new ServiceRouteRouteDestinationGetArgs();
    }
}
