// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class UpdateScheduleUpdateScheduleAntiVirusRecurringDailyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Action
        /// </summary>
        [Input("action")]
        public Input<string>? Action { get; set; }

        /// <summary>
        /// At
        /// </summary>
        [Input("at", required: true)]
        public Input<string> At { get; set; } = null!;

        public UpdateScheduleUpdateScheduleAntiVirusRecurringDailyGetArgs()
        {
        }
        public static new UpdateScheduleUpdateScheduleAntiVirusRecurringDailyGetArgs Empty => new UpdateScheduleUpdateScheduleAntiVirusRecurringDailyGetArgs();
    }
}
