// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scm.Inputs
{

    public sealed class ZoneProtectionProfileFloodTcpSynArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// When the flow exceeds the `ActivateRate`` threshold, the firewall drops individual SYN packets randomly to restrict the flow.
        /// </summary>
        [Input("activateRate")]
        public Input<int>? ActivateRate { get; set; }

        /// <summary>
        /// When the flow exceeds the `AlertRate`` threshold, an alarm is generated.
        /// </summary>
        [Input("alarmRate")]
        public Input<int>? AlarmRate { get; set; }

        /// <summary>
        /// Enable protection against SYN floods?
        /// </summary>
        [Input("enable")]
        public Input<bool>? Enable { get; set; }

        /// <summary>
        /// When the flow exceeds the `MaximalRate` threshold, 100% of incoming SYN packets are dropped.
        /// </summary>
        [Input("maximalRate")]
        public Input<int>? MaximalRate { get; set; }

        public ZoneProtectionProfileFloodTcpSynArgs()
        {
        }
        public static new ZoneProtectionProfileFloodTcpSynArgs Empty => new ZoneProtectionProfileFloodTcpSynArgs();
    }
}
