// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Retrieves a listing of config items.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scm from "@pulumi/scm";
 *
 * function tryOutput_(
 * 	...fns: Array<() => pulumi.Input<any>>
 * ): pulumi.Output<any> {
 * 	if (fns.length === 0) {
 * 		throw new Error("try: all parameters failed");
 * 	}
 * 	const [fn, ...rest] = fns;
 * 	try {
 * 		return pulumi.output(fn()).apply(result => result !== undefined ? result : tryOutput_(...rest));
 * 	} catch {
 * 		return tryOutput_(...rest);
 * 	}
 * 	throw new Error("try: all parameters failed");
 * }
 *
 *
 * // This data source will call the "List" API endpoint
 * // and return all application filters in the "All" folder.
 * // 1. Use a single data block to fetch ALL application filters in the "All" folder.
 * const allShared = scm.getApplicationFilterList({
 *     folder: "All",
 * });
 * export const applicationFiltersRawData = tryOutput_(
 *     () => allShared,
 *     () => null
 * );
 * // Simplified pagination example with error handling
 * const paginatedApplicationFiltersExample = scm.getApplicationFilterList({
 *     folder: "All",
 *     limit: 5,
 *     offset: 0,
 * });
 * export const paginatedApplicationFilters = tryOutput_(
 *     () => paginatedApplicationFiltersExample.then(paginatedApplicationFiltersExample => .reduce((__obj, applicationFilter) => ({ ...__obj, [applicationFilter.id]: applicationFilter }), {})),
 *     () => {}
 * );
 * export const paginationApplicationFiltersDetails = tryOutput_(
 *     () => {
 *         totalObjectsInFolder: paginatedApplicationFiltersExample.then(paginatedApplicationFiltersExample => paginatedApplicationFiltersExample.total),
 *         limitUsed: paginatedApplicationFiltersExample.then(paginatedApplicationFiltersExample => paginatedApplicationFiltersExample.limit),
 *         offsetUsed: paginatedApplicationFiltersExample.then(paginatedApplicationFiltersExample => paginatedApplicationFiltersExample.offset),
 *     },
 *     () => {}
 * );
 * ```
 */
export function getApplicationFilterList(args?: GetApplicationFilterListArgs, opts?: pulumi.InvokeOptions): Promise<GetApplicationFilterListResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("scm:index/getApplicationFilterList:getApplicationFilterList", {
        "device": args.device,
        "folder": args.folder,
        "limit": args.limit,
        "name": args.name,
        "offset": args.offset,
        "snippet": args.snippet,
    }, opts);
}

/**
 * A collection of arguments for invoking getApplicationFilterList.
 */
export interface GetApplicationFilterListArgs {
    /**
     * The device of the item.
     */
    device?: string;
    /**
     * The folder of the item. Default: Shared.
     */
    folder?: string;
    /**
     * The max number of items to return. Default: 200.
     */
    limit?: number;
    /**
     * The name of the item.
     */
    name?: string;
    /**
     * The offset of the first item to return.
     */
    offset?: number;
    /**
     * The snippet of the item.
     */
    snippet?: string;
}

/**
 * A collection of values returned by getApplicationFilterList.
 */
export interface GetApplicationFilterListResult {
    /**
     * The data.
     */
    readonly datas: outputs.GetApplicationFilterListData[];
    /**
     * The device of the item.
     */
    readonly device?: string;
    /**
     * The folder of the item. Default: Shared.
     */
    readonly folder?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The max number of items to return. Default: 200.
     */
    readonly limit?: number;
    /**
     * The name of the item.
     */
    readonly name?: string;
    /**
     * The offset of the first item to return.
     */
    readonly offset?: number;
    /**
     * The snippet of the item.
     */
    readonly snippet?: string;
    /**
     * The Terraform ID.
     */
    readonly tfid: string;
    /**
     * The total number of items.
     */
    readonly total: number;
}
/**
 * Retrieves a listing of config items.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scm from "@pulumi/scm";
 *
 * function tryOutput_(
 * 	...fns: Array<() => pulumi.Input<any>>
 * ): pulumi.Output<any> {
 * 	if (fns.length === 0) {
 * 		throw new Error("try: all parameters failed");
 * 	}
 * 	const [fn, ...rest] = fns;
 * 	try {
 * 		return pulumi.output(fn()).apply(result => result !== undefined ? result : tryOutput_(...rest));
 * 	} catch {
 * 		return tryOutput_(...rest);
 * 	}
 * 	throw new Error("try: all parameters failed");
 * }
 *
 *
 * // This data source will call the "List" API endpoint
 * // and return all application filters in the "All" folder.
 * // 1. Use a single data block to fetch ALL application filters in the "All" folder.
 * const allShared = scm.getApplicationFilterList({
 *     folder: "All",
 * });
 * export const applicationFiltersRawData = tryOutput_(
 *     () => allShared,
 *     () => null
 * );
 * // Simplified pagination example with error handling
 * const paginatedApplicationFiltersExample = scm.getApplicationFilterList({
 *     folder: "All",
 *     limit: 5,
 *     offset: 0,
 * });
 * export const paginatedApplicationFilters = tryOutput_(
 *     () => paginatedApplicationFiltersExample.then(paginatedApplicationFiltersExample => .reduce((__obj, applicationFilter) => ({ ...__obj, [applicationFilter.id]: applicationFilter }), {})),
 *     () => {}
 * );
 * export const paginationApplicationFiltersDetails = tryOutput_(
 *     () => {
 *         totalObjectsInFolder: paginatedApplicationFiltersExample.then(paginatedApplicationFiltersExample => paginatedApplicationFiltersExample.total),
 *         limitUsed: paginatedApplicationFiltersExample.then(paginatedApplicationFiltersExample => paginatedApplicationFiltersExample.limit),
 *         offsetUsed: paginatedApplicationFiltersExample.then(paginatedApplicationFiltersExample => paginatedApplicationFiltersExample.offset),
 *     },
 *     () => {}
 * );
 * ```
 */
export function getApplicationFilterListOutput(args?: GetApplicationFilterListOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetApplicationFilterListResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("scm:index/getApplicationFilterList:getApplicationFilterList", {
        "device": args.device,
        "folder": args.folder,
        "limit": args.limit,
        "name": args.name,
        "offset": args.offset,
        "snippet": args.snippet,
    }, opts);
}

/**
 * A collection of arguments for invoking getApplicationFilterList.
 */
export interface GetApplicationFilterListOutputArgs {
    /**
     * The device of the item.
     */
    device?: pulumi.Input<string | undefined>;
    /**
     * The folder of the item. Default: Shared.
     */
    folder?: pulumi.Input<string | undefined>;
    /**
     * The max number of items to return. Default: 200.
     */
    limit?: pulumi.Input<number | undefined>;
    /**
     * The name of the item.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The offset of the first item to return.
     */
    offset?: pulumi.Input<number | undefined>;
    /**
     * The snippet of the item.
     */
    snippet?: pulumi.Input<string | undefined>;
}
