// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Retrieves a config item.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scm from "@pulumi/scm";
 *
 * const example = scm.getKerberosServerProfile({
 *     id: "1234-56-789",
 * });
 * ```
 */
export function getKerberosServerProfile(args: GetKerberosServerProfileArgs, opts?: pulumi.InvokeOptions): Promise<GetKerberosServerProfileResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("scm:index/getKerberosServerProfile:getKerberosServerProfile", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getKerberosServerProfile.
 */
export interface GetKerberosServerProfileArgs {
    /**
     * The Id param.
     */
    id: string;
}

/**
 * A collection of values returned by getKerberosServerProfile.
 */
export interface GetKerberosServerProfileResult {
    /**
     * The Id param.
     */
    readonly id: string;
    /**
     * The Servers param.
     */
    readonly servers: outputs.GetKerberosServerProfileServer[];
    readonly tfid: string;
}
/**
 * Retrieves a config item.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scm from "@pulumi/scm";
 *
 * const example = scm.getKerberosServerProfile({
 *     id: "1234-56-789",
 * });
 * ```
 */
export function getKerberosServerProfileOutput(args: GetKerberosServerProfileOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetKerberosServerProfileResult> {
    return pulumi.output(args).apply((a: any) => getKerberosServerProfile(a, opts))
}

/**
 * A collection of arguments for invoking getKerberosServerProfile.
 */
export interface GetKerberosServerProfileOutputArgs {
    /**
     * The Id param.
     */
    id: pulumi.Input<string>;
}
