// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * TlsServiceProfile data source
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scm from "@pulumi/scm";
 *
 * //
 * // Data source to retrieve a single SCM TLS Service Profile object by its ID.
 * //
 * // Replace the ID with the UUID of the SCM TLS Service Profile you want to find.
 * const scmTlsServiceProf = scm.getTlsServiceProfile({
 *     id: "b4d70015-5b0e-4491-a2a9-4305b01397d5",
 * });
 * export const scmTlsServiceProfileDetails = {
 *     profileId: scmTlsServiceProf.then(scmTlsServiceProf => scmTlsServiceProf.id),
 *     folder: scmTlsServiceProf.then(scmTlsServiceProf => scmTlsServiceProf.folder),
 *     name: scmTlsServiceProf.then(scmTlsServiceProf => scmTlsServiceProf.name),
 * };
 * ```
 */
export function getTlsServiceProfile(args: GetTlsServiceProfileArgs, opts?: pulumi.InvokeOptions): Promise<GetTlsServiceProfileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("scm:index/getTlsServiceProfile:getTlsServiceProfile", {
        "device": args.device,
        "folder": args.folder,
        "id": args.id,
        "name": args.name,
        "snippet": args.snippet,
    }, opts);
}

/**
 * A collection of arguments for invoking getTlsServiceProfile.
 */
export interface GetTlsServiceProfileArgs {
    /**
     * The device in which the resource is defined
     */
    device?: string;
    folder?: string;
    /**
     * The UUID of the TLS service profile
     */
    id: string;
    name?: string;
    snippet?: string;
}

/**
 * A collection of values returned by getTlsServiceProfile.
 */
export interface GetTlsServiceProfileResult {
    readonly certificate: string;
    /**
     * The device in which the resource is defined
     */
    readonly device: string;
    readonly folder: string;
    /**
     * The UUID of the TLS service profile
     */
    readonly id: string;
    readonly name: string;
    readonly protocolSettings: outputs.GetTlsServiceProfileProtocolSettings;
    readonly snippet: string;
    readonly tfid: string;
}
/**
 * TlsServiceProfile data source
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scm from "@pulumi/scm";
 *
 * //
 * // Data source to retrieve a single SCM TLS Service Profile object by its ID.
 * //
 * // Replace the ID with the UUID of the SCM TLS Service Profile you want to find.
 * const scmTlsServiceProf = scm.getTlsServiceProfile({
 *     id: "b4d70015-5b0e-4491-a2a9-4305b01397d5",
 * });
 * export const scmTlsServiceProfileDetails = {
 *     profileId: scmTlsServiceProf.then(scmTlsServiceProf => scmTlsServiceProf.id),
 *     folder: scmTlsServiceProf.then(scmTlsServiceProf => scmTlsServiceProf.folder),
 *     name: scmTlsServiceProf.then(scmTlsServiceProf => scmTlsServiceProf.name),
 * };
 * ```
 */
export function getTlsServiceProfileOutput(args: GetTlsServiceProfileOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTlsServiceProfileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("scm:index/getTlsServiceProfile:getTlsServiceProfile", {
        "device": args.device,
        "folder": args.folder,
        "id": args.id,
        "name": args.name,
        "snippet": args.snippet,
    }, opts);
}

/**
 * A collection of arguments for invoking getTlsServiceProfile.
 */
export interface GetTlsServiceProfileOutputArgs {
    /**
     * The device in which the resource is defined
     */
    device?: pulumi.Input<string>;
    folder?: pulumi.Input<string>;
    /**
     * The UUID of the TLS service profile
     */
    id: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    snippet?: pulumi.Input<string>;
}
